/* ================= DATA: SCENARIOS ============================================
   Node fields: id, ph (phase), kc (kill chain stage), at (clock jump, hours from start),
   enter (fx applied on arrival), if/unless (show only if flag set / skip if set),
   hours (override base time), art (evidence block), att (technique ids, first one is quizzed),
   obs (behaviour described in the quiz), disc (workshop prompt), opts.
   Option fields: q (0 poor .. 3 best), t (text), r (result), f (fail result), w (why),
   u (controls that change the odds), p (base odds), fx (extra effects), set (flag), esc (force escalation), next.
   ========================================================================== */

const SCEN = [];

/* ---------- 1. Help desk hijack ---------- */
SCEN.push({
    id: "helpdesk", name: "Help Desk Hijack",
    blurb: "A caller talks the service desk into an MFA reset. By dinner time they are in vCenter.",
    tags: ["identity", "ransomware", "pii"], start: [4, 17, 40],
    actor: "A financially motivated, English-speaking social engineering crew working with a ransomware-as-a-service affiliate. Help desk impersonation of this kind was behind several major retail and hospitality breaches in 2025.",
    sum: "was hit by a phone-based social engineering attack on its service desk, which led to vCenter access and ransomware staging",
    escSum: "ransomware detonated across the ESXi cluster.",
    pre: [
        { kc: "recon", att: "T1589", txt: "Scraped LinkedIn and the company website for finance staff names, job titles and the service desk number." },
        { kc: "weapon", att: "T1583.001", txt: "Registered a lookalike SSO domain and rented a residential proxy near head office so sign-ins would look local." }
    ],
    intro: "Friday, 17:40. The service desk lead forwards a ticket. At 16:55 a caller claiming to be {fd}, the Finance Director, said their phone had been stolen and asked for an MFA reset. The agent did it. At 17:25 the real {fd} emailed from a personal Gmail account: they can't sign in, and they never called anyone. You're the lead analyst on shift.",
    nodes: [
        { id: "hd1", ph: "ident", kc: "delivery", att: ["T1566.004", "T1656"],
          obs: "A caller impersonated the Finance Director on the phone to get the service desk to reset their MFA.",
          title: "Live account takeover",
          text: "{fd}'s account has a new authenticator registered and an active session from a residential IP a few kilometres from head office. The account can reach finance SharePoint and approves payments. What do you do first?",
          art: "17:02:11 AuditLog  User registered security info  user={fdmail}  method=AuthenticatorApp\n17:04:48 SignIn    Success  user={fdmail}  ip=203.0.113.41 (residential ISP)  device=unregistered\n17:31:09 SignIn    Success  user={fdmail}  app=SharePoint Online",
          disc: "Who in your organisation can revoke sessions and remove MFA methods at 17:45 on a Friday? How long would it take?",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke {fd}'s sessions, remove the rogue authenticator, reset, then pull logs",
              r: "Sessions revoked, the attacker's authenticator is gone and the logs are exporting. You've bought time.",
              f: "You revoke and reset... the other {fdlast}. {org} has two people with that surname and you picked the one in facilities. The real account stays live for another 40 minutes.",
              w: "With a confirmed live takeover, contain the identity first: revoke sessions (a password reset alone doesn't kill issued tokens), remove attacker MFA methods, then scope." },
            { q: 2, t: "Pull the sign-in and audit logs first so you understand the full scope before acting",
              r: "Good data, but while you read it the attacker keeps browsing SharePoint for another hour.",
              w: "Scoping matters, but with a confirmed live takeover every minute is attacker access. Contain the identity and scope in parallel." },
            { q: 1, t: "Suspend the service desk agent's account in case they're involved in the attack",
              r: "The agent is locked out and very upset. The attacker, unaffected, carries on.",
              w: "The agent was deceived, not compromised. Wrong target, and blame hides the process failure." },
            { q: 0, set: "tipped", t: "Ring the callback number on the ticket to verify whether the caller was genuine",
              r: "A friendly voice confirms everything. You have just verified the attacker with the attacker.",
              w: "Never verify using contact details supplied by the requester. Use known-good details from HR records." } ] },

        { id: "hd2", ph: "ident", kc: "exploit", att: ["T1552.001", "T1213"],
          obs: "The attacker searched the document platform for 'password' and 'vcenter' and opened an old IT handover spreadsheet.",
          title: "What did they touch?",
          text: "The audit log shows 19 SharePoint searches in 40 minutes: 'password', 'vpn', 'vcenter', 'admin'. One result, IT-Handover-2023.xlsx, was opened twice and downloaded. It contains the password for svc-vcenter. How do you scope from here?",
          art: "17:12 SearchQuery     user={fdmail}  query='password'\n17:14 SearchQuery     user={fdmail}  query='vcenter'\n17:15 FileAccessed    IT-Handover-2023.xlsx  site=/sites/IT-Archive\n17:41 FileDownloaded  IT-Handover-2023.xlsx",
          disc: "Where do plaintext credentials live in your environment right now? Wikis, spreadsheets, scripts, old tickets?",
          opts: [
            { q: 3, u: ["logs", "edr"], t: "Hunt for every svc-vcenter logon and attacker IP in the SIEM and EDR",
              r: "The hunt lights up: svc-vcenter signed in over the VPN and a remote access tool appeared on a jump box.",
              f: "The SIEM query times out twice. Someone set VPN log retention to 24 hours 'to save licence costs'. You get there slowly via the firewall's local logs.",
              w: "Assume exposed credentials were used. Hunt for the specific account and the attacker's infrastructure across identity, VPN and endpoint telemetry." },
            { q: 2, t: "Ask the CMDB owner which systems use svc-vcenter so you can prioritise your checks",
              r: "Useful map, slow answer. The CMDB owner replies two hours later with a Visio from 2019.",
              w: "Knowing what the account can reach helps prioritise, but it tells you where they could go, not where they went. Telemetry first." },
            { q: 1, t: "Run a full AV scan across every endpoint to catch anything the attacker dropped",
              r: "4,000 endpoints scan at once. Fans roar. Nothing is found, because nothing malicious has been used yet.",
              w: "Valid account abuse is living off the land. AV won't find a legitimate login with stolen credentials." },
            { q: 0, set: "tipped", t: "Ask in the all-staff Teams channel whether anyone has noticed anything unusual",
              r: "112 replies, three about the printer. If the attacker still has any mailbox or Teams access, they now know you're onto them.",
              w: "Broadcasting on a channel the attacker may be reading tips them off and floods you with noise." } ] },

        { id: "hd2x", ph: "ident", kc: "exploit", if: "tipped", enter: { heat: 1 }, att: ["T1621"],
          obs: "The attacker spammed MFA push prompts at IT staff hoping someone would approve one.",
          title: "They know you know",
          text: "Within minutes, six IT staff start getting MFA push prompts they never asked for, some at 30-second intervals. The attacker is trying to get a privileged account before the door closes.",
          opts: [
            { q: 3, u: ["idp"], t: "Warn IT out of band, block push approvals for admins, check for any approvals",
              r: "Nobody approves. The prompts stop after 20 minutes and the logs confirm no approvals.",
              w: "MFA fatigue attacks rely on one tired 'approve'. Warn people out of band and remove plain push approval for privileged users." },
            { q: 2, t: "Post a warning in the IT Teams channel telling everyone to deny all prompts",
              r: "Most see it. One is on the train with Teams closed and taps approve to make it stop.",
              w: "Right message, possibly compromised channel, and not everyone reads Teams. Go out of band." },
            { q: 1, t: "Monitor the sign-in logs closely so you can react the moment anyone approves a prompt",
              r: "Someone does, at 23:14, half asleep.",
              w: "Waiting gives the attacker unlimited attempts." },
            { q: 0, t: "Temporarily disable MFA for the IT team until the prompt storm dies down",
              r: "The prompts stop. So does the only thing standing between the attacker and the admin accounts.",
              w: "Never remove a control under attack to reduce noise." } ] },

        { id: "hd3", ph: "contain", kc: "c2", att: ["T1219", "T1133"],
          obs: "After logging into the VPN with stolen credentials, the attacker installed AnyDesk on a jump box and drove it interactively.",
          title: "Foothold on the inside",
          text: "svc-vcenter connected over the VPN from a hosting provider IP. Six minutes later AnyDesk was installed on JUMP-01, which has vCenter management rights. They're inside. What do you contain?",
          art: "18:52:07 VPN      AUTH OK  user=svc-vcenter  src=198.51.100.23 (hosting ASN)\n18:58:40 EDR      JUMP-01  anydesk.exe  signed  parent=powershell.exe\n19:03:15 vCenter  Login    user=svc-vcenter@vsphere.local  src=JUMP-01",
          disc: "Do you have a documented break-glass process for hypervisor admin access? Has anyone tested it?",
          opts: [
            { q: 3, u: ["edr", "plan"], t: "Kill svc-vcenter and its VPN session, isolate JUMP-01, fence off vCenter",
              r: "Session dropped, JUMP-01 isolated, vCenter locked down. The AnyDesk session ends mid-keystroke.",
              f: "{admin} rotates the vCenter admin password, types it too fast three times and locks out the only other vCenter admin. You have zero working vCenter admins for 35 minutes.",
              w: "Contain every access path at once: the credential, the session, the remote tool and the route to the crown jewels. Piecemeal containment gives them time to adapt." },
            { q: 2, fx: { trust: -3 }, t: "Shut down the corporate VPN for everyone so nobody can get in from outside",
              r: "It works. It also cuts off 300 remote staff, the on-call DBA and the warehouse night shift.",
              w: "Effective and sometimes necessary, but blunt. AnyDesk is a second path that doesn't need your VPN. Pair it with endpoint isolation." },
            { q: 1, t: "Power off JUMP-01 immediately so AnyDesk can't be used on it any more",
              r: "The box goes dark and so does the memory evidence. svc-vcenter is still valid and the VPN still accepts it.",
              w: "Powering off destroys volatile evidence and leaves the stolen credential live. Isolate with EDR and revoke the account." },
            { q: 0, t: "Watch them quietly for a while to learn their tools and objectives first",
              r: "You watch them snapshot the domain controller VM and copy it out. That was the intelligence.",
              w: "Watching an attacker only makes sense with strong visibility and the ability to cut them off instantly. With vCenter in play, contain now." } ] },

        { id: "hd4", ph: "contain", kc: "actions", at: 3.8, att: ["T1490", "T1484.001"],
          obs: "The attacker deleted volume shadow copies and pushed a Group Policy change, classic ransomware staging.",
          title: "Staging for detonation",
          text: "EDR alerts on two file servers: shadow copies are being deleted. A new GPO called 'Update-Policy' was linked to the Servers OU ten minutes ago and launches a scheduled task. This is ransomware staging. Your move.",
          art: "21:18 AD   GPO created 'Update-Policy'  by=helpdesk_tmp  linked=OU=Servers\n21:27 EDR  FS-02  vssadmin.exe delete shadows /all /quiet\n21:29 EDR  FS-03  wmic.exe shadowcopy delete",
          disc: "Is your IR lead pre-authorised to take servers offline without executive sign-off? Where is that written down?",
          opts: [
            { q: 3, u: ["plan", "backup"], t: "Run the ransomware playbook: unlink the GPO, isolate servers, seal backups",
              r: "The GPO is unlinked before most servers refresh policy. Two servers ran the task, the rest never got it. Backups are sealed.",
              f: "The GPO is unlinked, but 40 servers had already pulled policy. EDR isolation catches most of them. Most.",
              w: "Stop the distribution mechanism, cut the attacker's admin paths and protect the backups, because they are the attacker's next target." },
            { q: 2, t: "Block all internet traffic at the firewall to cut the attacker off completely",
              r: "C2 and exfiltration stop. The GPO doesn't need the internet and keeps rolling out internally.",
              w: "Cutting egress helps with C2 and exfiltration, but ransomware pushed by GPO runs fine on the internal network." },
            { q: 1, fx: { impact: 4 }, t: "Order every server in the estate shut down immediately to stop the encryption",
              r: "Hard power-offs across the estate. Encryption stops, a SQL cluster corrupts and no memory evidence survives.",
              w: "A last resort that is sometimes justified. Targeted isolation and breaking the distribution mechanism usually achieve the same with less damage." },
            { q: 0, esc: true, t: "Get {ceo}'s approval before taking servers offline, it's a business decision",
              r: "{ceo} is at a school play with their phone on silent. The approval arrives an hour later. So does the ransom note.",
              w: "Pre-authorise containment actions in the IR plan so the lead can act on a Friday night without waiting for sign-off." } ] },

        { id: "hd5", ph: "erad", kc: "install", att: ["T1136", "T1053.005", "T1098"],
          obs: "The attacker created a new AD account, scheduled tasks and extra MFA methods to keep their access.",
          title: "Pulling out the roots",
          text: "Encryption is stopped. So far you have: two compromised accounts, the helpdesk_tmp account they created, AnyDesk on three hosts, a scheduled task on two servers and an extra MFA method on a second admin. How do you eradicate?",
          disc: "How long would a krbtgt double reset take in your environment, and who knows how to do it safely?",
          opts: [
            { q: 3, u: ["edr"], t: "Remove all persistence in one window, reset krbtgt twice, rotate credentials",
              r: "Coordinated removal in the small hours. The attacker's scripted re-entry attempt 14 minutes later bounces off every door.",
              f: "The krbtgt resets go fine. The service account rotation breaks the payroll interface, which nobody documented. Fixed by morning, with some shouting.",
              w: "Remove everything at once so the attacker can't react. Identity persistence (accounts, MFA methods, Kerberos tickets) matters as much as files on disk." },
            { q: 2, t: "Remove each persistence item the moment you find it so they have less access",
              r: "Whack-a-mole. The attacker notices the first removal and adds two new scheduled tasks.",
              w: "Piecemeal removal tips off an active attacker. Collect, plan, then remove in one go." },
            { q: 1, t: "Reimage every machine EDR flagged, which removes anything left behind on disk",
              r: "Clean machines, same compromised accounts. helpdesk_tmp is still enabled.",
              w: "Reimaging deals with hosts, not identity. Created accounts, extra MFA methods and forged tickets survive it." },
            { q: 0, t: "Reset {fd}'s password again and reopen the VPN so the business can work",
              r: "Cheerful optimism. svc-vcenter's old password still works because nobody rotated it.",
              w: "Eradication means every persistence mechanism and every exposed credential, not just the first account." } ] },

        { id: "hd6", ph: "recover", kc: "actions", at: 12.3, att: ["T1486"],
          obs: "Several servers and VMs were locked by ransomware before containment completed.",
          title: "Getting the lights back on",
          text: "Saturday morning. Two file servers and 14 VMs are encrypted. The business wants to open on Monday. How do you recover?",
          disc: "When did you last run a full, timed restore of a critical system end to end?",
          opts: [
            { q: 3, u: ["backup"], t: "Restore clean, pre-intrusion backups into an isolated network, then reconnect",
              r: "Restores come back clean from a Thursday snapshot. Critical systems are live by Sunday night.",
              f: "The restores work, but the backup catalogue lived on an encrypted VM. Rebuilding it costs nine hours.",
              w: "Restore into a clean environment, validate before reconnecting, and pick restore points from before the attacker's first access." },
            { q: 2, t: "Restore the most recent backups straight into production to minimise data loss",
              r: "Fast. You also restore a scheduled task from Friday evening. It tries to phone home.",
              w: "The latest backup may include attacker persistence. Check restore points against the intrusion timeline." },
            { q: 1, t: "Rebuild every affected system from scratch so nothing can possibly come back",
              r: "Very clean. Also three weeks of downtime for finance.",
              w: "Safe but disproportionately slow when you have validated immutable backups. Rebuild when backups can't be trusted." },
            { q: 0, fx: { trust: -6 }, t: "Pay for the decryptor, it's faster than restoring and the insurer may cover it",
              r: "The decryptor arrives. It's slow, crashes on large files, and nothing stops them publishing the stolen data anyway.",
              w: "Payment funds crime, carries sanctions and legal risk, decryptors are often buggy and data theft extortion continues regardless." } ] },

        { id: "hd7", ph: "recover", kc: "actions", at: 61.3,
          title: "Monday morning",
          text: "Monday, 07:00. Systems are coming back. The service desk still resets MFA for anyone who sounds convincing. What goes live with the recovery?",
          opts: [
            { q: 3, t: "Reopen with 30 days of extra monitoring and callback checks for every reset",
              r: "Two more 'urgent' reset calls come in that week. Both fail the callback. Both are logged as attempts.",
              w: "Attackers often come back. Close the entry point before you reopen and watch closely during recovery." },
            { q: 2, t: "Bring everything back now and review the help desk process next quarter",
              r: "Everything's back. On Thursday someone rings the service desk sounding exactly like {admin}.",
              w: "Reopening without fixing the initial access vector invites a repeat." },
            { q: 1, fx: { impact: 6 }, t: "Stay offline until the forensic report is in and you know the full picture",
              r: "Very secure. Revenue is also very secure, at zero.",
              w: "Recovery is a business risk decision. Restore with compensating controls rather than waiting for perfect information." },
            { q: 0, t: "Discipline the service desk agent so the business can see there are consequences",
              r: "The agent resigns. The process that failed them is unchanged and the replacement is trained on the same script.",
              w: "The agent followed a weak process. Fix the process; blaming individuals stops people reporting mistakes." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1486", "T1490"],
        obs: "Ransomware detonated across the ESXi hosts, locking every VM datastore.",
        title: "Detonation",
        text: "The monitoring dashboard turns red row by row. VMs are dropping off. On the ESXi datastores every .vmdk now ends in .locked, and a ransom note claims 380 GB was stolen first.",
        opts: [
            { q: 3, u: ["retainer", "plan"], t: "Isolate ESXi management, preserve evidence, call the retainer and legal",
              r: "The spread stops at 60% of the cluster. The retainer's team is on the bridge within the hour.",
              w: "When detonation happens: stop the spread, preserve evidence, escalate to specialists and executives at once." },
            { q: 2, t: "Shut down all the ESXi hosts right now to stop the encryption spreading",
              r: "The spread stops, and two VMs corrupt mid-write. Still, it stopped.",
              w: "Blunt but defensible with live encryption. Isolating the management interfaces is gentler." },
            { q: 0, t: "Contact the attacker and ask them to pause the encryption while you talk",
              r: "They reply with a smiley face and a bigger number.",
              w: "Attackers don't pause encryption on request. Contain first; any negotiation is for specialists, later." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board gives you budget and attention for one headline improvement. What do you push?",
        opts: [
            { q: 3, t: "Fix service desk verification, FIDO2 for admins and finance, purge stored passwords",
              w: "It breaks the chain at the start: the phone call, the MFA reset and the credential spreadsheet all had to happen for this attack to work." },
            { q: 2, t: "Deploy a second EDR product alongside the first for defence in depth",
              w: "Detection helped, but the attacker walked in the front door with valid credentials. More tooling doesn't fix the process gap." },
            { q: 1, t: "Roll out mandatory phishing and social engineering awareness training for every member of staff",
              w: "Nobody clicked anything. The service desk was socially engineered by phone. Training has to be role-specific." },
            { q: 0, t: "Ban personal phones from the office to reduce the social engineering risk",
              w: "Unrelated to the attack path and guaranteed to be ignored." } ] }
});

/* ---------- 2. Edge of chaos ---------- */
SCEN.push({
    id: "edge", name: "Edge of Chaos",
    blurb: "An emergency advisory drops for your VPN appliance. It's been exploited in the wild for nine days.",
    tags: ["edge", "pii", "ransomware"], start: [1, 8, 15],
    actor: "A state-linked espionage group mass-exploiting an edge device zero-day, who later sold some of the access to a ransomware affiliate. Edge devices have been the leading initial access vector in recent years.",
    sum: "found that its internet-facing VPN appliances had been compromised through a zero-day, leading to credential theft, lateral movement and data exfiltration",
    escSum: "the access was sold on and a ransomware affiliate's beacons appeared inside the network.",
    pre: [
        { kc: "recon", att: "T1595.002", txt: "Internet-wide scanning fingerprinted every exposed {vendor} appliance, including two belonging to {org}." },
        { kc: "weapon", att: "T1588.005", txt: "Developed or bought an unauthenticated remote code execution exploit for the {vendor} SSL VPN." }
    ],
    intro: "Tuesday, 08:15. Overnight the national CSIRT and {vendor}'s PSIRT published an emergency advisory: an unauthenticated remote code execution flaw in the {vendor} SSL VPN, exploited in the wild for at least nine days. It's on the Known Exploited Vulnerabilities list. {org} runs two of these appliances. The patch landed two hours ago.",
    nodes: [
        { id: "eg1", ph: "ident", kc: "exploit", att: ["T1190"],
          obs: "The attacker abused an unauthenticated code execution flaw in the VPN appliance that sits on the internet.",
          title: "Advisory morning",
          text: "Both appliances are on an affected version. What's your first move?",
          disc: "How quickly could you list every internet-facing device you own, with its current version?",
          opts: [
            { q: 3, u: ["logs"], t: "Check for compromise first: run the integrity tool and capture evidence, then patch",
              r: "The integrity checker flags an unexpected file in the web root. The evidence is safe before anything changes.",
              f: "The checker needs a newer build, which needs a support portal login, which belongs to someone who left in March. You have it by 11:00.",
              w: "Patching can overwrite the evidence you need. For an exploited-in-the-wild edge flaw, check for compromise first, then patch fast." },
            { q: 2, set: "missed", t: "Patch both appliances immediately, closing the hole is the only priority right now",
              r: "Patched by 09:00. The implant the attacker planted last week survives the upgrade just fine.",
              w: "Patching closes the door but doesn't evict anyone already inside. Edge implants have survived patches and even factory resets before." },
            { q: 1, set: "missed", t: "Schedule the patch for Sunday's change window so remote staff aren't disrupted mid-week",
              r: "Five more days of exposure to a flaw with public exploit code.",
              w: "Known exploited vulnerabilities on internet-facing kit need an emergency change, not the normal cycle." },
            { q: 0, set: "missed", fx: { trust: -4 }, t: "Reassure customers publicly that {org} is not affected by the vulnerability",
              r: "72 likes. One is from a threat intel analyst who has {org}'s IP on a list of compromised appliances.",
              w: "Never claim you're unaffected before you've checked. It ages badly and publicly." } ] },

        { id: "eg2x", ph: "ident", kc: "install", if: "missed", enter: { impact: 8, heat: 1, trust: -5 }, at: 50, att: ["T1505.003"],
          obs: "The attacker planted a script on the appliance that runs commands sent to it over HTTP.",
          title: "The call you didn't want",
          text: "Thursday. The national CSIRT calls: {org}'s appliance IP is on a list of devices still talking to attacker infrastructure. Your patched appliance has a file in its web root that shouldn't exist.",
          opts: [
            { q: 3, u: ["logs", "edr"], t: "Treat it as confirmed: image the box, list its users, hunt internally",
              r: "You find harvested LDAP credentials and RDP from the VPN pool to two servers. Late, but now you know.",
              w: "A web shell means the appliance and everything that passed through it is suspect. Patching didn't remove it." },
            { q: 2, t: "Delete the web shell and reboot, the appliance is already on the patched version",
              r: "Tidy. Also gone: the evidence of what they did with it.",
              w: "Removing the implant before scoping destroys evidence and misses what was already taken." },
            { q: 0, t: "Tell the CSIRT it's a false positive, you applied the patch on Tuesday",
              r: "The CSIRT sends you the packet capture. It isn't.",
              w: "A patch doesn't prove a clean device. Investigate the report." } ] },

        { id: "eg2", ph: "ident", kc: "install", unless: "missed", att: ["T1505.003"],
          obs: "The attacker planted a script on the appliance that runs commands sent to it over HTTP.",
          title: "Something in the web root",
          text: "The checker found /webui/assets/css/lang.php, which shouldn't exist. Appliance logs show admin session tokens used from an unknown IP at around 03:00 on three nights. How do you treat this?",
          art: "2026-09-03 03:12:44 httpd  GET /webui/assets/css/lang.php?c=aWQ= 200\n2026-09-03 03:12:51 admin  session reuse  token=...a91f  src=192.0.2.77\n2026-09-05 03:10:02 ldap   bind OK  dn=svc-vpnldap",
          disc: "Do your edge devices send logs off the box? If an attacker wiped the appliance, what would you still have?",
          opts: [
            { q: 3, u: ["logs", "edr"], t: "Treat it as confirmed: image the appliance and hunt from the VPN pool",
              r: "You find it: the LDAP bind account's credentials were readable on the box, and there's RDP from the VPN pool to two servers.",
              f: "Imaging the appliance takes four hours because it has to go through the vendor's serial console tool, which needs Java 6.",
              w: "A web shell means the appliance and everything that passed through it is suspect: credentials, sessions and the network behind it." },
            { q: 2, t: "Delete the web shell and apply the patch so the appliance is clean and current",
              r: "Tidy. Also gone: the evidence of what the attacker did with it.",
              w: "Removing the implant before scoping destroys evidence and misses what was already harvested." },
            { q: 1, t: "Factory reset the appliance and restore last week's known-good config backup",
              r: "The config backup includes a local admin account called 'support2' that nobody created.",
              w: "Backups taken during the compromise window can carry attacker changes. Rebuild clean and review config before restoring." },
            { q: 0, t: "Assume it's a legitimate vendor file and move on to patching the appliances",
              r: "It isn't. The vendor confirms this at 17:00, very politely.",
              w: "Unexpected files in the web root of an exploited appliance are never benign until proven so." } ] },

        { id: "eg3", ph: "contain", kc: "actions", att: ["T1021.001", "T1078"],
          obs: "Using harvested credentials, the attacker moved laterally over RDP from the VPN address pool.",
          title: "Credentials in the wild",
          text: "svc-vpnldap's password was stored reversibly on the appliance. Using it, and two user accounts that had logged in through the VPN, the attacker RDP'd from the VPN pool to APP-07 and FS-HR-01. What do you contain?",
          opts: [
            { q: 3, u: ["edr", "idp"], t: "Restrict the appliances, rotate every VPN user's credentials, isolate both servers",
              r: "Door shut, keys changed, the rooms they reached are locked. Remote staff grumble about the temporary setup but can work.",
              f: "The temporary access needs a firewall rule, and the firewall change needs {admin}'s hardware token. It's in {admin}'s car. At the airport.",
              w: "Contain the entry point, the harvested credentials and the hosts they reached, all together." },
            { q: 2, t: "Rotate the svc-vpnldap password, it's the account the attacker harvested",
              r: "The LDAP account is fixed. The two harvested user accounts are not.",
              w: "Every credential that passed through a compromised appliance must be treated as exposed." },
            { q: 1, t: "Block the attacker's IP address at the perimeter firewall and watch closely for any more",
              r: "Blocked. The next connection comes from a different IP, then another.",
              w: "These campaigns use large relay networks of compromised routers. IP blocking alone is whack-a-mole." },
            { q: 0, t: "Keep the VPN up for now, sales need it at the Lisbon conference this week",
              r: "Sales enjoy Lisbon. The attacker enjoys continued access.",
              w: "Business pressure is real, but offer an alternative access path rather than leaving a compromised appliance live." } ] },

        { id: "eg4", ph: "contain", kc: "actions", att: ["T1567.002"],
          obs: "The attacker uploaded HR data from a file server to a consumer file-sharing site.",
          title: "40 GB out the door",
          text: "Proxy logs show FS-HR-01 uploaded 40 GB to a consumer cloud storage provider at 03:20 last Thursday. FS-HR-01 holds payroll, sick leave records and passport scans.",
          disc: "Who decides whether an incident is notifiable, and are they in your IR call tree?",
          opts: [
            { q: 3, u: ["logs"], t: "Block it, size the exfiltration from the logs and bring in legal and the DPO",
              r: "Legal and the DPO are briefed within the hour. The exfiltration is sized and categorised with evidence behind it.",
              f: "Proxy logs roll over after seven days. You grab them with two days to spare, after hunting down the only person with export rights.",
              w: "Data theft turns an IT incident into a legal one. Size it with evidence and start the regulatory assessment immediately." },
            { q: 2, t: "Block the destination and keep investigating until you have the full picture",
              r: "Egress blocked. The notification clock keeps ticking without anyone who can make the call.",
              w: "Technically right, but the regulatory clock starts at awareness, not at the end of the investigation." },
            { q: 1, t: "Ask the cloud provider to delete the uploaded data before anyone can use it",
              r: "They may remove it, eventually. The attacker already has a copy elsewhere.",
              w: "Takedown requests are worth making, but they don't undo a breach or remove notification duties." },
            { q: 0, t: "Put it down to the offsite backup job and keep focusing on the appliance",
              r: "The backup job runs at 01:00 and goes somewhere else entirely. You find this out on Friday.",
              w: "Unusually large uploads to consumer cloud storage need to be proven benign." } ] },

        { id: "eg5", ph: "erad", kc: "install",
          title: "Rebuilding the edge",
          text: "Scoping is done. What's the eradication plan for the appliances?",
          opts: [
            { q: 3, t: "Rebuild both from clean firmware with new secrets and management off the internet",
              r: "Clean rebuild overnight. The management interface now only listens on the admin VLAN.",
              f: "The rebuild goes fine, but the new certificate has the wrong hostname and 600 VPN clients complain at once.",
              w: "Assume the device's firmware, config and secrets are tainted. Rebuild, rotate everything, and stop exposing management to the internet." },
            { q: 2, t: "Patch in place, reboot, and run the integrity checker again to confirm it's clean",
              r: "The checker is happy. Checkers only look for what they know about.",
              w: "Integrity tools help, but advanced implants have survived patching on edge devices. A clean rebuild is the safer bar." },
            { q: 1, t: "Put last week's config backup onto a freshly patched appliance to save time",
              r: "Welcome back, 'support2'.",
              w: "Config captured during the compromise window may include attacker-added accounts or settings." },
            { q: 0, t: "Rip out {vendor} tonight and replace it with a different vendor's appliance",
              r: "At 04:00 you learn the new firewall's licence file was emailed to someone on holiday.",
              w: "Changing vendor is a strategic decision, not an overnight incident action. Rebuild clean now, plan the migration later." } ] },

        { id: "eg6", ph: "recover", kc: "actions",
          title: "Reopening remote access",
          text: "Appliances rebuilt. 1,200 staff need remote access back. How do you bring it up?",
          opts: [
            { q: 3, u: ["logs"], t: "Phase it: admins first on strong MFA, logs forwarded off-box, alerts on new sessions",
              r: "Phased return complete. Two days later an alert fires on a login from a known relay network and it's blocked in four minutes.",
              w: "Recover in stages, with better visibility than before. Off-box logging matters because the attacker can wipe the box." },
            { q: 2, t: "Switch everything back on at once, the appliances are rebuilt and patched now",
              r: "Everyone's back. If anything happens on the appliance you'll find out the same way as last time: from an advisory.",
              w: "Recovery without better monitoring recreates the conditions of the breach." },
            { q: 1, t: "Keep remote access switched off for a month until you're confident it's safe",
              r: "Staff start emailing files to personal Gmail so they can work from home. Shadow IT blooms.",
              w: "Unworkable restrictions push people to unsafe workarounds." },
            { q: 0, t: "Re-enable the old LDAP bind account, the new one broke the office printers",
              r: "The printers work. So does the attacker's copy of the old password.",
              w: "Never reinstate a compromised credential. Fix the dependency." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "c2", enter: { impact: 15 }, att: ["T1071.001", "T1105"],
        obs: "A second group bought the access and deployed C2 beacons talking over HTTPS ahead of ransomware.",
        title: "New tenants",
        text: "EDR flags a beacon on APP-07 checking in with a CDN-fronted domain every 60 seconds. Intel says the initial access has been sold to a ransomware affiliate.",
        opts: [
            { q: 3, u: ["edr", "retainer"], t: "Isolate APP-07 and its contacts, block the C2, sweep the estate for the beacon",
              r: "Three more beacons found and isolated. The affiliate loses their purchase.",
              w: "Access brokers sell footholds. Hunt estate-wide for the new tooling, not just the one host." },
            { q: 2, t: "Isolate APP-07 straight away so the beacon loses its connection",
              r: "One down. Two more sleeping beacons wake up that night.",
              w: "Where there's one beacon there are usually more. Sweep for the behaviour." },
            { q: 0, t: "Reboot APP-07 to clear the beacon out of memory and get it back in service",
              r: "It comes back with the beacon, courtesy of a scheduled task.",
              w: "Rebooting isn't eradication, and it destroys memory evidence." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "Budget time. What's the headline improvement?",
        opts: [
            { q: 3, t: "An edge programme: inventory, KEV tracking, 48-hour patching, off-box logs",
              w: "You can't patch what you don't know about, and you can't investigate a device that only logs to itself." },
            { q: 2, t: "Subscribe to a premium threat intelligence feed so you hear about zero-days sooner",
              w: "The advisory was public and free. The gap was acting on it quickly." },
            { q: 1, t: "Commission an annual external penetration test of all your internet-facing systems",
              w: "A yearly test wouldn't catch a zero-day in its first week. Continuous asset and vulnerability management shortens exposure." },
            { q: 0, t: "Move everything to the cloud so there are no appliances left to exploit",
              w: "Cloud has its own edge. The lesson is process, not location." } ] }
});

/* ---------- 3. Token theft ---------- */
SCEN.push({
    id: "bec", name: "Token Theft",
    blurb: "A supplier asks why their invoices went to a new bank account. Nobody asked for one.",
    tags: ["identity", "email", "pii"], start: [2, 10, 5],
    actor: "A phishing-as-a-service customer using an adversary-in-the-middle kit, specialising in business email compromise and invoice fraud.",
    sum: "lost supplier payments to invoice fraud after an adversary-in-the-middle phishing attack stole a finance user's session",
    escSum: "a 480,000 EUR fraudulent invoice was sent to a major customer from a lookalike domain.",
    pre: [
        { kc: "recon", att: "T1589", txt: "Harvested accounts payable contacts and live invoice threads from a supplier's compromised mailbox." },
        { kc: "weapon", att: "T1608.005", txt: "Stood up an adversary-in-the-middle phishing page behind a CAPTCHA, on a 30-day-old domain to get past filters." }
    ],
    intro: "Wednesday, 10:05. {fd}'s assistant calls. {supplier}, a long-standing supplier, wants to know why its last two invoices, 212,000 EUR in total, were paid to 'the new bank account'. Nobody at {org} requested a bank change. Or, as it turns out, nobody admits to it.",
    nodes: [
        { id: "bc1", ph: "ident", kc: "actions", att: ["T1657"],
          obs: "The attacker diverted supplier payments by changing bank details from inside a compromised mailbox.",
          title: "Where did the money go?",
          text: "Accounts payable shows the bank change came by email from {supplier}'s usual contact, inside a genuine thread, and was processed by {apclerk}. What now?",
          disc: "Does finance know the bank's fraud line number, and would they call it before or after telling IT?",
          opts: [
            { q: 3, u: ["idp", "logs"], t: "Get finance on the bank's fraud line now while you check the clerk's mailbox",
              r: "The bank flags the receiving account within the hour and one payment is frozen. The mailbox tells a story of its own.",
              f: "The bank's fraud line has a 55-minute queue. One payment is frozen, the other has already moved on.",
              w: "Payment recall is extremely time-sensitive, hours not days. Start it immediately and investigate in parallel." },
            { q: 2, t: "Investigate the mailbox first so you know exactly what happened before calling the bank",
              r: "You have a clear picture by 13:00. By then both payments have moved through three mule accounts.",
              w: "Good investigation, wrong order. Recovery chances fall with every hour." },
            { q: 1, t: "Email {supplier}'s contact on the existing thread to confirm whether they changed banks",
              r: "They reply within minutes confirming everything. The attacker is very responsive.",
              w: "The thread may be compromised on either side. Verify by phone using a number from your own records." },
            { q: 0, set: "closed", t: "Reset {apclerk}'s password and close it as user error, they processed the change",
              r: "Ticket closed. Money gone. The attacker still has a valid session.",
              w: "Payment fraud is an incident, not a password ticket, and a reset alone may not end an attacker's session." } ] },

        { id: "bc1x", ph: "ident", kc: "actions", if: "closed", enter: { impact: 10, heat: 1 }, at: 48, att: ["T1657"],
          obs: "The attacker diverted supplier payments by changing bank details from inside a compromised mailbox.",
          title: "It happened again",
          text: "Two days later a second supplier calls: another payment, 64,000 EUR, went to a 'new' account. The attacker never left. The ticket is reopened with your name on it.",
          opts: [
            { q: 3, u: ["idp", "logs"], t: "Recall both payments now and do a full mailbox, rules and app consent review",
              r: "The second payment is frozen. The mailbox review starts to explain everything.",
              w: "Reopening is fine. Repeating the same shallow fix is not." },
            { q: 1, t: "Reset the password again and enforce a longer, more complex one this time",
              r: "Same result as last time.",
              w: "If a reset didn't work before, the problem isn't the password." } ] },

        { id: "bc2", ph: "ident", kc: "exploit", hours: 0.5, noquiz: true, att: ["T1557", "T1539"],
          obs: "An adversary-in-the-middle phishing page proxied the login and stole the session cookie, bypassing push MFA.",
          title: "But we have MFA",
          text: "{apclerk} has push MFA and approved one prompt last Tuesday, right after clicking a 'shared document' link. Since then, sign-ins come from a hosting provider with MFA marked as satisfied by token. What's the most likely explanation?",
          art: "Tue 09:41 SignIn  Success  user={apmail}  ip=203.0.113.14 (usual)       MFA=push approved\nTue 09:42 SignIn  Success  user={apmail}  ip=198.51.100.88 (hosting)   MFA=satisfied by token  ua=axios/1.7\nTue 09:44 InboxRule New 'RSS'  move to 'RSS Subscriptions' if subject contains invoice,bank,payment",
          disc: "Which of your users could have their session stolen this way today? Which MFA methods resist it?",
          opts: [
            { q: 3, t: "An AiTM phishing proxy stole the session cookie after MFA",
              r: "Correct. The phishing page was a transparent proxy to the real login page. MFA happened, for the attacker's benefit.",
              w: "AiTM kits sit between the user and the real login page, so push and code-based MFA get passed through and the resulting session token is stolen." },
            { q: 2, t: "MFA fatigue: the clerk approved a flood of push prompts to make them stop",
              r: "Close, but there was only one prompt and it was the clerk's own login.",
              w: "Fatigue attacks spam prompts. Here the timing and token reuse point to a proxied session." },
            { q: 1, t: "The clerk's password was in an old breach and has been reused across sites",
              r: "Maybe it was, but push MFA would still have stopped a password-only login.",
              w: "Password reuse explains the password, not how MFA was bypassed." },
            { q: 0, t: "Microsoft's authentication service itself must have been compromised",
              r: "Microsoft's security team is unlikely to take your call.",
              w: "Extraordinary claims need evidence. The logs show a classic token replay." } ] },

        { id: "bc3", ph: "contain", kc: "install", att: ["T1564.008", "T1550.004"],
          obs: "The attacker reused a stolen login and quietly filed supplier replies into an obscure folder.",
          title: "Evicting a token",
          text: "Confirmed: token theft, a sneaky inbox filter and a new authenticator registered to {apclerk}. How do you contain it?",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke all tokens, remove the filter and rogue MFA, require compliant devices",
              r: "Every token dies. The attacker's next request gets a 401 and they don't come back.",
              f: "Revocation works, but the conditional access policy you rushed out also blocks {ceo}'s iPad. You hear about it.",
              w: "Token theft needs token revocation. Remove every persistence item: rules, MFA methods and app consents." },
            { q: 2, t: "Reset the password to a long random one, which locks the attacker out of the account",
              r: "Reset done. The attacker's session keeps working for a while, because the token was already issued.",
              w: "A password reset doesn't necessarily kill existing sessions. Revoke them explicitly." },
            { q: 1, t: "Remove and re-register the user's MFA so the attacker's method stops working",
              r: "For two minutes {apclerk}'s account had no MFA at all. Nothing else changed.",
              w: "Re-registering MFA doesn't invalidate stolen tokens and briefly weakens the account." },
            { q: 0, t: "Delete the original phishing message from the inbox so it can't be clicked again",
              r: "The email is gone. The attacker is not.",
              w: "Deleting the lure doesn't undo the compromise." } ] },

        { id: "bc4", ph: "contain", kc: "actions", att: ["T1534"],
          obs: "The attacker used the hijacked mailbox to send lures to colleagues.",
          title: "It spread",
          text: "Message trace: from {apclerk}'s account the attacker sent 340 emails to colleagues with a 'remittance advice' link and replied in six supplier threads. Eleven people clicked.",
          opts: [
            { q: 3, u: ["logs", "idp"], t: "Purge it, block the link, check every clicker's sign-ins, phone the suppliers",
              r: "Two more victims found and contained. One supplier discovers they were compromised too and thanks you.",
              f: "The search-and-purge job fails silently on 'too many results'. You split it into batches and finish hours later.",
              w: "Treat every clicker as potentially compromised and warn suppliers out of band. Their mailbox could be the next vector." },
            { q: 2, t: "Purge the phishing emails from every mailbox and block the link at the proxy",
              r: "The lure is gone, but two colleagues had already typed their passwords into it.",
              w: "Purging prevents new victims but doesn't find existing ones." },
            { q: 1, t: "Send an all-staff email warning people not to click links in unexpected emails",
              r: "Staff helpfully reply-all asking which links.",
              w: "Generic warnings don't contain anything. Identify and check the people who clicked." },
            { q: 0, t: "Leave it, mail between colleagues is filtered as trusted anyway",
              r: "Internal email from a colleague is precisely why it works.",
              w: "Internal phishing from a compromised account bypasses most user suspicion." } ] },

        { id: "bc5", ph: "erad", kc: "install", att: ["T1528"],
          obs: "The attacker kept a foothold through a third-party app that users had granted mail permissions to.",
          title: "Hidden persistence",
          text: "Two of the clickers, including {fd}, entered credentials. And an app called 'Mail Sync Pro' has Mail.ReadWrite consent from three users. Nobody remembers installing it.",
          disc: "Can your users consent to third-party apps reading their mail today? Who reviews the grants?",
          opts: [
            { q: 3, u: ["idp"], t: "Reset both users, revoke the app tenant-wide, require admin approval for apps",
              r: "The app loses access everywhere. Future consent requests route to IT for approval.",
              w: "OAuth apps survive password resets. Revoke the grants, not just the users, and stop users consenting to unverified apps." },
            { q: 2, t: "Secure {fd}'s account as a priority, the trainee has little worth protecting",
              r: "The trainee's mailbox has access to the shared finance inbox.",
              w: "Attackers don't care about job titles. Every compromised account is a foothold." },
            { q: 1, t: "Remove Mail Sync Pro from {apclerk}'s account, since that's where it all started",
              r: "Two other users still grant it access to their mail.",
              w: "Consent grants are per user. Check and revoke tenant-wide." },
            { q: 0, t: "Leave the app in place, it looks like a legitimate productivity tool someone installed",
              r: "Mail Sync Pro keeps syncing mail. To somewhere.",
              w: "Unknown OAuth apps with mail permissions are a classic persistence mechanism." } ] },

        { id: "bc6", ph: "recover", kc: "actions",
          title: "Getting the money back",
          text: "The technical side is clean. The money is still missing. What does recovery look like?",
          opts: [
            { q: 3, t: "Keep the recall going, report to police and the insurer, add callback checks",
              r: "Police and bank coordinate and 131,000 EUR is recovered from a frozen mule account. Finance adopts the callback rule.",
              w: "Recovery covers the money and the process. Early reporting improves recovery odds and insurance claims." },
            { q: 2, t: "Ask {supplier} to absorb the loss, since it was their email thread that was used",
              r: "Their lawyers disagree. So does the relationship.",
              w: "Liability is a legal question, not a first response. Report, recover, fix the controls." },
            { q: 1, t: "Write the loss off quietly to avoid reputational damage with other suppliers",
              r: "Your insurer later declines a related claim because it was never notified.",
              w: "Unreported fraud loses insurance cover, law enforcement help and the chance to disrupt the mule network." },
            { q: 0, fx: { impact: 8 }, t: "Pay {supplier} again to the new account they just confirmed by email, to keep them happy",
              r: "Congratulations, you've been defrauded twice.",
              w: "Verify bank changes by phone using details you already hold. Never through the channel the change came from." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1114.003", "T1657"],
        obs: "The attacker copied mail to an outside address and used it to time a large fraudulent invoice.",
        title: "Bigger fish",
        text: "A forwarding rule you missed has been copying {fd}'s mail externally. The attacker has just emailed {org}'s largest customer from a lookalike domain with a 480,000 EUR invoice and 'updated' bank details.",
        opts: [
            { q: 3, u: ["idp"], t: "Phone the customer now, remove the forwarding and get the domain blocked",
              r: "The customer puts the payment on hold at 16:58, two minutes before their payment run.",
              w: "Warn the target out of band first, then kill the forwarding and the lookalike domain." },
            { q: 2, t: "Block the lookalike domain at your mail gateway so no more emails get through",
              r: "Your staff are protected. The customer, who was the target, is not.",
              w: "Blocking protects your users, not the external party being defrauded." },
            { q: 0, t: "Email the customer's finance team straight away to warn them about the invoice",
              r: "The attacker, reading the thread, replies first to say your warning is itself a scam.",
              w: "If mail may be compromised, warn by phone on a number you already hold." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline fix. What is it?",
        opts: [
            { q: 3, t: "Phishing-resistant MFA, token protection, admin-only app consent, bank callbacks",
              w: "It covers the technical bypass (token theft), the persistence (OAuth) and the business process that turned access into money." },
            { q: 2, t: "Upgrade to a better email security gateway that catches more phishing links",
              w: "Filters help, but AiTM links often slip through on fresh domains. The real fix is MFA that can't be proxied." },
            { q: 1, t: "Run monthly phishing simulations and publish the results by department",
              w: "Shaming reduces reporting. People who fear blame hide clicks, which lengthens dwell time." },
            { q: 0, t: "Move all supplier payments to cheques so bank details can't be changed by email",
              w: "Your suppliers would like a word." } ] }
});
