/* ---------- 8. Bucket list ---------- */
SCEN.push({
    id: "cloud", name: "Bucket List",
    blurb: "Every file in your main storage bucket has been re-encrypted with a key you don't have.",
    tags: ["cloud", "pii"], start: [5, 7, 50],
    actor: "A cloud-focused extortion crew that scans public code for leaked keys, then uses the victim's own cloud encryption features to lock their data. The technique was first seen in the wild in early 2025.",
    sum: "had its cloud storage encrypted with attacker-held keys and its account abused for crypto mining after an access key leaked in a public code repository",
    escSum: "the attacker deleted backup buckets and older object versions before being cut off.",
    pre: [
        { kc: "recon", att: "T1593.003", txt: "Scanned public GitHub commits for cloud access keys and found one in a contractor's test project." },
        { kc: "exploit", att: "T1580", txt: "Tested the key and mapped which buckets, regions and services it could reach." }
    ],
    intro: "Saturday, 07:50. The on-call engineer wakes you: the customer portal is throwing errors and the cloud billing alarm fired overnight at nine times normal spend. In the main AWS storage bucket every file has been replaced with an encrypted version, and each folder has a new file: HOW_TO_RESTORE.txt.",
    nodes: [
        { id: "cl1", ph: "ident", kc: "actions", att: ["T1486"],
          obs: "Attackers re-encrypted cloud storage objects using server-side encryption with a key only they hold.",
          title: "Locked with your own tools",
          text: "The note says the files were re-encrypted using the cloud provider's own encryption with a customer-supplied key that only the attackers hold, and that a lifecycle rule will delete everything in 7 days. The requests came from an access key belonging to 'ci-deploy-legacy'.",
          art: "CloudTrail  s3:CopyObject  sse-customer-algorithm=AES256  user=ci-deploy-legacy  src=203.0.113.200\nCloudTrail  s3:PutBucketLifecycleConfiguration  bucket=portal-prod-assets  expiration=7d\nCloudTrail  iam:CreateAccessKey  user=ci-deploy-legacy",
          disc: "Do you know which of your cloud access keys are long-lived, and where they're stored?",
          opts: [
            { q: 3, u: ["logs"], t: "Deactivate that key, then pull the full audit trail of everything it did",
              r: "The key is dead at 08:05. The audit trail shows it created a second key and a new IAM user, both now on your list.",
              f: "Audit logging only covered management events in one region. You get most of the picture from storage access logs, but not all of it.",
              w: "Stop the credential, then scope everything it did. Attackers with cloud keys usually create more keys and users within minutes." },
            { q: 2, t: "Remove the lifecycle rule first so nothing gets deleted while you investigate",
              r: "The deletion timer is off. The attacker's key still works and is being used right now.",
              w: "Right instinct on deletion, but the live credential is the bigger threat. Revoke it first, then fix the rule." },
            { q: 1, t: "Try decrypting a file with each key in your key management service in case it's one of yours",
              r: "None work. With customer-supplied keys, the key isn't stored anywhere you can reach.",
              w: "With SSE-C the caller supplies the key and the provider doesn't keep it. Without it, the data can't be decrypted." },
            { q: 0, set: "engaged", t: "Email the address in the note to find out exactly what they're asking for",
              r: "They want 8 BTC, and now they know you're awake.",
              w: "Engage only deliberately, with advice, and after containment." } ] },

        { id: "cl1x", ph: "ident", kc: "actions", if: "engaged", enter: { heat: 1, impact: 8 }, att: ["T1485"],
          obs: "The attacker began deleting data in backup storage after being contacted.",
          title: "They noticed",
          text: "Minutes after your email, the attacker's key starts deleting objects in a backup bucket. A reply arrives: 'Every hour you waste costs you a bucket.'",
          opts: [
            { q: 3, u: ["idp"], t: "Deactivate the key and kill every session now, deal with the note later",
              r: "Deletions stop after the first bucket. The rest survive.",
              w: "When destruction starts, stop the identity first. Everything else can wait." },
            { q: 1, t: "Reply asking them to stop deleting while you arrange the payment",
              r: "They keep deleting while they reply.",
              w: "You can't negotiate an attacker out of an account they still control." } ] },

        { id: "cl2", ph: "ident", kc: "install", att: ["T1098.001"],
          obs: "The attacker minted extra access keys and a new admin user to keep a way back in.",
          title: "Where did the key come from?",
          text: "ci-deploy-legacy was created in 2021 for a pipeline that was retired. Its key was committed to a contractor's public GitHub test project last month. The attacker has since created a new IAM user, 'aws-support-sync', with administrator access.",
          opts: [
            { q: 3, u: ["idp"], t: "Delete the rogue user and its keys, revoke sessions and hunt for other new identities",
              r: "aws-support-sync and a second backdoor role are removed. Every active session is invalidated.",
              f: "You remove the user but miss a role with a trust policy that lets an outside account assume it. Found on Sunday.",
              w: "Cloud persistence hides in users, keys, roles and trust policies. Hunt all of them, then invalidate sessions." },
            { q: 2, t: "Delete ci-deploy-legacy and aws-support-sync, the two identities you currently know about",
              r: "Both gone. A role trusting an external account is still there.",
              w: "Attackers with admin create more than one way back. Audit every new identity and trust relationship." },
            { q: 1, t: "Ask the contractor to delete the GitHub project so the key is no longer public",
              r: "They delete it on Monday. The key was scraped within minutes of being pushed last month.",
              w: "Leaked keys are harvested automatically and fast. Rotation is the fix, not deletion." },
            { q: 0, t: "Rename the rogue user to something obvious so it's easy to keep an eye on",
              r: "The attacker is now logged in as 'DO_NOT_USE_ATTACKER'. Still admin.",
              w: "Never leave attacker-created identities in place." } ] },

        { id: "cl3", ph: "contain", kc: "actions", att: ["T1496.001"],
          obs: "The attacker launched GPU instances in unused regions to mine cryptocurrency on the victim's bill.",
          title: "The bill",
          text: "The billing spike is 180 GPU instances in regions {org} has never used, mining cryptocurrency at roughly 2,000 EUR an hour.",
          opts: [
            { q: 3, t: "Terminate them, snapshot one for evidence and lock unused regions org-wide",
              r: "Instances gone by 09:30. The region lock blocks a second batch launched from a key you hadn't found.",
              w: "Kill the spend, keep evidence, and block the regions you don't use so the attacker can't simply relaunch." },
            { q: 2, t: "Terminate every instance in the unfamiliar regions straight away",
              r: "Spend stops. At 11:00 another batch starts in a different region.",
              w: "Terminating stops this batch. An organisation-wide region policy stops the next one." },
            { q: 1, t: "Leave them running for now, billing can be disputed later and the ransom matters more",
              r: "By Monday the bill is 96,000 EUR and the provider's goodwill credit has limits.",
              w: "Costs are real impact, and stopping them takes minutes." },
            { q: 0, t: "Open a support ticket and let the cloud provider take care of the instances",
              r: "Support replies in 11 hours with a link to the shared responsibility model.",
              w: "The account is yours. Act first, then involve the provider." } ] },

        { id: "cl4", ph: "contain", kc: "actions", att: ["T1485"],
          obs: "The attacker set lifecycle rules to delete stored objects and went after backups.",
          title: "What can you get back?",
          text: "The encrypted objects can't be decrypted without the attacker's key. Versioning was on for some buckets, and there's a backup vault in a separate account, if the attacker didn't find it.",
          opts: [
            { q: 3, u: ["backup"], t: "Remove the lifecycle rules, then protect versioned copies and the backup account",
              r: "Versioning holds pre-encryption copies for most buckets, and the isolated backup account wasn't touched.",
              f: "Versioning was off on the biggest bucket. The separate backup account covers it, but it's 26 hours old.",
              w: "Previous object versions and isolated backup accounts are how you recover from this. Protect them before the attacker thinks of it." },
            { q: 2, t: "Remove the lifecycle rules first so nothing else gets deleted while you work out the rest",
              r: "Deletion stops. Nobody checks versioning until Monday, by which time an old cleanup job has purged older versions.",
              w: "Stopping deletion is step one. Find and protect your recovery points straight away." },
            { q: 1, t: "Ask the provider's support team to restore the original unencrypted data",
              r: "They can't. They never had the key, and they explain this very politely.",
              w: "Know how your cloud's encryption works before you need it. The provider can't reverse customer-supplied keys." },
            { q: 0, t: "Pay the ransom, 8 BTC is less than the cost of rebuilding the data",
              r: "They send a key. It works on half the objects. The rest 'must have been corrupted'.",
              w: "Check your recovery options first. Paying funds the next attack and guarantees nothing." } ] },

        { id: "cl5", ph: "erad", kc: "install", att: ["T1562.008"],
          obs: "The attacker switched off audit logging in some regions to hide their tracks.",
          title: "Hunting in the account",
          text: "The attacker had admin for nine days. You find audit logging was switched off in two regions on day three. What's the eradication plan?",
          opts: [
            { q: 3, u: ["logs"], t: "Enforce org-wide logging, review every policy line by line, rotate all long-lived keys",
              r: "Two more problems found: a public bucket policy and a serverless function with a hardcoded outbound call. Both removed.",
              w: "Nine days of admin means anything could have changed. Restore visibility first, then audit the configuration itself." },
            { q: 2, t: "Re-enable logging in the two regions and review the last week of activity",
              r: "Better visibility, but the week with no logs hides a serverless backdoor.",
              w: "Turning logs back on doesn't recover what happened while they were off. Audit the configuration directly." },
            { q: 1, t: "Rotate the access keys of every human user, since the whole breach started with a stolen key",
              r: "Humans rotated. Machine keys, roles and resource policies untouched.",
              w: "Cloud identities include machines, roles and trust policies, not just people." },
            { q: 0, t: "Close it out now the rogue user and the mining instances are gone",
              r: "The serverless backdoor fires on Tuesday.",
              w: "Days of admin access means a full audit, not just removing what you saw." } ] },

        { id: "cl6", ph: "recover", kc: "actions",
          title: "Back in business",
          text: "Data is restored from versions and backups. The portal can come back. On what terms?",
          opts: [
            { q: 3, t: "No long-lived keys, SSE-C blocked by policy, alerts on billing and API anomalies",
              r: "The portal is live on Sunday. The new policy denies customer-key encryption unless explicitly approved.",
              w: "Close the specific technique, the root cause (long-lived keys) and the detection gap (no alerts)." },
            { q: 2, t: "Bring the portal back exactly as it was, now that the attacker has been removed",
              r: "Same architecture, same key model, same exposure.",
              w: "Recovery should leave you stronger than before the breach." },
            { q: 1, t: "Keep the portal down until a full cloud security review has been completed",
              r: "Customers can't log in for three weeks. Some don't come back.",
              w: "Recover with compensating controls while the wider review runs." },
            { q: 0, t: "Reuse a long-lived key for the new pipeline to save on setup time",
              r: "Another long-lived key in another pipeline, waiting for another commit.",
              w: "Short-lived, federated credentials remove this class of problem." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1485"],
        obs: "The attacker deleted backup buckets and older object versions.",
        title: "Scorched earth",
        text: "Spotting your containment, the attacker uses a role you hadn't found to delete older object versions and two backup buckets in the main account.",
        opts: [
            { q: 3, u: ["backup"], t: "Apply an org-level deny on the account, then restore from the isolated backup account",
              r: "One organisation-wide deny policy stops everything at once. The isolated backup account has what you need.",
              w: "When an attacker is destroying data, an organisation-level deny is the emergency brake." },
            { q: 2, t: "Hunt down the specific role they're using and delete it, leaving everything else running",
              r: "Found and deleted after 40 minutes. Another 1,200 object versions are gone by then.",
              w: "Precise but slow while destruction is under way. Broad deny first, refine later." },
            { q: 0, t: "Turn on versioning everywhere so any further deletions can be recovered",
              r: "Versioning doesn't help when an admin is deleting the versions.",
              w: "An admin can delete versions too. Stop the identity." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline fix. What is it?",
        opts: [
            { q: 3, t: "Short-lived credentials, secret scanning, SSE-C blocked, isolated backups",
              w: "It removes the leaked-key root cause and the specific encryption trick, and guarantees a recovery point." },
            { q: 2, t: "Buy a cloud security posture management tool to watch the whole account for problems",
              w: "Posture tools would have flagged some of this, but they don't stop a leaked key being used." },
            { q: 1, t: "Remove GitHub access from every contractor who works on the platform",
              w: "The problem was a long-lived key, not a contractor. Keys leak from employees too." },
            { q: 0, t: "Move all of the portal's data over to a different cloud provider",
              w: "Every cloud has its equivalent. The lesson is identity, not vendor." } ] }
});

/* ---------- 9. Pressure drop ---------- */
SCEN.push({
    id: "ot", name: "Pressure Drop",
    blurb: "The dosing pump setpoint changes on its own at 06:00, then a flag appears on the control screen.",
    tags: ["ot"], start: [6, 6, 10], orgs: ["Brightwater Utilities", "Kestrel Foods", "Ashgrove Engineering", "Tidewell Pharma"],
    actor: "A pro-Russian hacktivist group that hunts for internet-exposed industrial control panels with default passwords and posts videos of itself changing settings. Low skill, high visibility and potentially dangerous.",
    sum: "had operators lose control of a chemical dosing process after hacktivists logged into an internet-exposed control panel with a default password",
    escSum: "the process was driven into an unsafe state, tripping the line and ruining a batch.",
    pre: [
        { kc: "recon", att: "T1596.005", txt: "Searched internet scan databases for control panels from a popular vendor exposed on the VNC port." },
        { kc: "weapon", txt: "Compiled a list of the vendor's default passwords from public manuals." }
    ],
    intro: "Sunday, 06:10. The night operator at {org}'s plant in {plantsite} rings the on-call manager: the screen on the dosing control panel is moving by itself. The setpoint on a chemical dosing pump just jumped from 12 to 60, then back. Then a message appeared on screen with a group name and a flag. You've been patched in as incident lead.",
    nodes: [
        { id: "ot1", ph: "ident", kc: "actions", att: ["T0836"],
          obs: "The attacker changed a setpoint on the dosing pump through the control panel.",
          title: "Safety first",
          text: "The process is still running. The operator can see the screen but isn't sure it can be trusted. What's your first instruction?",
          disc: "Can your operators run critical processes by hand if the control system can't be trusted? When did they last practise?",
          opts: [
            { q: 3, t: "Move the pump to local manual control and check levels with physical readings",
              r: "The operator switches the pump to local manual and takes a grab sample. Levels are safe.",
              f: "The only operator trained on local manual mode is on holiday. Talking the night operator through it on the phone takes 25 minutes.",
              w: "In OT, safety and the physical process come first. Take control away from the network and verify with physical measurements, not the screen." },
            { q: 2, t: "Unplug the panel's network cable so the attacker can't reach it any more",
              r: "The attacker is cut off. The operator is now blind on that line until someone brings a laptop.",
              w: "Disconnecting is right, but get the process into a safe, locally controlled state first. Losing view can be dangerous too." },
            { q: 1, set: "fought", t: "Have the operator put the setpoint back and keep a close eye on the screen",
              r: "Setpoint restored. The attacker changes it again three minutes later.",
              w: "Fighting the attacker on a compromised panel isn't control. Take it local." },
            { q: 0, fx: { impact: 6 }, t: "Shut down the whole plant immediately until IT has had a chance to investigate",
              r: "An uncontrolled stop leaves tanks half processed and causes a pressure spike. Restarting takes two days.",
              w: "Shutdowns in OT follow the plant's safe shutdown procedure and are led by operations, not IT." } ] },

        { id: "ot1x", ph: "ident", kc: "actions", if: "fought", enter: { heat: 1, impact: 6 }, att: ["T0829"],
          obs: "The attacker changed the panel password, leaving operators unable to see or control the process from the screen.",
          title: "Locked out",
          text: "Now aware someone is watching, the attacker changes the panel's password. The operator can't see or control the process from the screen any more.",
          opts: [
            { q: 3, t: "Switch the pump to local manual control and cut the panel's network connection",
              r: "Control is back in human hands within 10 minutes.",
              w: "When the screen can't be trusted, go local and physical." },
            { q: 1, t: "Ring the panel vendor's support line and ask them for the master reset code for the panel",
              r: "The vendor needs a support contract number nobody can find.",
              w: "Restore control of the process first. The panel can wait." } ] },

        { id: "ot2", ph: "ident", kc: "exploit", att: ["T0883", "T0812"],
          obs: "The attacker reached the control panel from outside and logged in with the vendor's stock password.",
          title: "How did they get in?",
          text: "The panel was installed by an integrator in 2019. It's reachable from the internet over VNC through a port forward on the plant's broadband router, 'for remote support'. The password is the vendor default.",
          art: "router  NAT  wan:5900 -> 192.168.10.20:5900 (HMI-DOSING)\nHMI     VNC session  src=192.0.2.188  auth=OK (vendor default)\nHMI     Setpoint P-101  12.0 -> 60.0",
          opts: [
            { q: 3, u: ["logs"], t: "Remove the port forward, save the router and panel logs, look for other exposures",
              r: "The forward is gone. A second exposed device, the reservoir level panel, turns up on the same router.",
              w: "Close the door, keep the evidence and look for other doors. Integrators often expose more than one thing." },
            { q: 2, t: "Set a strong password on the panel and keep the remote access for the integrator",
              r: "Better password. Still a control panel on the internet over a protocol never built for it.",
              w: "A strong password helps, but OT devices should never be directly exposed to the internet." },
            { q: 1, t: "Ask the integrator who set up the remote access and wait for their answer",
              r: "The integrator's engineer is at a match and replies on Monday.",
              w: "You can remove the exposure yourself now and ask questions afterwards." },
            { q: 0, t: "Block the attacker's IP address on the router and leave the rest as it is",
              r: "They come back from a different IP within the hour.",
              w: "Hacktivists rotate IPs freely. Remove the exposure." } ] },

        { id: "ot3", ph: "contain", kc: "exploit",
          title: "Same integrator, other sites",
          text: "The same integrator built the control systems at {org}'s two other sites. Nobody knows whether they're set up the same way.",
          opts: [
            { q: 3, t: "Check every site's internet exposure today and pull remote access until verified",
              r: "One more site has the same port forward. It's closed before anyone finds it.",
              f: "The second site's router is managed by the integrator and nobody has the login. Closing it takes until evening.",
              w: "The same installer usually leaves the same pattern. Check all sites fast and remove exposure first." },
            { q: 2, t: "Ask each site manager to confirm their control systems aren't on the internet",
              r: "Both say no. One is wrong.",
              w: "People often don't know what's exposed. Check from the outside and on the routers." },
            { q: 1, t: "Wait for Monday so the integrator can audit all the sites properly in person",
              r: "Sunday evening, a second video appears on the group's channel. It's the other site.",
              w: "Hacktivists work weekends. So do exposed devices." },
            { q: 0, t: "Disconnect every site's control network from everything, operator screens included",
              r: "Operators at three plants lose visibility at once. Two lines trip.",
              w: "Blanket disconnection in OT can cause the safety problem you're trying to prevent. Work with operations." } ] },

        { id: "ot4", ph: "contain", kc: "actions",
          title: "Going viral",
          text: "The group has posted a screen recording of your panel on its Telegram channel, showing the setpoint change and naming the plant. A local reporter wants to know if people should be worried.",
          disc: "Who signs off a public safety statement about an OT incident at your organisation, and how fast?",
          opts: [
            { q: 3, u: ["plan"], t: "Agree a short factual statement with operations: what happened, and that it's safe",
              r: "The statement is out by noon. Coverage is calm and mentions the quick switch to manual control.",
              w: "Safety questions need fast, factual answers backed by operations. Silence breeds worst-case speculation." },
            { q: 2, t: "Say nothing until the investigation is complete, to avoid giving the hackers attention",
              r: "The story runs with the video and no comment. Local social media fills the gap.",
              w: "Hacktivists want attention, but safety concerns need an answer. Say what's true, briefly." },
            { q: 1, t: "Describe it as a minor IT glitch that never affected the process",
              r: "The video clearly shows the setpoint change. The 'glitch' line is quoted back at you for weeks.",
              w: "Never contradict what the public can see for themselves." },
            { q: 0, t: "Report the Telegram channel and hold off commenting until the video is taken down",
              r: "The channel has 40,000 subscribers and a bot that reposts everything.",
              w: "Takedowns rarely work and don't answer the safety question." } ] },

        { id: "ot5", ph: "contain", kc: "actions",
          title: "Who needs to know?",
          text: "It's a critical process. Legal lists the sector safety regulator, the national cyber security centre and, because {org} is in scope of NIS2, the national CSIRT.",
          opts: [
            { q: 3, t: "Notify the cyber centre and CSIRT early and brief the safety regulator with operations",
              r: "The cyber centre confirms other plants were hit by the same group this week and shares their indicators.",
              w: "OT incidents often have both safety and cyber regulators. Early notification brings help and meets obligations." },
            { q: 2, t: "Tell the safety regulator, since that's where the real risk is, and skip the cyber reports",
              r: "The safety regulator is satisfied. The CSIRT later asks why it heard about it from Telegram.",
              w: "Both regimes apply. Safety and cyber reporting run in parallel." },
            { q: 1, t: "Hold off reporting until you know whether any product was actually affected",
              r: "The 24-hour NIS2 window passes while you wait for lab results.",
              w: "Early warnings are designed for incomplete information." },
            { q: 0, t: "Keep it internal, reporting it will only bring extra scrutiny on the plant",
              r: "The regulator finds out from the news. The scrutiny arrives anyway, with interest.",
              w: "Hiding an OT incident at a regulated site is a serious compliance failure." } ] },

        { id: "ot6", ph: "erad", kc: "install",
          title: "Is the controller clean?",
          text: "The panel talks to a PLC that runs the dosing logic. The attacker only had panel access, but nobody has checked the PLC program since commissioning.",
          opts: [
            { q: 3, t: "Check PLC and panel logic against known-good backups, then reset every login",
              r: "The PLC logic matches the 2019 backup. The panel had a new user account added, now removed.",
              f: "There's no known-good backup of the PLC program. The integrator rebuilds one from their archive, which takes three days.",
              w: "Verify controller logic against a trusted baseline. Hacktivists usually stop at the panel, but you need to know." },
            { q: 2, t: "Reimage the control panel with a fresh install and new passwords",
              r: "Clean panel, and the odd user account is gone. Nobody checks the PLC.",
              w: "The panel is the visible part. The PLC runs the process and needs verifying too." },
            { q: 1, t: "Download the PLC program and have IT's endpoint security tooling scan it for malware",
              r: "The EDR has no idea what a ladder logic file is.",
              w: "OT verification needs OT tools and engineers, not IT antivirus." },
            { q: 0, t: "Assume the PLC is fine, the process has been running normally ever since",
              r: "It probably is. 'Probably' isn't what the safety case says.",
              w: "Normal running doesn't prove unmodified logic." } ] },

        { id: "ot7", ph: "recover", kc: "actions",
          title: "Back to automatic",
          text: "Operators have run the dosing process by hand for two days. They're tired and want it back on automatic control.",
          opts: [
            { q: 3, t: "Go back to automatic with no internet exposure and a secure path for remote support",
              r: "Automatic control resumes on Tuesday. The integrator now connects through a monitored jump host with MFA.",
              w: "Remote support is a real need. Give it a secure path rather than leaving it to a router port forward." },
            { q: 2, t: "Return to automatic now that the port forward and default password are gone",
              r: "It works. On Friday the integrator, needing access, sets up a new port forward.",
              w: "If you don't provide a secure remote access route, someone will create an insecure one." },
            { q: 1, t: "Keep manual operation for a month while a full OT security review takes place",
              r: "Two operators go off sick with fatigue and a dosing error happens on a manual shift.",
              w: "Manual operation has its own safety risks. Restore automation with safeguards." },
            { q: 0, t: "Give the integrator permanent VPN access on a shared account to make support easier",
              r: "A shared, permanent account with no MFA into your control network.",
              w: "Third-party access into OT must be individual, time-limited and monitored." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T0831", "T0880"],
        obs: "The attacker drove the process into an unsafe state, forcing the safety system to trip.",
        title: "Trip",
        text: "Before the connection was cut, the attacker ran the dosing pump at full rate for four minutes. The safety system tripped the line and a batch is now off specification.",
        opts: [
            { q: 3, u: ["plan"], t: "Operations lead the emergency procedure; quarantine the batch, notify the regulator",
              r: "Operations take charge, the batch is quarantined and the regulator is informed within the hour.",
              w: "Once physical safety is involved, operations and the safety procedures lead. Cyber supports." },
            { q: 2, t: "Restart the line as soon as the safety system resets, to limit the loss of production",
              r: "The line restarts before anyone confirms the batch is contained. It isn't.",
              w: "Never restart until operations confirm the process is safe." },
            { q: 0, t: "Keep the off-spec batch quiet while you work out exactly what happened",
              r: "It's found at the next quality check. The cover-up becomes the story.",
              w: "Safety incidents must be reported, fast." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline fix. What is it?",
        opts: [
            { q: 3, t: "No internet-facing controls, secure remote support, no defaults, tested manual fallback",
              w: "It removes the exposure, the weak credentials and the dependence on the screen: the three links in this chain." },
            { q: 2, t: "Deploy an OT network monitoring tool at every one of the plants",
              w: "Useful visibility, but the attacker walked through an open door that monitoring would only have watched." },
            { q: 1, t: "Merge the OT network into the corporate network so IT security can manage and monitor it all",
              w: "Flattening OT into IT increases exposure. Segment, don't merge." },
            { q: 0, t: "Remove the plant's location and details from the company website",
              w: "Hacktivists find targets with internet scans, not by reading websites." } ] }
});

/* ---------- 10. Blackout Friday ---------- */
SCEN.push({
    id: "ddos", name: "Blackout Friday",
    blurb: "A five-minute outage on the biggest sales day of the year. Then the email: 'That was a demo.'",
    tags: ["ddos", "pii"], start: [4, 10, 30], orgs: ["Northgate Retail Group", "Quayside Hotels"],
    actor: "A ransom DDoS group renting a botnet of hijacked routers and IoT devices, using the flood as cover for a credential stuffing campaign. DDoS attacks of several terabits per second were reported repeatedly through 2025.",
    sum: "was hit by an extortion-driven DDoS during its biggest sales weekend, used as cover for a credential stuffing attack on customer accounts",
    escSum: "a flood of over a terabit per second took the website, payment terminals and head office offline at once.",
    pre: [
        { kc: "weapon", att: "T1583.005", txt: "Rented time on a botnet of compromised routers and IoT devices." },
        { kc: "recon", att: "T1597.002", txt: "Bought a list of leaked email and password pairs from other companies' breaches." }
    ],
    intro: "Friday, 10:30. It's the biggest sales weekend of {org}'s year. At 10:00 the website slowed to a crawl for five minutes, then recovered. At 10:20 an email arrived for {ceo}: 'That was a demo. 2 BTC by 14:00 or your weekend goes dark.' Online sales are already down by a third.",
    nodes: [
        { id: "dd1", ph: "ident", kc: "actions", att: ["T1498"],
          obs: "The attacker hit the site with a huge volume of junk traffic to knock it offline.",
          title: "A demo, and a deadline",
          text: "The five-minute slowdown matches a spike of 40 Gbps of amplified UDP traffic and a flood of requests to the search page. You have three and a half hours until the deadline. What first?",
          art: "10:00:12 edge  ingress 41.2 Gbps  UDP/123, UDP/53 amplification\n10:01:40 waf   /search?q=  180,000 req/s  (normal peak 4,000)\n10:05:03 edge  ingress 1.1 Gbps  (normal)",
          disc: "Does your DDoS protection cover your network edge or only your website? Who phones the provider?",
          opts: [
            { q: 3, u: ["plan"], t: "Call your ISP and DDoS provider now and get mitigation in place before 14:00",
              r: "Scrubbing is on standby by 11:30 and the site is moved behind it by 12:15.",
              f: "DDoS protection was 'on the roadmap'. Emergency onboarding with a provider takes until 13:40, cutting it very fine.",
              w: "Ransom DDoS gives you warning. Use it to get upstream mitigation in place before the main attack." },
            { q: 2, t: "Scale up web servers and bandwidth in the cloud to absorb whatever comes next",
              r: "More servers help with the request flood. They do nothing about 400 Gbps hitting your network edge.",
              w: "You can't out-scale a botnet at the network layer. Volumetric floods need upstream scrubbing." },
            { q: 1, t: "Pay the 2 BTC, it's far less than a weekend of lost sales would cost",
              r: "They take the money. Another group hears you pay and sends its own demand on Sunday.",
              w: "Paying marks you as a payer, guarantees nothing and funds the botnet." },
            { q: 0, set: "ignored", t: "Ignore it, these emails are usually bluffs and the site has recovered",
              r: "At 14:00 the site goes dark.",
              w: "The demo was the proof. Treat a demonstrated capability as real." } ] },

        { id: "dd1x", ph: "contain", kc: "actions", if: "ignored", at: 3.5, enter: { impact: 12, trust: -6 },
          title: "Dark",
          text: "At 14:00 the site goes completely dark. No mitigation is in place, and the ISP says emergency scrubbing takes at least an hour to set up.",
          opts: [
            { q: 3, t: "Start the ISP's emergency scrubbing and a DDoS provider onboarding right now",
              r: "The site is back at 15:40 behind scrubbing. A painful 100 minutes.",
              w: "Late beats never. Get upstream mitigation in place now." },
            { q: 1, t: "Keep restarting the web servers to clear the load as it builds up",
              r: "They come back up and fall over again within seconds.",
              w: "The problem is upstream of your servers." } ] },

        { id: "dd2", ph: "contain", kc: "actions", at: 3.5, att: ["T1499.002"],
          obs: "The attacker sent a flood of expensive web requests to exhaust the application.",
          title: "Full flood",
          text: "The main attack is in full swing: 380 Gbps of amplified traffic plus a million requests a second aimed at search and checkout. The volumetric flood is being scrubbed. The request flood is getting through and the site is timing out.",
          opts: [
            { q: 3, u: ["logs"], t: "Rate limit and bot-challenge search and checkout, and cache what you can",
              r: "Challenges drop bot traffic by 95%. Real customers see a brief check, then the site works.",
              f: "The first rate limit is too aggressive and blocks the payment provider's callbacks for 15 minutes. Tuned and fixed.",
              w: "Application floods look like real users. Rate limits, bot challenges and caching separate the two." },
            { q: 2, t: "Geo-block every country outside Ireland and the UK until the flood stops",
              r: "Traffic drops, and so do your international customers. The botnet has plenty of local devices.",
              w: "Geo-blocking is blunt and botnets are global, including local. Use behavioural controls." },
            { q: 1, t: "Take the site down yourself and show a maintenance page until it's over",
              r: "You've done the attacker's job for them, for free.",
              w: "Self-inflicted downtime is exactly the outcome the attacker wanted." },
            { q: 0, t: "Block the top 100 attacking IP addresses at the firewall",
              r: "There are 200,000 of them.",
              w: "Botnets have far too many IPs for manual blocking." } ] },

        { id: "dd3", ph: "contain", kc: "exploit", att: ["T1110.004"],
          obs: "Under cover of the flood, the attacker tried leaked usernames and passwords against customer accounts.",
          title: "The quiet part",
          text: "While everyone watches the traffic graphs, fraud notices a spike in failed logins, then in successful ones, from residential IPs. Loyalty points are being drained and saved cards used to buy gift cards.",
          art: "14:22 auth   login_failed   18,400/min  (normal 60)\n14:25 auth   login_success  2,100 accounts from 9,800 residential IPs\n14:31 fraud  gift card purchases +4,100% using saved cards",
          opts: [
            { q: 3, u: ["idp"], t: "Reset the hit accounts, bot-protect the login and hold gift card orders",
              r: "2,100 accounts secured, the gift card orders held, and credential stuffing drops sharply behind the bot check.",
              w: "DDoS is often a smokescreen. Protect the accounts, stop the cash-out (gift cards) and make logins expensive for bots." },
            { q: 2, t: "Switch on mandatory MFA for every customer account immediately",
              r: "Right direction, but springing MFA on millions of customers mid-sale locks many of them out.",
              w: "Customer MFA needs a planned rollout. Mid-incident, target the affected accounts and add bot defences." },
            { q: 1, t: "Leave it to the fraud team, security needs to stay focused on the DDoS",
              r: "Fraud handles refunds. Nobody handles the attack.",
              w: "It's the same incident. The smokescreen worked if you split them." },
            { q: 0, t: "Put it down to customers retrying their logins because the site is slow",
              r: "Customers retrying don't buy 300 gift cards each.",
              w: "Look at the pattern, not just the volume." } ] },

        { id: "dd4", ph: "contain", kc: "actions",
          title: "The second demand",
          text: "At 16:00 a new email: '2 BTC now, or 5 BTC tomorrow and we hit your payment provider too.' {ceo} asks whether paying would make it all stop.",
          opts: [
            { q: 3, t: "Advise against paying, report it to police and warn the payment provider now",
              r: "The payment provider adds your traffic to its own protection. Police link the group to three other retailers.",
              w: "Ransom DDoS groups often lack the capacity they claim, and paying invites more. Prepare the next target and report." },
            { q: 2, t: "Buy time by replying to the attackers that you're arranging payment",
              r: "They stop for two hours, then start again, now confident you'll pay.",
              w: "Stalling can buy time, but it's a specialist tactic and signals willingness to pay." },
            { q: 1, t: "Pay the 2 BTC now to protect tomorrow's trading, which matters more",
              r: "Saturday is quiet. On Monday a new demand arrives for 10 BTC.",
              w: "Payers get targeted again." },
            { q: 0, t: "Reply threatening the attackers with legal action if they carry on",
              r: "They answer by hitting the site at 18:00 with twice the traffic.",
              w: "Provoking an attacker with a live botnet doesn't help." } ] },

        { id: "dd5", ph: "erad", kc: "install", att: ["T1098"],
          obs: "The attacker changed the email address on taken-over customer accounts to keep control of them.",
          title: "Nothing to eradicate?",
          text: "The flood is under control. The attacker never got into your network. What does eradication look like here?",
          opts: [
            { q: 3, t: "Purge attacker access to customer accounts and review what they changed in each",
              r: "300 accounts had their email address changed by the attacker. All reverted, all customers contacted.",
              w: "With credential stuffing, eradication means removing the attacker from customer accounts, not servers." },
            { q: 2, t: "Reset the passwords on all 2,100 compromised customer accounts",
              r: "Done. 300 accounts had their email changed, so the reset links go straight to the attacker.",
              w: "Check what changed in taken-over accounts before sending resets." },
            { q: 1, t: "Leave the WAF in its strictest blocking mode permanently, just in case they come back",
              r: "Genuine customers keep hitting challenges for months. Conversion stays down.",
              w: "Emergency settings should be tuned back once the attack is over." },
            { q: 0, t: "Nothing to do, the attackers never actually got into the network",
              r: "They got into 2,100 customer accounts.",
              w: "Account takeover is an intrusion, just not into your servers." } ] },

        { id: "dd6", ph: "recover", kc: "actions",
          title: "After the weekend",
          text: "The attacks stopped on Sunday. Sales were down 18% and customers are complaining about gift card fraud.",
          opts: [
            { q: 3, t: "Refund fast, notify customers and the regulator, keep DDoS protection always on",
              r: "Refunds done within a week. The regulator is notified about the account takeovers within 72 hours.",
              w: "Account takeover exposes personal data. Make customers whole, notify, and keep the protection permanent." },
            { q: 2, t: "Refund the fraud and move on, since there wasn't a data breach as such",
              r: "The regulator disagrees. Attackers accessed personal data in 2,100 accounts.",
              w: "Unauthorised access to customer accounts is typically a personal data breach." },
            { q: 1, t: "Cancel the emergency DDoS protection now the attack is over, it's expensive",
              r: "The same group returns six weeks later for the Christmas peak.",
              w: "DDoS groups come back to victims who drop their guard." },
            { q: 0, t: "Point out in the public statement that customers who reused their passwords were at fault",
              r: "Accurate and disastrous for trust.",
              w: "Credential reuse is a customer problem you're still expected to defend against." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1498"],
        obs: "A far larger wave of junk traffic saturated the link, taking everything that shared it offline.",
        title: "Everything, everywhere",
        text: "The attackers add a second botnet. The flood passes 1.2 Tbps and saturates your ISP link, taking down the website, the card terminals at your locations and head office internet all at once.",
        opts: [
            { q: 3, u: ["plan"], t: "Shift everything behind the provider's scrubbing platform, card terminals to 4G, brief staff",
              r: "Card terminals switch to 4G within 30 minutes. The site is back behind the larger scrubbing network an hour later.",
              w: "Huge floods take out everything sharing the link. Resilient paths keep the business trading." },
            { q: 2, t: "Ask the ISP to blackhole the website's IP address so that everything else can stay online",
              r: "Head office and the card terminals recover. The website is gone for the rest of the day, by design.",
              w: "Blackholing sacrifices the target to save the rest. Sometimes right, but it completes the attacker's goal." },
            { q: 0, t: "Wait it out, floods this size usually only last an hour or two",
              r: "This one lasts nine.",
              w: "Hope is not a mitigation." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline fix. What is it?",
        opts: [
            { q: 3, t: "Always-on DDoS protection at both layers, login bot defences, payment failover",
              w: "It covers the volumetric flood, the application flood, the credential stuffing and the continuity gap." },
            { q: 2, t: "Buy a lot more bandwidth from the ISP so there's headroom for the next flood",
              w: "Botnets can generate more traffic than any single customer's bandwidth." },
            { q: 1, t: "Move the website to a bigger hosting provider with more capacity",
              w: "Bigger hosting helps with some floods, but not credential stuffing or your locations' connectivity." },
            { q: 0, t: "Keep the dates of the next big sale secret so attackers can't plan",
              w: "Your customers need to know when it is too." } ] }
});
