/* ---------- 11. Salted Earth (departing insider) ---------- */
SCEN.push({
    id: "leaver", name: "Salted Earth",
    blurb: "A trusted senior admin is working out their notice. DLP just caught them taking the customer database with them.",
    tags: ["insider", "pii"], start: [2, 9, 30],
    actor: "A long-serving senior administrator with legitimate privileged access, leaving for a competitor, who has decided to take the customer database and their automation with them, and to leave something behind. Insider incidents are among the slowest to detect and the costliest per record.",
    sum: "discovered that a departing senior administrator had exfiltrated the customer database and planted a delayed backdoor before their leaving date",
    escSum: "the planted task fired, disabling endpoint protection and deleting shared drives.",
    pre: [
        { kc: "recon", att: "T1591", txt: "No external reconnaissance was needed: the insider already knew exactly where the crown jewels lived and how they were protected." },
        { kc: "weapon", att: "T1585", txt: "Set up personal file-sharing and email accounts over the preceding weeks to receive the data quietly." }
    ],
    intro: "Wednesday, 09:30. The DLP team escalates an alert. {admin}, a senior infrastructure administrator who handed in their notice ten days ago and leaves on Friday, uploaded a 4 GB archive named 'personal-photos.7z' to a personal file-sharing account at 22:10 last night. The archive name is a lie: the DLP content scan matched thousands of customer records. You are the lead analyst.",
    nodes: [
        { id: "lv1", ph: "ident", kc: "actions", att: ["T1567.002", "T1005"],
          obs: "A privileged administrator copied a large archive of the customer database to a personal file-sharing account online, out of hours.",
          title: "The archive that lied",
          text: "The upload is confirmed. {admin} still has full privileged access and three days left on the payroll. HR and legal don't know yet. What do you do first?",
          art: "22:07 DLP    match  customer_records  count~11400  host=WKS-ADM-04  user={admin}\n22:10 Proxy  POST  filesharehost.example  4.1 GB  'personal-photos.7z'  user={admin}\n22:31 Auth   {admin}  interactive logon  WKS-ADM-04",
          disc: "Who has to be in the room for an insider case: HR, legal, the manager? How fast can you get them, and who is allowed to know?",
          opts: [
            { q: 3, t: "Preserve evidence and loop in HR and legal, quietly",
              r: "A small, need-to-know group forms within the hour. Evidence is preserved and nobody has tipped their hand.",
              f: "Legal is in a client meeting until noon. You get HR and start the evidence hold, but the full group doesn't convene until after lunch.",
              w: "Insider cases are HR and legal cases with a technical thread. Preserve evidence, keep the circle tiny, and act on advice so anything you find holds up later." },
            { q: 2, t: "Start pulling every log on {admin}'s activity yourself before telling anyone",
              r: "You build a good picture. You are also one analyst carrying a legal-weight case with no cover.",
              w: "Scoping matters, but an insider case needs HR and legal from the start, both for authority and to keep evidence admissible." },
            { q: 1, set: "spooked", t: "Message {admin} to ask what the archive was, giving them a chance to explain",
              r: "They reply 'just old holiday snaps, I'll delete it' and go very quiet.",
              w: "Confronting the subject before you are ready destroys the element of surprise and invites them to cover tracks or retaliate." },
            { q: 0, set: "spooked", t: "Disable {admin}'s account immediately to stop any more data leaving",
              r: "Access is cut, and {admin} now knows they are caught with two days of privileged history to hide and a grudge forming.",
              w: "Cutting access on an unproven suspicion, with no evidence hold and no legal steer, tips them off and can breach employment process. Preserve first." } ] },

        { id: "lv1x", ph: "ident", kc: "actions", if: "spooked", enter: { heat: 1 }, att: ["T1070.001", "T1485"],
          obs: "Now aware they are being watched, the insider began deleting their command history and local copies of what they took.",
          title: "They know",
          text: "{admin} is now clearing browser history, deleting local files and asking colleagues 'is something going on with the DLP tool?'. How do you handle it?",
          opts: [
            { q: 3, t: "Snapshot the workstation now, then suspend with HR",
              r: "A forensic image is taken before more is lost, and the suspension is done cleanly with HR present.",
              f: "The image starts, but the workstation's disk is nearly full and it crawls. You get most of it before HR walks in.",
              w: "Once the subject is spooked, capturing volatile evidence beats waiting. Pair it with a lawful, HR-led suspension so the removal itself is clean." },
            { q: 1, t: "Confront {admin} directly and demand they return the data",
              r: "They deny everything and lawyer up. The data is already copied elsewhere anyway.",
              w: "Demands without evidence and without HR just escalate and rarely recover data that is already gone." },
            { q: 0, t: "Do nothing and hope they calm down before Friday",
              r: "They spend Thursday deleting anything that might incriminate them.",
              w: "An alerted insider with live access will act. Waiting only costs you evidence." } ] },

        { id: "lv2", ph: "ident", kc: "actions", att: ["T1052.001", "T1074.001"],
          obs: "For weeks the same account had been staging finance and HR folders onto a removable drive plugged into the workstation.",
          title: "How long, and how much",
          text: "The forensic review of {admin}'s workstation shows this wasn't one night. Files have been staged for weeks, and a removable drive was mounted repeatedly. You need to know the full scope of what left.",
          art: "Registry USBSTOR: 'Samsung PSSD T7'  first seen 6 weeks ago  last 2 days ago\nStaging folder C:\\Temp\\proj\\  finance\\  hr\\  crm-export\\  (deleted, recovered)",
          disc: "Could you tell today which files a specific user copied to a USB drive last month? What telemetry would you need?",
          opts: [
            { q: 3, u: ["logs"], t: "Correlate DLP, endpoint and file-server logs",
              r: "A timeline emerges: the customer CRM export, finance folders and an HR pay file, staged and copied over six weeks.",
              f: "File-server auditing was off on one share 'for performance'. You reconstruct most of it from DLP and endpoint logs, with a gap.",
              w: "Scope an insider by correlating identity, endpoint, DLP and file-access telemetry. USB history and staging folders show intent and volume." },
            { q: 2, t: "Interview {admin}'s teammates about what they saw them working on",
              r: "Useful colour, unreliable detail. Memories differ and some are loyal to {admin}.",
              w: "Human accounts help build context but can't substitute for the log-based record of what actually moved." },
            { q: 1, t: "Assume only the 4 GB archive matters and scope to that one upload",
              r: "You close early. The USB copies and the staged finance folder go unnoticed for now.",
              w: "The first alert is rarely the whole story. Insiders with time stage across multiple channels." },
            { q: 0, t: "Ask {admin} to sign a statement listing everything they took",
              r: "They list the least incriminating thing they can think of.",
              w: "A self-report from the subject is not a scope. Establish it from evidence." } ] },

        { id: "lv3", ph: "contain", kc: "install", att: ["T1098", "T1053.005"],
          obs: "They granted a rarely used break-glass login extra rights and set a script to run on a timer after their leaving date.",
          title: "A parting gift",
          text: "Buried in the review: a break-glass admin account had its privileges quietly widened last week, and a task is set to run a script next Monday, after {admin} is gone. It calls a script in a folder only {admin} could write to. How do you contain?",
          art: "Task 'BackupSync-2'  trigger=Mon 02:00  runas=SYSTEM  action=\\\\fileserver\\it$\\sync.ps1\nAccount 'brk-glass-02'  added to Domain Admins  8 days ago  by={admin}",
          disc: "Do you know every privileged account in your directory and who last changed each one? How would you spot a quiet privilege bump?",
          opts: [
            { q: 3, u: ["edr", "plan"], t: "Disable the task and account, preserve the script",
              r: "The task and the account are neutralised and the script is preserved as evidence. The trap is defused without tipping {admin}.",
              f: "You disable both, but the script share had two more copies of the payload you find the next morning.",
              w: "Remove the trigger and the extra access, but preserve the payload as evidence and assume there is more than one copy." },
            { q: 2, t: "Delete the task, the account and the script straight away to be safe",
              r: "The threat is gone and so is the evidence of what it would have done and who set it.",
              w: "Deleting neutralises but destroys the proof. Disable and preserve; you may need it for dismissal or prosecution." },
            { q: 1, t: "Leave it in place and just plan to be watching on Monday to catch it running",
              r: "A risky bet on a destructive task. If your watch slips, it runs.",
              w: "Never leave a known destructive trigger armed to observe it. Defuse now." },
            { q: 0, esc: true, t: "Assume it's a legitimate backup task and move on to the data question",
              r: "It is not a backup task. It is waiting for Monday.",
              w: "A privileged task pointing at a share only the suspect can write to is not routine. Treat it as hostile." } ] },

        { id: "lv4", ph: "erad", kc: "install", att: ["T1098.001"],
          obs: "Beyond the one account, the person had left several ways back in during their years of access.",
          title: "Everything they touched",
          text: "Friday is the leaving date. {admin} has held the keys for years. Before that access ends, how do you make sure it really ends?",
          disc: "When someone privileged leaves, what actually gets rotated: their account, or every credential and key they ever had sight of?",
          opts: [
            { q: 3, u: ["edr"], t: "Rotate every credential and key {admin} could reach",
              r: "Domain and service credentials, VPN certs, cloud keys and the shared vault entries are all rotated overnight.",
              f: "The rotation is thorough but breaks an undocumented integration to {supplier} that used a shared key. Fixed by mid-morning.",
              w: "A privileged leaver knows secrets, not just their own password. Rotate everything within their reach: service accounts, keys, shared vault entries." },
            { q: 2, t: "Disable {admin}'s personal accounts and revoke their VPN certificate",
              r: "Their named access is gone. The shared service-account passwords they memorised are not.",
              w: "Disabling the named account misses shared and service credentials the insider also knew." },
            { q: 1, t: "Change the passwords {admin} used most often and monitor the rest",
              r: "Partial coverage leaves known credentials live.",
              w: "Half a rotation is an open door. Insiders return through the credential you left." },
            { q: 0, t: "Trust the standard HR offboarding checklist to disable their account on Friday",
              r: "The checklist disables one account and ticks a box. It never heard of the service accounts.",
              w: "Standard offboarding rarely covers privileged secondary access. It needs a security-led version for admins." } ] },

        { id: "lv5", ph: "recover", kc: "actions", at: 30.0, att: ["T1213"],
          obs: "The exported customer records and the HR pay file contain personal data of customers and staff.",
          title: "The data that left",
          text: "Thursday. You have confirmed the customer CRM export, finance folders and an HR pay file left the building on a personal drive and to a personal account. This is personal data. How do you handle the breach question?",
          disc: "Is data taken by an employee to a competitor a notifiable breach? Who in your organisation decides, and on what timeline?",
          opts: [
            { q: 3, t: "Assess against the breach criteria with the DPO and legal",
              r: "The DPO leads the assessment. The customer and staff data clearly qualifies, and the clock is managed deliberately.",
              w: "Data leaving to a competitor with staff and customer records is very likely notifiable. Assess formally with the DPO and legal against the criteria." },
            { q: 2, t: "Wait for the police or legal process to conclude before deciding on notification",
              r: "The investigation takes months. The regulator's clock does not.",
              w: "Notification duties run on their own statutory clock and don't pause for a police case." },
            { q: 1, t: "Treat it as an HR matter only, since it was an employee not a hacker",
              r: "HR handles the dismissal. The unnotified customer data becomes the bigger problem later.",
              w: "The route in doesn't change the duty. Personal data left the controller's control." },
            { q: 0, t: "Keep it quiet to protect {org}'s reputation while you try to recover the files",
              r: "It surfaces anyway when {admin} joins the competitor. Now it's a cover-up story too.",
              w: "Concealing a notifiable breach compounds the harm and the penalties." } ] },

        { id: "lv6", ph: "recover", kc: "actions", at: 54.0,
          title: "The last day",
          text: "Friday, {admin}'s leaving date. The technical work is done. What goes into how {org} handles the exit and the aftermath?",
          disc: "Does your leaver process treat a resigning admin differently from a resigning receptionist? Should it?",
          opts: [
            { q: 3, t: "Run a witnessed exit, recover devices, pursue the data legally",
              r: "A controlled exit. Devices are collected, an undertaking to delete the data is sought, and the evidence trail is intact.",
              w: "A privileged leaver's exit is a controlled process: witnessed, devices recovered, and data return pursued lawfully with the evidence preserved." },
            { q: 2, t: "Recover the laptop and phone and consider the matter closed once they're gone",
              r: "The hardware is back. The copies in personal accounts are not.",
              w: "Getting the devices back doesn't recover data already in personal accounts. Pursue deletion undertakings." },
            { q: 1, t: "Send a stern email reminding {admin} of their confidentiality obligations",
              r: "It is read once and ignored.",
              w: "A reminder without a legal process rarely changes behaviour after someone has already taken data." },
            { q: 0, t: "Give {admin} a good reference to keep things amicable and avoid a fight",
              r: "The competitor now has your data and a glowing reference to go with it.",
              w: "Amicability is not a control. Handle the exit on the facts, not on avoiding awkwardness." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1485", "T1562.001"],
        obs: "The planted task ran, turning off endpoint protection and deleting the shared drives.",
        title: "Monday, 02:00",
        text: "The timed task you left armed fires. Endpoint protection is switched off on the file servers and the shared drives begin deleting. It ran because it was never defused.",
        opts: [
            { q: 3, u: ["backup", "edr"], t: "Isolate servers, kill the task, restore backups",
              r: "The task is stopped part way through and clean drives are restored from Sunday's immutable copy.",
              w: "When a logic bomb fires: stop the mechanism, cut the access it used, and restore from a copy it could not reach." },
            { q: 2, t: "Power the file servers off to stop the deletion",
              r: "Deletion stops with partial loss, and the evidence of exactly what ran is muddied.",
              w: "Blunt but understandable under live destruction. Isolation preserves more." },
            { q: 0, t: "Try to phone {admin} to ask how to stop their script",
              r: "It goes to voicemail. On a competitor's payroll now, they are not picking up.",
              w: "The person who armed the trap is not your incident response plan." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline improvement after an insider walked out with the crown jewels. What do you push?",
        opts: [
            { q: 3, t: "Privileged access management, leaver controls and DLP",
              w: "It breaks the chain at every point: least privilege limits what one admin can take, leaver controls end all their access, and DLP flags the bulk copy." },
            { q: 2, t: "Require two people to approve any large data export",
              w: "A useful control on one channel, but an admin with broad rights has many channels. It needs the wider access programme around it." },
            { q: 1, t: "Make all staff re-sign the confidentiality policy every year",
              w: "Paper deters the honest. It did nothing to stop someone who decided to take the data." },
            { q: 0, t: "Ban USB drives across the whole organisation",
              w: "One channel of several, and blunt enough to be worked around or waived within a week." } ] }
});

/* ---------- 12. Under the Floor (rogue physical implant) ---------- */
SCEN.push({
    id: "implant", name: "Under the Floor",
    blurb: "Facilities found a small computer with a SIM card wired into a switch in a meeting room. It has been there a while.",
    tags: ["physical", "pii"], start: [3, 11, 0],
    actor: "An intruder who gained brief physical access, posing as a contractor, and left a cellular-connected drop box wired into the network. Physical implants are rare but bypass the perimeter entirely and hide from internet egress monitoring.",
    sum: "found a rogue cellular-connected device wired into its internal network, giving an outsider remote access that bypassed the firewall",
    escSum: "the implant was used to stage and exfiltrate a bulk data dump over its own mobile connection before it was removed.",
    pre: [
        { kc: "recon", att: "T1591", txt: "Cased the building and its visitor process, likely posing as maintenance to learn where the network cabinets were." },
        { kc: "delivery", att: "T1200", txt: "Built a small single-board computer with a 4G modem and, during a brief unescorted moment, wired it into a live switch port." }
    ],
    intro: "Thursday, 11:00. The facilities manager sends a photo to the IT channel: a small circuit board in a plastic case, zip-tied inside the network cabinet of meeting room 2, with a blinking LED, a SIM card and a network cable running into the switch. Nobody in IT put it there. You are the lead analyst.",
    nodes: [
        { id: "im1", ph: "ident", kc: "delivery", att: ["T1200"],
          obs: "An unauthorised small computer with a mobile data dongle was found wired into an internal network switch.",
          title: "What is that thing",
          text: "The device is live, connected to the switch and to a mobile network. It has been in a room used by visitors and contractors. What do you do first?",
          art: "Photo: Raspberry Pi 4 in case, USB 4G modem, SIM present, Ethernet to SW-MR2 port 14\nSwitch: port 14 up, MAC not in inventory, first seen 9 days ago",
          disc: "If someone found an unknown device on your network right now, who decides whether to pull it, and is it also a matter for the police?",
          opts: [
            { q: 3, t: "Photograph it, isolate the switch port, treat as evidence",
              r: "The port is shut, the device is left physically in place and documented. Access is cut without destroying the evidence.",
              f: "You shut the port, but it's the wrong one: the patching is mislabelled and the device stays live for another 15 minutes until you trace the cable.",
              w: "Cut its network access at the switch, but preserve the device in place with a chain of custody. It is potential criminal evidence." },
            { q: 2, t: "Unplug the device straight away to be sure it can't do any more",
              r: "It's off the wired network. It still has power from the cabinet, still has its SIM, and you have handled the evidence.",
              w: "Pulling it stops the wired path but leaves the cellular side and risks the evidence. Isolate at the switch first, then handle it properly." },
            { q: 1, t: "Leave it running and watch its traffic to learn what it's doing",
              r: "It talks only over its own mobile connection, which you can't see. You learn almost nothing while it keeps working.",
              w: "You can't monitor traffic that leaves over a mobile network you don't control. Watching gives the attacker time, not you intelligence." },
            { q: 0, set: "smashed", t: "Rip it out and bin it so it's dealt with",
              r: "The threat on that port is gone, and so is any hope of forensics, attribution or knowing what it reached.",
              w: "Destroying the device throws away the answer to the only question that matters: what did it touch?" } ] },

        { id: "im2", ph: "ident", kc: "c2", att: ["T1090", "T1011"],
          obs: "The device routed its traffic out over a mobile network, sidestepping the company's internet filtering entirely.",
          title: "A door you can't see",
          text: "Analysis of the device (or its twin, imaged carefully) shows a reverse tunnel out over the SIM and tools for scanning the internal network. It has had nine days on your LAN with an out-of-band path home. How do you scope what it reached?",
          art: "Config: autossh reverse tunnel to 45.0.113.x over wwan0\nHistory: nmap sweeps of 10.20.0.0/16, responder logs present",
          disc: "How much of your internal network can one device on one switch port reach? Is that meeting room on the same flat network as your servers?",
          opts: [
            { q: 3, u: ["logs"], t: "Hunt internal logs for the device's IP and MAC",
              r: "The internal telemetry shows the sweeps, the hosts it touched and one successful authentication to a file server.",
              f: "Internal east-west logging is thin. You reconstruct the scans from the switch and one server's logs, but the middle is fuzzy.",
              w: "Even without egress visibility, internal telemetry shows where the device went: scans, connections and any authentications it made." },
            { q: 2, t: "Assume the whole flat network is compromised and plan to rebuild everything",
              r: "Safe, enormous, and probably far more than the evidence supports.",
              w: "Assume breach, but scope it. Rebuilding everything without evidence burns effort you'll need elsewhere." },
            { q: 1, t: "Check only the meeting-room subnet, since that's where it was plugged in",
              r: "On a flat network the device reached far beyond that subnet. You miss the file-server touch.",
              w: "Where it plugged in is not where it could reach. Scope by what the network allowed, not by physical location." },
            { q: 0, t: "Conclude it probably didn't do much in nine days and close it out",
              r: "Nine days is a long time for an automated implant. It did plenty.",
              w: "Dwell time is opportunity. Treat a nine-day foothold as a serious intrusion until proven otherwise." } ] },

        { id: "im2x", ph: "contain", kc: "c2", if: "smashed", enter: { heat: 1 },
          title: "No device, no answers",
          text: "Because the device was destroyed, you can't image it. You are now scoping blind, from network evidence only. This makes everything slower. How do you proceed?",
          disc: "How much of an intrusion can you reconstruct with no host to examine, only network and identity logs?",
          opts: [
            { q: 3, u: ["logs"], t: "Rebuild activity from switch, DHCP and server logs",
              r: "It is slower and gappy, but the logs still place the device and show what it authenticated to.",
              f: "The logs get you most of the way, but the key window overlaps a SIEM outage. Best-effort it is.",
              w: "With no host, network and identity telemetry are all you have. They can still reconstruct much of the intrusion, just more slowly." },
            { q: 1, t: "Ask facilities to keep an eye out in case another one turns up",
              r: "Passive hope is not a scope.",
              w: "You need an active reconstruction from the evidence you do have, not a lookout." },
            { q: 0, t: "Declare it contained since the device is gone",
              r: "The device is gone. Whatever it did, and whatever else was planted, is not.",
              w: "Removing one device does not close an intrusion of unknown scope." } ] },

        { id: "im3", ph: "contain", kc: "exploit", att: ["T1557"],
          obs: "The implant answered internal name-lookup requests to trick a server into handing over a login it could crack.",
          title: "How it got a login",
          text: "The device captured a credential by answering broadcast name-lookup requests on the flat network and relaying the response. A service account's hash was captured and used against a file server. How do you contain the identity side?",
          disc: "Is legacy broadcast name resolution still on across your network? What would it take to turn it off safely?",
          opts: [
            { q: 3, u: ["idp", "edr"], t: "Reset the account, hunt its use, disable the legacy protocol",
              r: "The account is rotated, its recent use is traced, and the broadcast protocol is disabled on the affected segments.",
              f: "The reset and hunt go fine. Disabling the legacy protocol breaks an ancient print server nobody owned up to. Fixed after lunch.",
              w: "Contain the stolen credential and shut the mechanism: reset and hunt the account, and disable the legacy name resolution the capture relied on." },
            { q: 2, t: "Reset the captured service account and move on",
              r: "The one account is safe. The technique still works against the next one tomorrow.",
              w: "Resetting the account without disabling the capture method leaves the door open for a repeat." },
            { q: 1, t: "Block the device's mobile provider at the firewall",
              r: "The device never used your firewall. It has its own connection.",
              w: "You cannot firewall a path that doesn't traverse your firewall." },
            { q: 0, t: "Assume the captured account wasn't actually used and leave it",
              r: "It was used, against a file server, an hour after capture.",
              w: "Assume a captured credential was used. The logs here say it was." } ] },

        { id: "im4", ph: "erad", kc: "install", att: ["T1046"],
          obs: "One device was found, but nothing rules out a second, and the way it got in is still open.",
          title: "Only one?",
          text: "You have one device and one captured account handled. But someone walked in and wired hardware to your network. How do you make sure that's the end of it?",
          disc: "When did you last physically audit your network cabinets and match every connected device to your inventory?",
          opts: [
            { q: 3, t: "Sweep every cabinet and port, rotate exposed credentials",
              r: "A full physical and port sweep finds no second device, and the potentially exposed credentials are rotated.",
              f: "The sweep finds a forgotten unmanaged switch in another meeting room. Legitimate, but it took an hour to prove.",
              w: "One planted device means the physical and identity trust is broken. Sweep every cabinet and port, and rotate what could have been captured." },
            { q: 2, t: "Check the other meeting rooms on that floor",
              r: "Reasonable, but the intruder wasn't confined to one floor.",
              w: "Partial sweeps leave partial assurance. Cover the whole estate's network points." },
            { q: 1, t: "Rely on the switch's port security to have blocked anything else",
              r: "Port security was not enabled on the access switches, which is how this happened.",
              w: "Trusting a control you haven't confirmed is on is how the first device got a port." },
            { q: 0, t: "Assume it was a one-off and skip the sweep",
              r: "Assumption is not eradication.",
              w: "You have direct proof someone can plant hardware here. Prove it happened only once." } ] },

        { id: "im5", ph: "recover", kc: "actions", at: 20.0,
          title: "What went out the SIM",
          text: "The device had nine days and its own mobile connection, which your egress monitoring never saw. You need a defensible view of what may have left, for the breach question.",
          disc: "How would you assess a breach when the exfiltration path was completely invisible to you?",
          opts: [
            { q: 3, t: "Assess the breach on what the device could reach, with the DPO",
              r: "The DPO leads a worst-reasonable-case assessment based on what the device could access. Notification is prepared accordingly.",
              w: "When the exfil path is invisible, assess on what the device could reach, not on the traffic you couldn't see. Involve the DPO early." },
            { q: 2, t: "Report that no exfiltration was observed, since you have no egress logs for it",
              r: "Technically true and dangerously misleading. Absence of a log you never had is not absence of exfiltration.",
              w: "No evidence of exfiltration over a channel you can't see is not evidence of none. Say what could have left." },
            { q: 1, t: "Wait for the forensic lab report on the SIM before saying anything",
              r: "The lab takes weeks. The breach clock does not.",
              w: "Deep forensics inform the final picture but can't hold up the statutory assessment." },
            { q: 0, t: "Conclude nothing left, since the device is now gone",
              r: "It had nine days before it was gone.",
              w: "The device being gone tells you nothing about the nine days it worked." } ] },

        { id: "im6", ph: "recover", kc: "actions", at: 44.0,
          title: "Closing the front door",
          text: "The network is clean. But the root cause was physical: someone got unescorted access and wired into a live, flat network. What goes into recovery?",
          disc: "What stops an unescorted visitor from plugging into your network today: the locked cabinet, the switch config, or nothing?",
          opts: [
            { q: 3, t: "Enable port control and tighten physical access",
              r: "Access ports now reject unknown devices, cabinets are locked and visitor escorting is enforced.",
              w: "Fix both halves: make the network reject unknown devices, and make it hard to reach a live port physically in the first place." },
            { q: 2, t: "Lock the network cabinets and leave the network config as it is",
              r: "Better locks, same flat network with open ports behind the next unlocked door.",
              w: "Physical locks help, but a flat network with open ports is still one propped door away from a repeat." },
            { q: 1, t: "Add the incident to the risk register and review it next quarter",
              r: "The register grows. The open ports stay open.",
              w: "Logging the risk is not treating it. The control gap is concrete and fixable now." },
            { q: 0, t: "Put up a sign asking visitors not to touch the network cabinets",
              r: "The kind of person who plants an implant does not read the sign.",
              w: "Signs deter the honest. They do not enforce anything." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1105", "T1011"],
        obs: "Before removal, the implant pulled tools in and pushed a bulk data dump out over its own mobile link.",
        title: "It moved first",
        text: "While the response was still forming, the device pulled down extra tooling and began pushing a large archive out over its mobile connection. The out-of-band path you couldn't see is being used to steal data.",
        opts: [
            { q: 3, u: ["edr", "plan"], t: "Isolate the port, seize the device",
              r: "The wired path is cut and reachable hosts are isolated. The device is seized before it can be told to wipe itself.",
              w: "Even with an invisible egress path, you can cut the device's access to fresh data and seize it. Then assess what the dump contained." },
            { q: 2, t: "Shut down the switch serving that room entirely",
              r: "The device loses the LAN, and so does a room full of people mid-meeting. It stops the wired side.",
              w: "Effective and blunt. Isolating the single port is cleaner." },
            { q: 0, t: "Wait to see how big the dump gets before acting",
              r: "It gets as big as it needs to.",
              w: "Watching an active exfiltration you can't intercept just measures the loss." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline improvement after finding rogue hardware on the LAN. What do you push?",
        opts: [
            { q: 3, t: "802.1X access control plus segmentation",
              w: "It breaks the chain at the plug: an unknown device can't join, and even if it did, segmentation means one port is not a path to the servers." },
            { q: 2, t: "Roll out better locks and CCTV on all comms rooms",
              w: "Physical security matters, but it's the second line. The network trusting any device that plugs in is the root cause." },
            { q: 1, t: "Turn off any unused switch ports across the estate",
              w: "A sensible hygiene step, but the attacker used a live port. It doesn't stop the next propped door." },
            { q: 0, t: "Require all visitors to wear badges",
              w: "This intruder posed as a contractor. A badge lanyard would not have stopped them." } ] }
});

/* ---------- 13. Trusted Hands (MSP / RMM supply chain) ---------- */
SCEN.push({
    id: "msp", name: "Trusted Hands",
    blurb: "Your outsourced IT provider's remote management tool just started pushing an encryptor to every one of your machines.",
    tags: ["supply", "ransomware", "pii"], start: [5, 6, 30],
    actor: "A ransomware affiliate who breached a managed service provider's remote management platform and used its standing access to push their payload to every downstream client at once. Compromising an MSP is a force multiplier behind several mass ransomware events.",
    sum: "was hit by ransomware pushed through its managed service provider's remote management platform, which had standing access to every endpoint",
    escSum: "the encryptor finished running across the estate before the provider's agent could be cut off.",
    pre: [
        { kc: "recon", att: "T1591", txt: "The attacker targeted the MSP, not you: one provider is a doorway into all of its clients at once." },
        { kc: "exploit", att: "T1199", txt: "Compromised the MSP's management console with stolen administrator credentials, inheriting its trusted access into {org}." }
    ],
    intro: "Saturday, 06:30. Your phone lights up: EDR alerts across dozens of endpoints, all running the same PowerShell script, all launched by the agent your outsourced IT provider uses to manage your machines. The provider's support line rings out. A user forum thread titled 'is [provider] down? getting weird files' is filling up. You are the lead analyst.",
    nodes: [
        { id: "ms1", ph: "ident", kc: "actions", att: ["T1072"],
          obs: "Dozens of endpoints simultaneously ran the same script, pushed down by the outsourced provider's management agent.",
          title: "Everything at once",
          text: "This isn't one machine, it's dozens firing in the same minute, all from the management agent. The provider isn't answering. What do you do first?",
          art: "06:22 EDR  38 hosts  powershell.exe -enc <base64>  parent=rmm-agent.exe\n06:22 EDR  same script hash across all 38\nProvider status page: 'All systems operational'",
          disc: "If your IT provider's tool turned hostile at 06:30 on a Saturday, who on your side can act without waiting for them?",
          opts: [
            { q: 3, u: ["edr", "plan"], t: "Declare an incident and use your own EDR to isolate hosts",
              r: "You don't wait for the provider. EDR blocks the agent's script and begins isolating the affected hosts.",
              f: "EDR isolation works on most hosts. On a handful the agent has local admin and fights back; those need a manual pull.",
              w: "When a trusted tool turns hostile, act with the controls you own. Don't wait for the party whose tool is the problem." },
            { q: 2, t: "Keep trying to reach the provider before you touch anything they manage",
              r: "You dial for twenty minutes. The script keeps running on twenty more machines.",
              w: "Coordinating with the MSP matters, but not before stopping active harm with your own tools." },
            { q: 1, t: "Shut down the affected machines one by one as you get to them",
              r: "Slow, manual, and it destroys the memory evidence as you go.",
              w: "Manual power-offs don't scale to a fleet-wide push and lose evidence. Use central isolation." },
            { q: 0, set: "trusting", t: "Assume the provider is deploying a legitimate update that's misbehaving",
              r: "You give it the benefit of the doubt. It is not an update. It is an encryptor.",
              w: "A base64 script hitting your whole estate at once is not a routine patch. Treat it as hostile until proven otherwise." } ] },

        { id: "ms2", ph: "ident", kc: "c2", att: ["T1219", "T1078"],
          obs: "The provider's support software was being driven from outside to run commands across the whole estate.",
          title: "Whose hands on the wheel",
          text: "The commands are coming through the provider's legitimate support software, driven by their own privileged access, from an IP that isn't theirs. Other clients on the forum report the same. How do you scope?",
          art: "RMM audit: script pushed by user 'msp-admin'  src=185.0.113.x (not provider range)\nForum: 4 other companies report identical rmm-agent.exe activity",
          disc: "Do you know exactly what your MSP's tools can do on your network, and from where they normally connect?",
          opts: [
            { q: 3, u: ["logs"], t: "Treat the provider's access as compromised, map its full reach",
              r: "You map the agent's reach and the MSP accounts' rights. It's broad: the agent runs as SYSTEM almost everywhere.",
              f: "The mapping is sobering and slow: nobody had documented the MSP's full access, so you build it live from logs.",
              w: "If the provider is compromised, so is everything their tools and accounts can touch. Scope by their full standing access, not the first 38 hosts." },
            { q: 2, t: "Focus on the 38 hosts already alerting and deal with the rest later",
              r: "The 38 are contained. The agent still has SYSTEM on the other 300.",
              w: "The alerting hosts are where it started, not where it can go. The trusted agent is everywhere." },
            { q: 1, t: "Wait for the provider to tell you which systems are affected",
              r: "The provider is themselves mid-incident and not answering.",
              w: "A provider in the middle of their own breach is not a reliable source of your scope." },
            { q: 0, t: "Assume only Windows machines matter and skip the servers",
              r: "The agent manages the servers too. They are very much in scope.",
              w: "The management agent's footprint defines scope, and it usually includes servers." } ] },

        { id: "ms2x", ph: "contain", kc: "actions", if: "trusting", enter: { heat: 1 },
          title: "Lost minutes",
          text: "The minutes you spent assuming it was a bad update let the push reach more machines. It is clearly hostile now. How do you catch up?",
          opts: [
            { q: 3, u: ["edr"], t: "Blanket-block the agent's script fleet-wide",
              r: "A fleet-wide block finally halts new executions. The spread stops, later than it should have.",
              f: "The block lands, but the extra machines it reached in the delay now need cleaning too.",
              w: "Once you've lost time, act broadly: block the mechanism everywhere at once rather than chasing hosts individually." },
            { q: 1, t: "Go back to trying the provider's support line",
              r: "Still ringing out. The clock keeps running.",
              w: "The provider is not going to answer in time. Use your own controls." },
            { q: 0, t: "Hope the encryptor fails on the remaining machines",
              r: "It does not fail. It is quite well tested.",
              w: "Hope is not containment for an active fleet-wide push." } ] },

        { id: "ms3", ph: "contain", kc: "actions", att: ["T1486", "T1490"],
          obs: "On reached machines the payload began encrypting files and deleting the local recovery copies.",
          title: "Cut the cord",
          text: "The agent is your provider's lifeline into your network, and right now it's the attacker's. You need to sever the MSP's standing access without waiting for them, knowing they are also your only IT support. How?",
          disc: "Could you disconnect your MSP's access to your network in ten minutes if you had to? Who holds that switch?",
          opts: [
            { q: 3, u: ["edr", "plan"], t: "Disable the agent, cut the MSP's access, protect backups",
              r: "The agent is dead, the MSP's inbound access is blocked at the firewall, and the backups are sealed and checked.",
              f: "Agent and VPN are cut. One forgotten site-to-site tunnel to the MSP stays up for another half hour until you find it.",
              w: "Sever every path the provider has: the agent, the VPN, the jump hosts. Then protect backups, the payload's next target." },
            { q: 2, fx: { trust: -3 }, t: "Pull your entire internet connection to be certain nothing gets in or out",
              r: "It works and it takes the whole business offline, including the systems that were fine.",
              w: "A sledgehammer that also stops legitimate work. Targeted severing of the MSP's access is proportionate." },
            { q: 1, t: "Ask the provider to disable their own access from their side",
              r: "Their side is the compromised side. You'd be asking the attacker to lock themselves out.",
              w: "Don't rely on the compromised party to contain your network. Cut it yourself." },
            { q: 0, esc: true, t: "Leave the agent in place so the provider can help fix it remotely",
              r: "The agent is exactly what the attacker is using. You've left them the wheel.",
              w: "The compromised tool cannot be the recovery tool. Cut it, then rebuild access cleanly." } ] },

        { id: "ms4", ph: "erad", kc: "install", att: ["T1098"],
          obs: "The intruder had used the provider's rights to add access of their own that would survive the agent being removed.",
          title: "Roots through a third party",
          text: "The payload is stopped. But the attacker had SYSTEM across the estate through the agent and may have left their own way back in that doesn't need the MSP at all. How do you eradicate?",
          disc: "If a third party's compromise gave an attacker admin everywhere, what would you need to rotate to trust your environment again?",
          opts: [
            { q: 3, u: ["edr"], t: "Hunt attacker persistence, rotate what the MSP could reach",
              r: "You find and remove a rogue account and a scheduled task, then rotate the MSP's shared credentials and the domain secrets the agent could touch.",
              f: "The hunt is thorough. Rotating the MSP's shared admin password breaks two automated jobs nobody documented. Fixed by evening.",
              w: "Assume the attacker used SYSTEM access to plant their own persistence. Remove it and rotate every credential the provider held or the agent could reach." },
            { q: 2, t: "Remove the RMM agent from every machine and call it clean",
              r: "The agent is gone. The rogue account it created is not.",
              w: "Removing the tool doesn't remove what the tool was used to plant." },
            { q: 1, t: "Reimage the 38 originally alerting hosts",
              r: "Those hosts are clean and the identity persistence across the estate survives.",
              w: "Reimaging the first hosts misses estate-wide identity persistence." },
            { q: 0, t: "Let the provider reinstall their agent so management is restored quickly",
              r: "You reconnect the exact access that was just used against you, before it's been cleaned.",
              w: "Don't restore the compromised access path until both sides are verified clean." } ] },

        { id: "ms5", ph: "recover", kc: "actions", at: 20.0, att: ["T1486"],
          obs: "A number of machines and servers were encrypted before the agent was cut off.",
          title: "Back on your feet, and on whose watch",
          text: "Sunday. A chunk of the estate is encrypted. You need to recover, and to answer whether you can keep an IT provider whose tool did this. How do you recover?",
          disc: "If your MSP caused an outage this size, what would it take to trust them again, or to leave?",
          opts: [
            { q: 3, u: ["backup"], t: "Restore from clean backups, rebuild MSP access scoped",
              r: "Clean restores come back from a pre-incident point, and any future provider access is rebuilt scoped and monitored.",
              f: "Restores are clean, but the backup console was itself managed by the MSP's agent and needs rebuilding first.",
              w: "Recover from backups the agent couldn't reach, and treat the provider relationship as something to rebuild on tight, monitored terms, not restore as-was." },
            { q: 2, t: "Restore quickly and reconnect the provider as before so operations resume",
              r: "Fast, and it puts the same broad standing access straight back.",
              w: "Restoring the old trust model reintroduces the exact risk that just detonated." },
            { q: 1, t: "Rebuild everything from scratch and drop the provider entirely with no plan",
              r: "Very clean, and now you have no IT support and weeks of rebuild.",
              w: "Cutting the provider may be right, but with no transition plan you trade one crisis for another." },
            { q: 0, fx: { trust: -6 }, t: "Pay the ransom so the provider can get everyone back online fastest",
              r: "The provider is barely online themselves. Payment funds the crew and the stolen data still surfaces.",
              w: "Payment carries legal and sanctions risk, doesn't undo the data theft, and here relies on the very party that was breached." } ] },

        { id: "ms6", ph: "recover", kc: "actions", at: 44.0,
          title: "Two victims, one story",
          text: "You and the provider are both breach victims, and their other clients are watching. Comms and contracts need handling. What's your approach?",
          disc: "When a shared provider is breached, who tells your customers, and how do you avoid contradicting the other victims?",
          opts: [
            { q: 3, t: "Coordinate facts with the provider, own your notifications",
              r: "A consistent, factual account goes out, and {org} owns its own customer communications rather than outsourcing them.",
              w: "Coordinate the facts, but own your notifications. You are accountable to your customers regardless of who was breached." },
            { q: 2, t: "Wait for the provider to issue one statement covering all their clients",
              r: "Their statement is generic and late, and your regulator expected to hear from you.",
              w: "A shared provider statement doesn't discharge your own duties to your regulator and customers." },
            { q: 1, t: "Say nothing publicly and point any questions at the provider",
              r: "Deflection reads as evasion when your customers' data was involved.",
              w: "Pointing at the provider doesn't remove your accountability and damages trust." },
            { q: 0, t: "Blame the provider loudly in public to protect {org}'s reputation",
              r: "It plays badly, complicates the legal position, and your customers still hold you responsible.",
              w: "Public blame before the facts are settled harms the legal case and rarely convinces anyone." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1486", "T1490"],
        obs: "The encryptor completed across the fleet, locking servers and endpoints and wiping local recovery points.",
        title: "Fleet locked",
        text: "The push finished before the agent was cut. Servers and endpoints across the estate are encrypted and their local recovery points are gone. The provider's tool did in minutes what would normally take an intruder days.",
        opts: [
            { q: 3, u: ["retainer", "backup"], t: "Isolate what's left, seal backups, call the retainer",
              r: "The remaining clean systems are fenced off, offsite immutable backups are confirmed intact, and specialists join the bridge.",
              w: "After fleet-wide detonation: stop any remaining spread, confirm the backups the agent couldn't reach, and bring in specialists and executives at once." },
            { q: 2, t: "Shut down all servers to stop any encryption still running",
              r: "It stops the tail of the run, with some corruption and lost evidence.",
              w: "Defensible under live encryption, but isolation preserves more." },
            { q: 0, t: "Wait for the provider to lead the recovery since it's their tool",
              r: "The provider is overwhelmed across all their clients. You are on your own timeline.",
              w: "A breached provider cannot be your recovery plan. Drive your own." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline improvement after a provider's tool encrypted the estate. What do you push?",
        opts: [
            { q: 3, t: "Scope and monitor third-party access, own your isolation",
              w: "It breaks the chain at the trust: the provider's access is limited and watched, and you can contain even when their tools are the threat." },
            { q: 2, t: "Switch to a different managed service provider",
              w: "Any provider with standing access is the same risk. The problem is unscoped trust, not the logo on it." },
            { q: 1, t: "Add a clause making the provider liable for breaches",
              w: "Liability helps after the fact. It does nothing to stop or contain the next push." },
            { q: 0, t: "Require the provider to run antivirus on their own machines",
              w: "Their hygiene matters, but you cannot audit it and it doesn't limit their access to you." } ] }
});

/* ---------- 14. Scorched (destructive wiper) ---------- */
SCEN.push({
    id: "wiper", name: "Scorched",
    blurb: "Machines rebooted overnight into a ransom note. But nothing is encrypted, and the payment address is dead. This was never about money.",
    tags: ["wiper", "pii"], start: [0, 3, 15],
    actor: "A state-aligned group running a destructive operation disguised as ransomware. There is no working decryption key, because destruction, not payment, is the goal. Wipers masquerading as ransomware have been used repeatedly in geopolitical conflicts.",
    sum: "was hit by destructive wiper malware disguised as ransomware, which overwrote systems with no recoverable key",
    escSum: "the wiper reached the virtualisation and backup infrastructure before it was stopped.",
    pre: [
        { kc: "delivery", att: "T1566.002", txt: "Gained access weeks earlier through a phishing link, then went quiet." },
        { kc: "exploit", att: "T1078", txt: "Sat dormant on valid credentials, waiting for a chosen moment to detonate everywhere at once." }
    ],
    intro: "Monday, 03:15. On-call is woken by a flood of alerts: machines across the estate restarted on their own and came back up showing a full-screen ransom message demanding payment in cryptocurrency. But early reports are strange: files aren't encrypted, they're gibberish, and the 'contact us' address bounces. You are the lead analyst.",
    nodes: [
        { id: "wp1", ph: "ident", kc: "actions", att: ["T1529"],
          obs: "At 03:15 machines across the estate restarted on their own and came up showing a ransom message.",
          title: "Three in the morning",
          text: "Dozens of machines are down and showing a ransom note. It looks like ransomware. What do you do first?",
          art: "03:15 EDR  mass restart events, 60+ hosts\nNote: 'Your files are encrypted. Pay 3 BTC to <wallet>. Contact: <dead address>'\nFirst responder: 'the files aren't locked, they're... scrambled?'",
          disc: "At 03:15, who declares the incident, who can authorise taking systems offline, and how long does that take?",
          opts: [
            { q: 3, u: ["plan"], t: "Declare a major incident and scope before assuming ransomware",
              r: "The incident is declared, the team is on an out-of-band bridge, and the odd early signs are being investigated rather than assumed.",
              f: "The bridge is up fast. One key responder's out-of-hours number is out of date, costing ten minutes to reach them.",
              w: "Mobilise properly and let the evidence, not the note, tell you what this is. The strange early signs matter." },
            { q: 2, t: "Trigger the ransomware playbook immediately based on the note",
              r: "The playbook spins up. Some of its steps, like preserving files for decryption, assume something that isn't true here.",
              w: "Mobilising is right; committing to 'ransomware' before checking the note's claims can send you down the wrong path." },
            { q: 1, t: "Start restoring the downed machines to get people working by morning",
              r: "You restore over live infrastructure without knowing what's happening. Some come straight back down.",
              w: "Restoring before you understand and contain the cause invites reinfection." },
            { q: 0, t: "Prepare to pay the ransom to get the decryption key quickly",
              r: "There is no key to buy. The address is dead and the files are already gone.",
              w: "Rushing to pay before verifying the threat is exactly the mistake this attack is designed to provoke." } ] },

        { id: "wp2", ph: "ident", kc: "actions", noquiz: true, att: ["T1561", "T1485"],
          obs: "The first drives examined show their master boot record overwritten and files replaced with random bytes; there is no key.",
          title: "It's not what it says it is",
          text: "Forensics on two affected machines: the master boot record is overwritten, files are filled with random data, and there is no encryption key anywhere. The 'ransom note' is a costume. What's your call?",
          art: "Disk: MBR overwritten with random bytes\nFiles: high-entropy, no header, no key artifact, no decryptable structure\nWallet: on-chain, already flagged and seized months ago",
          disc: "How would you tell a wiper from ransomware in the first hour, and how does that change your whole response?",
          opts: [
            { q: 3, t: "Call it a wiper and pivot to stopping spread and restoring",
              r: "The team drops the decryption track entirely. This is now a destruction and recovery incident, and everyone knows it.",
              w: "Naming it correctly changes everything: there is nothing to decrypt or negotiate, so every hour goes to stopping spread and restoring." },
            { q: 2, t: "Keep treating it as ransomware but also prepare restores in parallel",
              r: "You hedge. Half the team still chases a decryption path that doesn't exist.",
              w: "Hedging wastes effort on a non-existent key. The evidence is clear enough to commit." },
            { q: 1, t: "Send the samples to a lab and wait for confirmation before deciding",
              r: "The lab confirms it in two days. The wiper spends those two days spreading.",
              w: "Your own forensics already answer the question. Waiting for external confirmation cedes time to a live wiper." },
            { q: 0, t: "Open negotiations with the attacker to buy time",
              r: "There is no one to negotiate with. The address is dead and always was.",
              w: "You cannot negotiate with a destructive operation that never wanted money." } ] },

        { id: "wp3", ph: "contain", kc: "actions", att: ["T1484.001"],
          obs: "The wiper was being pushed to machines through an estate-wide startup script linked at the directory level.",
          title: "Stop the spread",
          text: "The wiper is still propagating: it's being pushed through an estate-wide startup mechanism, and not every machine has run it yet. There is nothing to decrypt, so every un-hit machine is worth saving. How do you contain?",
          disc: "If a destructive payload were spreading through your directory right now, could you break the distribution before the next machine reboots?",
          opts: [
            { q: 3, u: ["edr", "plan"], t: "Break the distribution mechanism, isolate un-hit machines, and protect the backups",
              r: "The push is unlinked before most remaining machines pull it. Un-hit systems are isolated and the backups are sealed.",
              f: "You unlink it, but a batch of machines had already pulled the payload and reboot into it over the next hour. EDR catches most.",
              w: "With a wiper, saving the machines that haven't run it yet is the whole game. Kill the distribution, isolate the clean, protect backups." },
            { q: 2, t: "Shut every machine in the estate down to stop them running the payload",
              r: "It stops execution and takes the business fully dark, with some corruption on shutdown.",
              w: "A blunt last resort that can be justified against a wiper, though it loses evidence and the healthy systems too." },
            { q: 1, t: "Focus on recovering the machines already hit first",
              r: "While you recover the dead ones, the live ones keep dying.",
              w: "Recovering the hit before stopping the spread means recovering into an ongoing attack." },
            { q: 0, esc: true, t: "Wait for executive sign-off before touching the directory in the middle of the night",
              r: "Sign-off arrives at 07:00. So has the wiper, on a great many more machines.",
              w: "Destructive spread is exactly what pre-authorised containment is for. Every minute is machines lost." } ] },

        { id: "wp4", ph: "contain", kc: "exploit", att: ["T1078"],
          obs: "The operator was still logged in on stolen credentials, positioned to re-trigger the payload.",
          title: "Still in the room",
          text: "This didn't fire itself. The operator has been dormant on stolen credentials for weeks and is likely still present, able to push the payload again. How do you deal with the human on the other end?",
          disc: "A wiper implies a patient intruder who chose the moment. How do you find and evict someone who has been quiet for weeks?",
          opts: [
            { q: 3, u: ["idp", "edr"], t: "Hunt the dormant access, revoke credentials, close re-entry",
              r: "The hunt finds the foothold and the stale credentials. Sessions are revoked and the re-entry paths are closed.",
              f: "You evict the main foothold cleanly, but a second set of stolen credentials surfaces the next day and needs the same treatment.",
              w: "A wiper has a patient operator behind it. Hunt the dormant access, kill the credentials and sessions, and close the ways back in." },
            { q: 2, t: "Reset the one account named in the logs and move on",
              r: "One account down. A dormant attacker rarely relies on just one.",
              w: "Resetting a single account underestimates a weeks-long foothold." },
            { q: 1, t: "Assume the wiper firing means the attacker is finished and gone",
              r: "They may be. They may also be waiting to fire it again once you restore.",
              w: "Detonation is not proof of departure. Assume they can re-trigger until you've evicted them." },
            { q: 0, t: "Block the wallet address to cut the attacker off financially",
              r: "The wallet was never the point, and it's already dead.",
              w: "There is no financial channel to cut. This was destruction, not extortion." } ] },

        { id: "wp5", ph: "erad", kc: "install", att: ["T1505.003"],
          obs: "The intruder had left web shells and scheduled tasks during the weeks of dwell time.",
          title: "Weeks of roots",
          text: "The operator had weeks inside before detonation. Eradication has to assume persistence spread during that time, not just the wiper itself. How do you approach it?",
          disc: "If an attacker was dormant in your network for a month, how confident are you that you'd find everything they left?",
          opts: [
            { q: 3, u: ["edr"], t: "Hunt the whole dwell window, remove persistence together",
              r: "The hunt across the dwell period turns up web shells and scheduled tasks, removed together with a domain-wide credential reset.",
              f: "The coordinated removal is solid, but one dormant scheduled task on an isolated host is found only on the second pass.",
              w: "A month of dwell means persistence is scattered. Hunt the whole window and remove it together, or the attacker simply returns." },
            { q: 2, t: "Remove the wiper's distribution mechanism and consider eradication done",
              r: "The payload's launcher is gone. The attacker's older footholds remain.",
              w: "The wiper is the payload, not the persistence. Roots planted over weeks survive its removal." },
            { q: 1, t: "Reimage the machines that were wiped",
              r: "You have to rebuild those anyway, but the dormant footholds on untouched hosts stay.",
              w: "Reimaging the wiped hosts is necessary but doesn't touch persistence elsewhere." },
            { q: 0, t: "Restore from backup and treat that as a clean slate",
              r: "The backup predates the wiper but not necessarily the intrusion. The foothold may come back with it.",
              w: "A restore point after the initial access can carry the attacker's persistence with it." } ] },

        { id: "wp6", ph: "recover", kc: "actions", at: 26.0, att: ["T1490"],
          obs: "With no decryption possible, restoring from backups is the only path, and the attacker had targeted recovery.",
          title: "Backups are everything",
          text: "There is no decryptor and never will be. Recovery is entirely a restore-and-rebuild job, on machines whose boot records were destroyed. How do you recover?",
          disc: "If every wiped machine could only come back from backup, how far would today's backups actually get you?",
          opts: [
            { q: 3, u: ["backup"], t: "Rebuild and restore from clean pre-intrusion backups",
              r: "Machines are rebuilt from images, data comes back from an immutable copy the attacker couldn't reach, all validated before reconnecting.",
              f: "Restores are clean, but one critical system's last good backup is older than hoped, costing a day of data.",
              w: "With no key, immutable backups are the entire recovery. Rebuild the OS, restore data from a point before the intrusion, validate before reconnecting." },
            { q: 2, t: "Restore the most recent backups straight into production to move fast",
              r: "Fast, and you risk carrying the attacker's foothold back in with a too-recent restore point.",
              w: "The newest backup may sit inside the dwell window. Choose the restore point against the intrusion timeline." },
            { q: 1, t: "Try third-party 'wiper recovery' tools before restoring",
              r: "Overwritten data does not come back. The random bytes are random bytes.",
              w: "There is nothing to recover from an overwrite. Restoration from backup is the path." },
            { q: 0, fx: { trust: -6 }, t: "Pay the ransom in case a key exists after all",
              r: "There is no key. You've funded a destructive operation and recovered nothing.",
              w: "Paying a wiper crew gets you nothing but a paper trail and sanctions risk." } ] },

        { id: "wp7", ph: "recover", kc: "actions", at: 50.0,
          title: "It was never about money",
          text: "The board is rattled and someone keeps asking whether paying would 'just make it go away'. The recovery is grinding on. What frames the wrap-up?",
          disc: "How do you explain to a board that this attacker never wanted anything you could give them?",
          opts: [
            { q: 3, t: "Frame it as destruction, fund closing the way in",
              r: "The board understands there was nothing to buy, and the dormant entry route that enabled it gets funded to be fixed.",
              w: "The honest frame: destruction can't be paid away, so the wins are recovery speed and permanently closing the way in." },
            { q: 2, t: "Focus the wrap-up on faster restore times for next time",
              r: "Useful, but it treats the symptom and skips the weeks of undetected access that made it possible.",
              w: "Faster recovery helps, but the real gap was a month of undetected dwell. Address both." },
            { q: 1, t: "Reassure the board it was a one-off unlikely to recur",
              r: "The same access route is still open until someone fixes it.",
              w: "Comfort without fixing the entry point invites a repeat by the same or another actor." },
            { q: 0, t: "Quietly authorise a payment attempt to reassure nervous executives",
              r: "It reassures no one and funds nothing recoverable.",
              w: "Paying to soothe nerves against a wiper is money burned and a governance problem." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1485", "T1490"],
        obs: "The wiper reached the virtualisation hosts and the backup server, destroying data and recovery points together.",
        title: "It reached the backups",
        text: "The distribution wasn't stopped in time and the wiper reached the virtualisation cluster and the backup server on the same flat network. Recovery points and live systems are being destroyed together.",
        opts: [
            { q: 3, u: ["backup", "retainer"], t: "Isolate backups, fall back to offsite copies, call the retainer",
              r: "The spread is walled off from the offsite immutable backups, which are intact, and specialists join to run the rebuild.",
              w: "When a wiper hits recovery infrastructure, the offsite immutable copy is the last line. Isolate it, fall back to it, and bring in specialists." },
            { q: 2, t: "Power off the virtualisation cluster to stop the destruction",
              r: "It stops the run at the cost of corruption and any evidence in memory.",
              w: "Defensible against active destruction, but it loses the running state and evidence." },
            { q: 0, t: "Accept the loss and rebuild everything from bare metal with no backups",
              r: "Months of work and permanent data loss, when an offsite copy might have existed.",
              w: "Bare-metal rebuild is the outcome only if every backup is truly gone. Confirm the offsite copy first." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline improvement after a wiper hit the estate. What do you push?",
        opts: [
            { q: 3, t: "Immutable offline backups, faster detection",
              w: "It breaks the chain at both ends: backups the wiper can't reach make recovery possible, and shorter dwell stops the quiet weeks that set it up." },
            { q: 2, t: "Buy a faster storage array to speed up restores",
              w: "Speed helps only if the backups survive. Immutability and segmentation come first." },
            { q: 1, t: "Increase the ransom insurance cover",
              w: "There is nothing to pay a wiper for. Insurance for extortion misreads the threat." },
            { q: 0, t: "Add another antivirus product to the endpoints",
              w: "The payload sat dormant for weeks on valid access. More endpoint AV misses the actual gap." } ] }
});

/* ---------- 15. Open Door (data exposure and coordinated disclosure) ---------- */
SCEN.push({
    id: "exposure", name: "Open Door",
    blurb: "A security researcher emails: your customer backup is sitting on the open internet with no password. The question is who found it first.",
    tags: ["pii"], start: [1, 10, 30],
    actor: "No intruder in your network. A misconfiguration left a backup exposed to anyone who looked, and bulk scanners look constantly. A helpful researcher found it; the unknown is who else did, and what they took.",
    sum: "discovered that a database backup containing millions of customer records had been left exposed on the internet with no authentication",
    escSum: "the exposed data was scraped and offered for sale before the store could be locked down.",
    pre: [
        { kc: "recon", att: "T1595.002", txt: "Bulk internet scanners continuously index exposed services; this store was indexed like any other." },
        { kc: "recon", att: "T1580", txt: "Anyone enumerating cloud ranges could list the store's contents, because it required no login at all." }
    ],
    intro: "Tuesday, 10:30. An email arrives from someone signing off as an independent security researcher: 'Your customer database backup is publicly accessible with no authentication. ~2.3 million records. I have not downloaded it. Please secure it. Happy to share details.' A link is attached. You are the lead analyst. Your first instinct sets the tone for everything that follows.",
    nodes: [
        { id: "ex1", ph: "ident", kc: "recon", att: ["T1595.002"],
          obs: "A researcher located the open store the same way bulk internet probes do, by connecting to a service that asked for no login.",
          title: "The email",
          text: "The email is calm and specific. It could be genuine, a scam, or the opening of an extortion attempt. How do you respond?",
          art: "From: researcher <redacted>\nSubject: Exposed customer data - please secure\n'No auth required. ~2.3M records. Not downloaded. Details on request.'\nLink: https://<storage-host>/backups/  (no credentials prompted)",
          disc: "If a stranger emailed you tonight saying your data was exposed, who reads it, who replies, and how fast?",
          opts: [
            { q: 3, t: "Acknowledge the researcher, get details, verify in parallel",
              r: "A courteous reply keeps the researcher onside while your team independently checks whether the store is really exposed.",
              w: "A genuine reporter is an asset. Engage professionally to learn what they know while you verify it yourself, without admitting or promising anything prematurely." },
            { q: 2, t: "Verify the exposure first and reply to the researcher only once you know it's real",
              r: "Sensible caution, though a long silence risks a helpful researcher deciding to go public instead.",
              w: "Verifying first is fine, but leaving a good-faith reporter with no acknowledgement can push them toward disclosure. A holding reply costs nothing." },
            { q: 1, set: "hostile", t: "Reply warning the researcher they accessed your data without authorisation",
              r: "The tone lands badly. The researcher, who was trying to help, stops cooperating and starts documenting your reaction.",
              w: "Threatening a good-faith reporter turns an ally into an adversary and looks terrible if it becomes public." },
            { q: 0, set: "hostile", t: "Ignore it as probable spam and carry on with the day",
              r: "The exposure stays open and public. The clock you don't know is running keeps running.",
              w: "A specific, verifiable report is not spam. Ignoring it leaves real data exposed and wastes the warning." } ] },

        { id: "ex1x", ph: "ident", kc: "recon", if: "hostile", enter: { heat: 1 },
          title: "Going public",
          text: "Handled coldly, the researcher has posted that a company is exposing millions of records and being unresponsive. A journalist has picked it up. The exposure is now a story before it's even fixed. How do you recover the situation?",
          disc: "How much harder is a breach to manage once it's a headline about your unresponsiveness?",
          opts: [
            { q: 3, t: "Secure the data, re-engage, lead with facts",
              r: "The store is locked down first, the researcher gets a genuine response, and a factual statement replaces the silence.",
              w: "Fix the exposure, repair the relationship, and lead with facts. Silence is what made it a story." },
            { q: 1, t: "Issue a statement disputing the researcher's account",
              r: "The researcher has screenshots and timestamps. Disputing them makes it worse.",
              w: "Arguing with a documented, accurate report deepens the credibility hole." },
            { q: 0, t: "Stay quiet and hope the story blows over",
              r: "It does not blow over while the data is still exposed and the regulator is now reading along.",
              w: "Silence during an active public exposure reads as negligence." } ] },

        { id: "ex2", ph: "ident", kc: "actions", att: ["T1530"],
          obs: "Access logs on the open store showed other unknown clients pulling large volumes of records before you were told.",
          title: "Who else was here",
          text: "You've confirmed it's real and it's yours: a database backup on a misconfigured storage bucket, world-readable. The critical question for the breach assessment is whether anyone other than the researcher accessed it. How do you find out?",
          art: "Storage: bucket ACL 'AllUsers: READ'  object backups/crm-2026.sql.gz  2.3M rows\nAccess logs: multiple source IPs, large GET volumes, over ~8 months",
          disc: "If a storage bucket were exposed for months, would you have the access logs to tell who read it? Are they even switched on?",
          opts: [
            { q: 3, u: ["logs"], t: "Pull the access logs: who read it, how much, how long",
              r: "The logs show reads from several unknown sources over months, including bulk downloads. This is an access, not just an exposure.",
              f: "Access logging was only enabled three months ago. You have partial coverage and have to reason about the earlier gap.",
              w: "The access logs turn 'exposed' into 'accessed'. Who read it, how much and for how long drives the entire breach assessment." },
            { q: 2, t: "Assume the researcher was the only one who found it and scope to that",
              r: "The logs later show many others did. Scoping to the friendly finder understated the breach.",
              w: "The reporter you heard from is rarely the only one who found an internet-exposed store." },
            { q: 1, t: "Estimate exposure from how long the bucket was misconfigured",
              r: "Duration bounds the risk but doesn't tell you what was actually taken.",
              w: "Exposure window is context; access logs are evidence. Use the logs where you have them." },
            { q: 0, t: "Assume no one accessed it because the data hasn't appeared anywhere yet",
              r: "It hasn't appeared yet. Stolen data often sits before it surfaces.",
              w: "Data not yet seen for sale is not data that wasn't taken." } ] },

        { id: "ex3", ph: "contain", kc: "actions",
          title: "Close it without breaking it",
          text: "The store needs locking down now, but the access logs are your only evidence of what happened. How do you contain?",
          disc: "Could you make an exposed store private in minutes while preserving its access logs as evidence?",
          opts: [
            { q: 3, t: "Remove public access, preserve the object and logs",
              r: "Public read is revoked, the data is no longer reachable, and the object and logs are preserved for the investigation.",
              w: "Cut the public access immediately, but preserve the data and especially the access logs. They are the whole evidential record." },
            { q: 2, t: "Delete the exposed backup entirely so it can't be reached again",
              r: "The exposure is gone, and so is the evidence of what was in it and who touched it.",
              w: "Deleting closes the hole but destroys the record you need to assess and notify accurately." },
            { q: 1, t: "Move the bucket to a new name and leave the old one for now",
              r: "The old public object may still be cached and indexed. Half a fix.",
              w: "Renaming doesn't reliably remove public access or cached copies. Revoke the access directly." },
            { q: 0, t: "Leave it up while you investigate so you don't disturb anything",
              r: "Every hour it stays public is more records leaving.",
              w: "You never leave a live exposure open to preserve tidiness. Close it, carefully." } ] },

        { id: "ex4", ph: "contain", kc: "actions", att: ["T1213"],
          obs: "The exposed backup held names, contact details and account information for millions of customers.",
          title: "Is this a breach",
          text: "The access logs show bulk reads by unknown parties. The data is customer personal information at scale. The organisation has to decide, formally, whether this is a notifiable breach. How do you handle that?",
          disc: "Who in your organisation makes the notifiable-breach call, and does the clock start at exposure or at discovery?",
          opts: [
            { q: 3, t: "Run the formal breach assessment with the DPO now",
              r: "The DPO leads the assessment. With confirmed third-party access to personal data at scale, it clearly meets the bar and the clock is managed.",
              w: "Confirmed unauthorised access to personal data at scale is a notifiable breach. Assess formally with the DPO and legal without delay." },
            { q: 2, t: "Wait for a full forensic timeline before deciding on notification",
              r: "The forensics take weeks. The notification deadline is measured in hours from awareness.",
              w: "You assess and, if needed, notify on the evidence you have. The clock doesn't wait for perfect forensics." },
            { q: 1, t: "Treat it as exposure only, not access, to avoid triggering notification",
              r: "The access logs already show reads. Framing it as mere exposure won't survive scrutiny.",
              w: "Where logs show access, calling it exposure-only is wishful and risky." },
            { q: 0, t: "Decide quietly not to notify and hope it never surfaces",
              r: "The researcher, the journalist and the log evidence all still exist.",
              w: "Choosing not to notify a qualifying breach is the decision that turns an incident into a scandal." } ] },

        { id: "ex5", ph: "erad", kc: "actions",
          title: "Why was it open",
          text: "Root cause: the bucket was created for a one-off task and never secured, then quietly used for real backups. You need to be sure this is the only one. How do you approach it?",
          disc: "How many storage buckets, databases and shares does your organisation have exposed to the internet right now? Could you list them today?",
          opts: [
            { q: 3, t: "Fix the misconfiguration and scan the estate for others",
              r: "The bucket is corrected and a posture scan across the estate finds two more risky configurations before anyone else does.",
              w: "One exposed store means the process that creates them is flawed. Fix this one and hunt the estate for the same mistake." },
            { q: 2, t: "Secure this bucket and remind teams to check their own configurations",
              r: "This one is fixed. The reminder finds the diligent and misses the rest.",
              w: "A reminder isn't a scan. Actively find the other exposures rather than asking people to look." },
            { q: 1, t: "Add a policy that new buckets must be private",
              r: "Good for the future, silent about what's already exposed today.",
              w: "Policy prevents new mistakes but doesn't discover the existing ones. Scan as well." },
            { q: 0, t: "Assume it was a unique one-off and close the investigation",
              r: "The same casual process created several buckets over the years.",
              w: "A recurring process rarely goes wrong exactly once. Verify." } ] },

        { id: "ex6", ph: "recover", kc: "actions", at: 20.0,
          title: "Telling people",
          text: "It's a notifiable breach affecting millions. Regulators, customers and the press all need handling, and how you treat the researcher is part of the story. What's your approach?",
          disc: "When you notify millions of customers, what do they actually need to hear, and what would a bug bounty have cost compared to this?",
          opts: [
            { q: 3, t: "Notify the regulator and customers on time, credit the researcher",
              r: "Timely, plain-language notifications go out, guidance is given to customers, and the researcher is credited rather than blamed.",
              w: "Notify accurately and on time, tell people what to do, and treat the reporter as the ally they were. It's the right thing and it reads well." },
            { q: 2, t: "Notify the regulator but delay customer notice until the investigation fully closes",
              r: "The regulator is informed, but customers hear it from the news first.",
              w: "Affected people generally need to be told promptly too, not only the regulator." },
            { q: 1, t: "Issue a vague statement about a 'technical issue' with no specifics",
              r: "Vagueness erodes trust and invites the press to fill in the blanks.",
              w: "Under-informing during a real breach damages credibility and rarely holds." },
            { q: 0, t: "Send the researcher a legal letter to discourage them from talking",
              r: "It becomes the story, and it chills the next person who might have warned you.",
              w: "Legal threats against good-faith reporters are both wrong and self-defeating." } ] },

        { id: "ex7", ph: "recover", kc: "actions", at: 44.0,
          title: "A front door for reports",
          text: "This time a researcher chose to email quietly. Next time they might not know how, or might go straight to the press. What goes into the wrap-up?",
          disc: "If someone finds a hole in your systems tomorrow, is there an obvious, safe way for them to tell you?",
          opts: [
            { q: 3, t: "Publish a disclosure policy and add posture monitoring",
              r: "Reporters now have a clear, safe channel, and automated monitoring flags exposures before strangers email about them.",
              w: "Give finders a front door with a disclosure policy, and add continuous posture monitoring so you find exposures first." },
            { q: 2, t: "Set up a security email address and monitor it",
              r: "A contact is better than none, without a policy people still won't know the rules of engagement.",
              w: "A mailbox helps, but a stated disclosure policy is what makes reporters comfortable and defines expectations." },
            { q: 1, t: "Rely on the annual penetration test to catch future exposures",
              r: "A point-in-time test won't catch a bucket someone opens next month.",
              w: "Annual testing misses exposures that appear between tests. Continuous monitoring closes that gap." },
            { q: 0, t: "Consider the matter closed now that this bucket is fixed",
              r: "The next casual bucket is one busy afternoon away.",
              w: "Without a process and monitoring, this recurs. Fixing one bucket isn't the lesson." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1567", "T1657"],
        obs: "The exposed records were scraped in bulk and advertised for sale, with an extortion demand following.",
        title: "For sale",
        text: "While the response was still forming, the data was scraped and a post appears offering 2.3 million records for sale, followed by an email demanding payment to 'take it down'. The exposure is now an extortion.",
        opts: [
            { q: 3, u: ["retainer", "plan"], t: "Lock it, preserve evidence, escalate, don't pay",
              r: "The exposure is closed, the sale post and demand are preserved as evidence, and legal and the regulator are engaged. No payment is made.",
              w: "Once it's for sale, secure and preserve, escalate to legal and the regulator, and don't pay: the data is already copied and payment guarantees nothing." },
            { q: 2, t: "Focus everything on getting the sale listing taken down",
              r: "Takedowns help at the edges, but the data is already in many hands.",
              w: "Chasing listings is worth doing but won't recall copied data. Prioritise notification and evidence." },
            { q: 0, t: "Pay the demand quietly to stop the data being sold",
              r: "Payment doesn't delete copies, invites repeat demands, and now there's a payment to explain too.",
              w: "Paying an extortionist for already-copied data buys nothing and adds legal and sanctions exposure." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline improvement after millions of records sat open on the internet. What do you push?",
        opts: [
            { q: 3, t: "Posture management and asset inventory",
              w: "It breaks the chain at the source: you know what you have, exposures are caught automatically, and new stores are private by default." },
            { q: 2, t: "Encrypt all backups at rest",
              w: "Worth doing, but an exposed bucket often hands over the keys too. Not knowing the bucket existed was the real failure." },
            { q: 1, t: "Run more frequent penetration tests",
              w: "Point-in-time tests miss exposures that appear between them. Continuous posture monitoring fits the risk better." },
            { q: 0, t: "Ban the use of cloud storage for backups",
              w: "The issue was configuration and inventory, not the cloud. A blanket ban gets quietly ignored." } ] }
});
