/* ================= DATA: INJECTS ==============================================
   kind "q" = quirky, "s" = serious. ph limits which phases an inject can appear in.
   tag limits it to scenarios with that tag. cond(run) is an optional extra test.
   ========================================================================== */

const MID = ["ident", "contain", "erad", "recover"];
const LATE = ["contain", "erad", "recover"];

const INJ = [
    /* ---------- quirky ---------- */
    { id: "q_rat", kind: "q", ph: LATE, title: "Rodent-based outage",
      text: "The link to {site}, where your offsite backup copies live, has dropped. Facilities report a rat has chewed through the fibre in the cable duct. The rat is 'no longer with us'.",
      opts: [
        { q: 3, u: ["backup"], t: "Switch to the secondary backup copy and get the carrier on an emergency splice",
          r: "Secondary copy online. The splice is done by morning, with a new rodent guard.",
          f: "The secondary copy exists, but the decryption key is in a password manager on a laptop at {site}.",
          w: "Resilience means more than one backup path. 3-2-1-1-0 exists for exactly this." },
        { q: 2, t: "Log it with the carrier and carry on, the offsite copies won't be needed for the next few hours",
          r: "Carrier SLA is 8 hours. The rat's colleagues are unavailable for comment.",
          w: "Waiting is fine if those backups aren't on the critical path. Know which ones are." },
        { q: 0, t: "Drive the backup NAS from {site} to head office yourself so the data is where you need it",
          r: "It fits in the boot. Chain of custody does not. It was also still mid-sync.",
          w: "Moving storage mid-incident without a process risks data, evidence and your back." } ] },

    { id: "q_bbq", kind: "q", ph: LATE, title: "The server room is having a barbecue",
      text: "Temperature alarms. The server room is at 41C. The air conditioning failed hours ago and nobody noticed, because the monitoring VM was on a host you isolated earlier.",
      opts: [
        { q: 3, t: "Shut down non-critical kit, get emergency cooling and move monitoring off that host",
          r: "Back to 24C within the hour. Two old switches are slightly crispy but alive.",
          w: "Monitoring is a dependency too. Know what your containment actions will knock out." },
        { q: 1, t: "Prop the server room door open and set up a couple of big fans to push the heat out while you wait",
          r: "The fan helps a little. The fire extinguisher is technically now in use.",
          w: "Improvised fixes buy minutes, not hours, and open a physical security gap." },
        { q: 0, t: "Leave it to facilities to sort out, your whole focus needs to stay on the incident right now",
          r: "A RAID controller cooks itself. Now you have two incidents.",
          w: "Environmental alarms during an incident still need an owner." } ] },

    { id: "q_nephew", kind: "q", ph: MID, title: "The helpful nephew",
      text: "{ceo}'s nephew is 'really good with computers' and has offered to help. He's already standing in the war room holding a USB stick.",
      opts: [
        { q: 3, t: "Thank him, keep his USB stick away from everything and put him on food runs",
          r: "He's an excellent runner and morale improves. The USB stick held a cracked 'virus cleaner'.",
          w: "Keep the response to trained people with defined roles. Unknown media never touches incident systems." },
        { q: 1, t: "Let him run his cleaning tool on one spare laptop, it can't hurt and it keeps him occupied",
          r: "It installs three browser toolbars and a crypto miner. You have an extra host to investigate.",
          w: "Uncontrolled tools contaminate evidence and add malware." },
        { q: 0, t: "Give him a temporary admin account so he can help the team work through the backlog faster",
          r: "He resets the password on the account you were watching. Evidence trail gone.",
          w: "Privilege goes to people with a role in the plan, not people in the room." } ] },

    { id: "q_lanzarote", kind: "q", ph: LATE, title: "The firewall whisperer",
      text: "You need a firewall change. The only person with the admin password is {admin}, currently on a flight to Lanzarote. A colleague says it's 'in the notebook marked NOT PASSWORDS'.",
      opts: [
        { q: 3, u: ["plan"], t: "Use the sealed break-glass account from the safe, log it and rotate it afterwards",
          r: "Envelope opened, change made, use logged. Very boring. Exactly right.",
          f: "The envelope exists. The password inside was rotated in 2023 and nobody updated the envelope. You end up in the notebook anyway.",
          w: "Break-glass access has to exist, be tested and be audited. Single points of human failure are common and preventable." },
        { q: 1, t: "Find the notebook, make the change, and ask {admin} to change the password when they land",
          r: "It's a sticky note on the monitor. It also has the Wi-Fi password and a bank PIN.",
          w: "Works today, becomes an audit finding tomorrow. Credentials belong in a vault." },
        { q: 0, t: "Wait for {admin} to land, they know the firewall best and won't make mistakes under pressure",
          r: "Four hours in the air, then an hour of the phone looking for signal.",
          w: "Key-person dependencies stall responses at the worst moment." } ] },

    { id: "q_printer", kind: "q", ph: LATE, tag: "ransomware", title: "Print nightmare",
      text: "The printer on the 3rd floor has started printing the same page over and over. It's a message from the attackers. Staff are gathering round it taking photos.",
      opts: [
        { q: 3, t: "Pull it off the network, keep one copy as evidence and send staff a short honest note",
          r: "Printer isolated. One photo reached a WhatsApp group, but the internal note calms things down.",
          w: "Visible attacker messages are pressure tactics. Preserve evidence, stop the display, get ahead of the gossip." },
        { q: 1, t: "Leave it printing, every page is evidence and unplugging it could alert the attackers",
          r: "2,400 copies later the evidence has used all the toner.",
          w: "One copy is evidence. The rest is a morale problem." },
        { q: 0, t: "Tell staff it's a printer driver fault to keep people calm while you deal with it",
          r: "The page says THIS IS NOT A DRIVER BUG in large letters.",
          w: "Don't mislead staff. Short, honest internal comms beat rumour." } ] },

    { id: "q_cab", kind: "q", ph: LATE, title: "Please raise a CAB ticket",
      text: "The change manager has rejected your emergency firewall block: 'All changes need five working days' notice and a CAB review. No exceptions.'",
      opts: [
        { q: 3, u: ["plan"], t: "Use the IR plan's emergency change route and file the change record afterwards",
          r: "Approved in six minutes. The retrospective ticket is filed. The change manager is satisfied, if not happy.",
          f: "There is no emergency change process. You escalate to the CIO, who approves it by text 40 minutes later.",
          w: "Change control shouldn't be bypassed, it should have a fast lane agreed before the incident." },
        { q: 1, t: "Make the change quietly and sort out the paperwork with the change manager next week",
          r: "It works. On Monday the change manager reverts it as unauthorised.",
          w: "Undocumented changes get undone and confuse the investigation timeline." },
        { q: 0, t: "Raise the CAB ticket properly and wait, change control exists to stop outages like this",
          r: "CAB meets on Thursday. The attacker is not on the CAB distribution list.",
          w: "Standard change timescales don't fit incident timescales." } ] },

    { id: "q_fatigue", kind: "q", ph: LATE, title: "Running on fumes",
      text: "It's the middle of the night and the team has been up for 20 hours. {admin} is about to run a 180-line firewall change and their eyes are closing.",
      opts: [
        { q: 3, t: "Rotate in a fresh shift with a written handover and send the tired crew home",
          r: "The fresh shift spots a typo in line 142 that would have blocked the payment gateway.",
          w: "Fatigue causes errors. Plan shifts from hour one of a major incident, not hour twenty." },
        { q: 1, t: "Keep the current crew on, they have the context and a handover would waste precious time",
          r: "The change goes in with a typo that blocks the payment gateway until morning.",
          w: "Heroics feel productive and raise error rates." },
        { q: 0, t: "Order energy drinks and give the team a pep talk, they only need to get through tonight",
          r: "The speech lands well with the two people still awake.",
          w: "Motivation doesn't replace sleep." } ] },

    { id: "q_pizza", kind: "q", ph: MID, title: "Pizza incident",
      text: "The war room's 30 pizzas were delivered to {site}, 80 km away. The security guard there is having the best night of his life.",
      opts: [
        { q: 3, t: "Reorder, and schedule proper breaks and meals for the team from now on",
          r: "Food arrives, people eat, and the next few hours are noticeably sharper.",
          w: "Welfare is part of incident management. Hungry, tired responders make mistakes." },
        { q: 1, t: "Skip the food and keep going, there's no time to stop until containment is done",
          r: "Two hours later two engineers are arguing over a timestamp.",
          w: "Skipping basics costs more time than it saves." } ] },

    { id: "q_hoover", kind: "q", ph: MID, title: "Unplanned maintenance",
      text: "The core switch in the comms room just went offline. A contract cleaner needed a socket for the hoover.",
      opts: [
        { q: 3, t: "Restore it, log it as non-malicious in the timeline and lock the comms room",
          r: "Back in 12 minutes. The timeline entry saves an analyst an hour chasing a 'suspicious outage' later.",
          w: "Record non-malicious events in the timeline, or they get misread as attacker activity. And physical security still matters." },
        { q: 1, t: "Treat it as possible attacker activity and escalate, you can't rule anything out right now",
          r: "An hour of panic. Then someone finds the hoover.",
          w: "Verify before escalating. Correlation is not causation." } ] },

    { id: "q_jazz", kind: "q", ph: MID, title: "Your call is important to us",
      text: "You need urgent help from a key vendor. Their support line has played the same smooth jazz loop for 50 minutes.",
      opts: [
        { q: 3, u: ["plan", "retainer"], t: "Escalate through the emergency contacts listed in the IR plan",
          r: "A senior engineer calls back within 15 minutes.",
          f: "The emergency number in the IR plan belongs to an account manager who left in 2024. The new one picks up eventually.",
          w: "Keep vendor emergency contacts in the IR plan and check them every quarter." },
        { q: 1, t: "Keep holding, hanging up means going to the back of the queue and losing your place",
          r: "The jazz takes a saxophone solo. It's quite good, actually. Another 40 minutes pass.",
          w: "Don't let a queue set your timeline. Have escalation paths." },
        { q: 0, t: "Post about it on social media, vendors respond faster when complaints are public",
          r: "Their social team offers to help by DM within two working days. You've also announced you have an incident.",
          w: "Public complaints mid-incident can disclose the incident itself." } ] },

    { id: "q_selfie", kind: "q", ph: MID, title: "Say cheese",
      text: "Someone from marketing posted a 'late night with the team!' selfie on LinkedIn. The whiteboard behind them reads 'RANSOMWARE??' and shows half your IOC list.",
      opts: [
        { q: 3, t: "Get it deleted quietly, brief comms and remind staff of the confidentiality rules",
          r: "Deleted after 14 views. Comms prepares a holding line just in case.",
          w: "Incident comms includes internal comms. Staff need to know what not to share, and why." },
        { q: 1, t: "Leave it, deleting it now would draw more attention than the post itself",
          r: "A journalist does.",
          w: "Assume anything posted publicly will be found." },
        { q: 0, t: "Comment on the post asking them to take it down, so it's handled publicly and straight away",
          r: "Your public comment gets more views than the post.",
          w: "Handle it privately." } ] },

    { id: "q_licence", kind: "q", ph: MID, title: "Licence to chill",
      text: "The EDR console shows a banner: licence expired at midnight. Isolation actions are greyed out.",
      cond: run => run.posture.edr > 0,
      opts: [
        { q: 3, t: "Get an emergency extension from the vendor and isolate at the switch port meanwhile",
          r: "The vendor grants a 30-day emergency extension within an hour. Switch-port isolation holds in the meantime.",
          w: "Have alternative containment methods ready, and track security tool renewals like certificates." },
        { q: 1, t: "Ask procurement to raise a purchase order for the renewal as a matter of urgency",
          r: "Procurement opens at 09:00 and needs three quotes.",
          w: "Procurement timescales and incident timescales don't mix." } ] },

    { id: "q_emptybackup", kind: "q", ph: LATE, title: "Nine months of nothing",
      text: "Checking backups, the backup admin goes pale. The file server job has reported 'Success' every night for nine months. It has been backing up an empty folder since a path change.",
      opts: [
        { q: 3, u: ["backup"], t: "Find the next best source, fix the job and add restore testing to the plan",
          r: "Storage snapshots cover most of it. Restore testing goes on the lessons list in red.",
          f: "The array snapshots only go back 48 hours. Some older files are gone for good.",
          w: "A backup isn't a backup until you've restored from it. Monitor size and content, not just 'Success'." },
        { q: 1, t: "Fix the job quietly tonight and only escalate it if a restore is actually needed",
          r: "It's needed the next day.",
          w: "Bad news early changes recovery plans. Bad news late ruins them." } ] },

    { id: "q_badge", kind: "q", ph: MID, title: "Locked out of your own building",
      text: "Your badge stops working at the side door. The door access server was on the network segment you just isolated.",
      opts: [
        { q: 3, t: "Use the manual override and have facilities check which doors failed open",
          r: "Security let you in with a key. Two fire doors had failed open. Now fixed and logged.",
          w: "Physical systems share your network. Know which ones containment will affect and whether they fail open or closed." },
        { q: 1, t: "Prop the side door open so the team can get in and out without badges",
          r: "The door stays propped open until Monday. So does the building.",
          w: "Workarounds become the next vulnerability." } ] },

    { id: "q_dns", kind: "q", ph: LATE, title: "It's always DNS",
      text: "Half the company can't reach anything, yet monitoring shows every server up. After an hour of puzzled faces: one of your containment firewall rules also blocked the internal DNS servers.",
      opts: [
        { q: 3, t: "Fix the rule, log it, and add a dependency check to the containment playbook",
          r: "Fixed in minutes once found. The playbook gains a 'what else uses this path' step.",
          w: "Containment changes have side effects. Map dependencies before blocking and log every change so it can be traced." },
        { q: 1, t: "Roll back all of today's containment rules until you find which one did it",
          r: "Everything works again, including the attacker's access.",
          w: "Roll back selectively. Never undo containment wholesale." },
        { q: 0, t: "Put the outage down to the attacker in the next status update",
          r: "The post-incident review finds the rule. Awkward.",
          w: "Honest status updates, including your own mistakes, maintain trust." } ] },

    { id: "q_autoreply", kind: "q", ph: MID, title: "Thank you for your email",
      text: "A regulator emailed the security mailbox about the incident and got an auto-reply: 'Thanks for contacting IT support. Our response time is 5 working days. Have you tried turning it off and on again?'",
      opts: [
        { q: 3, t: "Phone them to apologise, give them a named contact and fix the mailbox routing",
          r: "The regulator laughs, mostly. A named contact is agreed.",
          w: "Regulators and partners need a named, monitored contact during an incident." },
        { q: 1, t: "Reply from the same mailbox with a formal apology and an update",
          r: "Your reply triggers the auto-reply again.",
          w: "Fix the channel before using it." } ] },

    /* ---------- serious ---------- */
    { id: "s_customer", kind: "s", ph: LATE, title: "Your biggest customer is worried",
      text: "A major customer's security team emails: they've heard about the incident and want a written update within two hours, or they'll cut their network and API connections to {org}.",
      opts: [
        { q: 3, t: "Send a named contact, facts, indicators and the next update time, cleared with legal",
          r: "They keep the connection open and ask to be kept in the loop.",
          w: "Partners have their own risk to manage. Timely, factual updates keep relationships and connections intact." },
        { q: 2, t: "Send them the same holding statement that went to the press, it's already been approved",
          r: "They cut the API connection until Monday.",
          w: "Partners need more than the press: indicators, scope and what it means for them." },
        { q: 0, t: "Hold off replying until the incident is fully closed",
          r: "They cut the connection and raise it with their board.",
          w: "Silence with partners reads as either chaos or concealment." } ] },

    { id: "s_press", kind: "s", ph: LATE, title: "A journalist calls",
      text: "A reporter from a national news site calls your mobile. They've had a tip about a cyber incident at {org} and are publishing in an hour, with or without comment.",
      opts: [
        { q: 3, u: ["plan"], t: "Pass them to {comms} for the pre-approved holding statement",
          r: "{comms} has the holding statement out in 40 minutes. The story is short and factual.",
          f: "There is no pre-approved holding statement. {comms} drafts one with legal and misses the deadline by 10 minutes.",
          w: "Route media through comms. A holding statement acknowledges, reassures and commits to updates without speculating." },
        { q: 2, t: "Politely say 'no comment' and end the call, you can't discuss an active investigation",
          r: "The article says {org} 'declined to comment'. It reads like a cover-up.",
          w: "No comment is a comment. A short factual holding statement is better." },
        { q: 0, t: "Brief them off the record so the story is at least accurate when it's published",
          r: "It appears as 'a source close to the investigation said the attackers had domain admin'.",
          w: "Nothing is off the record in an incident. Only authorised spokespeople speak." } ] },

    { id: "s_dpo", kind: "s", ph: LATE, tag: "pii", title: "The regulatory clock",
      text: "{dpo}, the DPO, asks: 'Is this notifiable? We've been aware for {elapsed} hours.' Personal data may be involved.",
      opts: [
        { q: 3, t: "Assess it now and notify within 72 hours with what you know, then update",
          r: "A preliminary notification is filed. The authority acknowledges and asks for an update in two weeks.",
          w: "GDPR allows notification in phases. The 72-hour clock starts at awareness, not at the end of the investigation." },
        { q: 2, t: "Wait until the investigation is complete so the notification is accurate the first time",
          r: "The investigation takes three weeks. The notification is very accurate and very late.",
          w: "Late notification is its own breach of the rules. Notify early, update later." },
        { q: 0, t: "Only notify if the data actually turns up online, otherwise there's no confirmed harm",
          r: "{dpo} writes a strongly worded note to the file, and to you.",
          w: "The test is risk to individuals, not whether criminals publish." } ] },

    { id: "s_nis2", kind: "s", ph: LATE, title: "NIS2 early warning",
      text: "Legal points out that {org} is in scope of NIS2 as a {sector} business. A significant incident needs an early warning to the national CSIRT within 24 hours of awareness.",
      cond: run => run.ctx.nis2,
      opts: [
        { q: 3, t: "Send the early warning now with the basics, then notify and report on schedule",
          r: "Early warning submitted. The CSIRT offers help and shares indicators from a similar case.",
          w: "NIS2 reporting is staged: early warning within 24 hours, notification within 72 hours, final report within a month. Management bodies carry accountability." },
        { q: 1, t: "Hold off until you know enough to send something meaningful to the CSIRT",
          r: "At hour 30 the CSIRT learns about it from the news. Legal is unhappy.",
          w: "The early warning is designed for incomplete information. Send it." },
        { q: 0, t: "Push back on legal, you're not convinced a {sector} business is really in scope",
          r: "You are. Legal sends you the list.",
          w: "Know your regulatory scope before the incident, not during it." } ] },

    { id: "s_insurer", kind: "s", ph: ["contain", "erad"], title: "Read the small print",
      text: "{fd} has found the cyber insurance policy. It requires notification within 48 hours and use of the insurer's panel IR firm for costs to be covered.",
      opts: [
        { q: 3, u: ["retainer"], t: "Notify the insurer now and engage their panel firm",
          r: "The panel firm joins the bridge. Costs are covered.",
          w: "Insurer obligations belong in the IR plan. Missing them can void cover." },
        { q: 1, t: "Bring in a trusted local security firm you already know, they're cheaper and faster",
          r: "Great people. Not on the panel. The claim is declined.",
          w: "Off-panel responders can void cover. Check before you engage." },
        { q: 0, t: "Focus on the response and deal with the insurer properly once things are stable",
          r: "The notification window closes on day two. So does the cover.",
          w: "Policy notification deadlines are strict." } ] },

    { id: "s_board", kind: "s", ph: LATE, title: "Hourly updates, please",
      text: "A board member wants hourly updates by WhatsApp. Directly from you. With details.",
      opts: [
        { q: 3, t: "Agree a four-hourly brief for all execs through the crisis lead",
          r: "One brief, every four hours, everyone aligned. You get your hours back.",
          w: "Structured updates protect responder time and keep leadership consistently informed." },
        { q: 1, t: "Send the hourly WhatsApp updates, keeping the board happy protects the response",
          r: "Fifteen minutes of every hour goes on updates. They get forwarded to people you've never met.",
          w: "Ad hoc updates fragment attention and leak." },
        { q: 0, t: "Ignore it for now, updating the board is a distraction from the actual response",
          r: "The board member calls {ceo}, who calls you. Loudly.",
          w: "Leadership needs information. Channel it." } ] },

    { id: "s_vish", kind: "s", ph: MID, tag: "identity", title: "They're calling our people",
      text: "Three employees report calls to their personal mobiles from 'IT support', asking them to approve an MFA prompt 'to help fix the incident'.",
      opts: [
        { q: 3, u: ["idp"], t: "Alert all staff out of band that IT never asks for approvals or codes",
          r: "Two more calls are reported within the hour. Nobody approves anything.",
          w: "Attackers exploit incident confusion. Tell staff what legitimate IT will and won't do." },
        { q: 1, t: "Tell the three people to ignore the calls and block the numbers they came from",
          r: "A fourth person, who you didn't tell, approves the prompt.",
          w: "If three got calls, many did. Warn everyone." },
        { q: 0, t: "Assume a colleague is helping with the recovery and tell staff to cooperate with them",
          r: "It isn't. Your IT team is on the bridge with you.",
          w: "Verify every contact during an incident." } ] },

    { id: "s_msp", kind: "s", ph: ["contain", "erad"], title: "Let us just remote in",
      text: "Your MSP offers to help: 'Install our remote tool on the domain controllers and send us the admin password, we'll sort it.'",
      opts: [
        { q: 3, u: ["idp"], t: "Accept help through named accounts, MFA and a logged jump host",
          r: "The MSP's engineers work through the jump host. Everything they do is logged.",
          w: "Third-party access is a common attack path. Keep it controlled even when the help is welcome." },
        { q: 0, t: "Let them install their tool on the DCs, speed matters and they know the environment",
          r: "Their tool works well. So does the attacker's copy of the MSP's credentials, stolen last month.",
          w: "Uncontrolled third-party access during an incident widens the blast radius." } ] },

    { id: "s_police", kind: "s", ph: LATE, title: "Do we call the police?",
      text: "Someone asks whether you should report this to law enforcement and the national cyber security centre.",
      opts: [
        { q: 3, t: "Report to police and the national CSIRT, and share indicators",
          r: "Law enforcement links the infrastructure to a known group and shares extra indicators.",
          w: "Reporting brings intelligence and sometimes recovery, helps everyone else, and is often an insurance or regulatory expectation." },
        { q: 1, t: "Not yet, reporting now risks the incident leaking to the press",
          r: "It doesn't leak. You just miss the indicators they could have shared.",
          w: "Law enforcement handles these discreetly and routinely." } ] },

    { id: "s_ceo", kind: "s", ph: MID, title: "The CEO is on the bridge",
      text: "Confidence is slipping. {ceo} has joined the bridge and is giving technical instructions directly to engineers.",
      cond: run => run.trust < 35,
      opts: [
        { q: 3, fx: { trust: 12 }, t: "Take five minutes one to one to agree roles, status and the decisions needed",
          r: "{ceo} agrees and steps back into the exec crisis role. The bridge calms down.",
          w: "Clear roles restore trust. Executives decide business risk; the IR lead runs the response." },
        { q: 1, t: "Step back and let {ceo} lead, visible leadership from the top reassures everyone",
          r: "{ceo} orders everything rebooted. Twice.",
          w: "Well-meaning leadership without technical context can undo containment." },
        { q: 0, t: "Correct {ceo} on the bridge so the engineers know who is actually running this",
          r: "It's memorable, for the wrong reasons.",
          w: "Disagreements go offline. The bridge needs one voice." } ] }
];
