/* ---------- 6. The new hire ---------- */
SCEN.push({
    id: "newhire", name: "The New Hire",
    blurb: "Your best new developer asks for pay to go to a third bank account. Their laptop logs in from a VPS.",
    tags: ["insider", "pii"], start: [1, 11, 0],
    actor: "A North Korean remote IT worker scheme: operatives using borrowed identities and AI-assisted interviews to get hired, sending wages back to the regime and sometimes stealing data or extorting employers once discovered.",
    sum: "discovered that a remote contractor it had hired was operating under a false identity as part of a state-backed IT worker scheme, with access to source code and customer data",
    escSum: "the worker used stolen source code to extort the company after their access was cut.",
    pre: [
        { kc: "recon", att: "T1591", txt: "Scanned job boards for fully remote engineering roles with access to cloud and data platforms." },
        { kc: "weapon", att: "T1585", txt: "Built a fake identity: a borrowed name, a doctored passport scan, a LinkedIn profile and a GitHub history of lightly modified open-source code." },
        { kc: "delivery", att: "T1656", txt: "Passed four video interviews using a real-time face-swap filter and an AI assistant feeding answers." }
    ],
    intro: "Tuesday, 11:00. Payroll flags something odd: {dev}, a contract data engineer hired eight weeks ago, has asked for their pay to go to a third different bank account. The same morning, the laptop shipped to their home address logs in from a VPS provider with a strange USB device attached. Their manager calls {dev} 'the best hire we've made this year'.",
    nodes: [
        { id: "nh1", ph: "ident", kc: "delivery", att: ["T1656"],
          obs: "An operative posed as a genuine job candidate using a false identity and deepfaked video interviews.",
          title: "Too good to be true",
          text: "Laptop telemetry shows a USB device identifying itself as an IP-KVM, keyboard input at 03:00 local time and mouse movement that doesn't look human. HR's file has a passport scan and a reference from a company that was dissolved last year. What's your first move?",
          art: "EDR  LT-DEV-219  USB attach  'PiKVM HID'  (remote keyboard, video and mouse device)\nEDR  LT-DEV-219  user={devuser}  logon 03:02 local  src=198.51.100.140 (VPS provider)\nHR   Reference: 'Northwind Data Ltd'  company status: dissolved 2025",
          disc: "Who in your organisation would you tell first about a suspected insider, and who must not be told?",
          opts: [
            { q: 3, u: ["logs", "plan"], t: "Quietly preserve evidence and bring in HR, legal and the CISO before anyone alerts {dev}",
              r: "A small cell forms: security, HR and legal. Evidence is captured and nobody tips {dev} off.",
              f: "Legal is at a conference and can't join until 16:00. Meanwhile HR mentions 'a few questions about your bank details' to {dev}.",
              w: "Suspected insider cases need a small need-to-know group from the start. HR and legal shape what you can monitor, how you keep evidence and how you act." },
            { q: 2, set: "warned", t: "Get {dev} on a video call today and ask them to explain the login activity",
              r: "{dev}'s camera 'isn't working'. The call ends quickly and the laptop goes quiet for an hour.",
              w: "Confronting a suspect before preserving evidence and planning the exit gives them time to take what they can." },
            { q: 1, t: "Disable {dev}'s account right now, there's clearly something seriously wrong with this particular hire",
              r: "Access cut. So is your view of what they touched, and they still hold copies of everything they cloned.",
              w: "Cutting access without evidence or a plan loses visibility and creates legal exposure. It's right eventually, but plan it." },
            { q: 0, t: "Leave it with their manager, contractors often run home servers for performance",
              r: "The manager, delighted with {dev}'s output, signs off another month's contract extension.",
              w: "IP-KVM devices, VPS logins and 03:00 activity on a shipped laptop are textbook signs of a remote IT worker scheme." } ] },

        { id: "nh1x", ph: "ident", kc: "actions", if: "warned", enter: { heat: 1, impact: 6 }, att: ["T1567.002"],
          obs: "After being tipped off, the worker began bulk copying code and data to a personal file-sharing account.",
          title: "They know",
          text: "Within an hour of the call, {dev}'s account clones 120 repositories and starts a large export from the data warehouse to a personal cloud storage account.",
          opts: [
            { q: 3, u: ["idp"], t: "Cut every access path now, preserve what's in flight and bring legal in",
              r: "Access is cut 20 minutes in. The warehouse export is killed at 30%.",
              w: "Once a suspect is tipped off, speed beats completeness. Cut access and preserve evidence." },
            { q: 1, t: "Call {dev} back and ask them to stop what they're doing while you talk",
              r: "The call goes to voicemail. The export finishes.",
              w: "You can't negotiate with an active insider mid-exfiltration." } ] },

        { id: "nh2", ph: "ident", kc: "install", att: ["T1219.003"],
          obs: "The worker used an IP-KVM device plugged into the laptop to drive it from abroad.",
          title: "Where is the laptop, really?",
          text: "EDR's Wi-Fi data shows the laptop sitting among dozens of other corporate devices, several named with other companies' naming schemes. It's a laptop farm: a facilitator in the UK keeps them powered and plugged into IP-KVMs for workers overseas. What next?",
          opts: [
            { q: 3, u: ["logs"], t: "Pull everything {dev}'s identity touched: repos, data, cloud consoles, tickets",
              r: "Eight weeks of activity: 40 repos cloned, read access to the customer analytics warehouse, and an unapproved tool on two cloud VMs.",
              w: "Laptop farms let overseas workers appear local. Scope everything the identity touched, because the access was legitimate and no alerts fired." },
            { q: 2, t: "Report the laptop farm address to the police so they can raid it and seize the laptops",
              r: "The police take a report and it joins a queue of similar cases. You still don't know what {dev} accessed.",
              w: "Law enforcement engagement is right, but it doesn't replace scoping what the identity accessed." },
            { q: 1, t: "Remotely wipe the laptop now so whoever has it can't reach company data",
              r: "The laptop wipes. The evidence on it goes too, and the cloud sessions are untouched.",
              w: "Wiping destroys evidence and doesn't touch cloud sessions, tokens or cloned repos." },
            { q: 0, t: "Ask {dev} to send a photo of their home workspace to prove where they are",
              r: "They send a lovely photo of a tidy desk in Leeds. It's a stock image.",
              w: "Anything the suspect can fabricate isn't verification." } ] },

        { id: "nh3", ph: "contain", kc: "actions", att: ["T1213.003"],
          obs: "The worker copied down dozens of internal Git projects.",
          title: "Planning the exit",
          text: "Evidence is preserved. {dev} still has access to the Git server, the data warehouse and two cloud VMs. Legal confirms you can terminate. How do you do it?",
          disc: "If you had to cut every access path a contractor has in one move, could you list them all?",
          opts: [
            { q: 3, u: ["idp", "plan"], t: "Cut every access path at once, then have HR tell {dev}",
              r: "Tokens, keys, VMs and repo permissions all go at 14:00. HR calls {dev} at 14:05. There's nothing left to grab.",
              f: "Everything is revoked except a personal access token on GitHub nobody knew about. It's used once at 14:11 before you catch it.",
              w: "Revoke all access at the same moment, before the conversation: accounts, tokens, SSH and API keys, cloud roles, devices. The moment they're told, they'll reach for what's left." },
            { q: 2, t: "Disable the directory account and let HR handle the conversation this afternoon",
              r: "The directory account is off. The personal access token and the cloud VM keys are not.",
              w: "Directory accounts are one path. Tokens and keys live elsewhere and survive an account disable." },
            { q: 1, t: "Give {dev} the two weeks' notice the contract requires, to avoid a legal dispute",
              r: "In two weeks, {dev} clones every remaining repo and dumps the warehouse's customer tables.",
              w: "Contract terms matter, but legal can advise on removing access immediately while the process runs." },
            { q: 0, t: "Keep them on for now and feed them fake data to gather intelligence",
              r: "They spot the fake data within a day and move straight to extortion.",
              w: "Deception operations need specialists and legal sign-off. Keeping a sanctioned state operative on the payroll is its own problem." } ] },

        { id: "nh4", ph: "contain", kc: "actions",
          title: "You've been paying them",
          text: "Legal raises the uncomfortable part: {org} has paid {dev} eight weeks of wages, some of which has almost certainly gone to a sanctioned regime. What now?",
          opts: [
            { q: 3, t: "Stop payments, preserve the records and take advice on sanctions disclosure",
              r: "Payments are frozen. Legal prepares a voluntary disclosure to the sanctions authority and a report to police.",
              w: "Unknowingly paying a sanctioned state is a legal problem. Stop the money, keep the evidence and let legal manage disclosure." },
            { q: 2, t: "Stop the payments and close the contract quietly, the amounts involved are small",
              r: "Payments stop. So does your chance to show you disclosed it promptly.",
              w: "Voluntary disclosure is usually treated far more favourably than being discovered later." },
            { q: 1, t: "Pay the final invoice anyway so they have no reason to retaliate",
              r: "The payment goes to the third bank account. It's now a sanctions breach you knew about.",
              w: "Paying after discovery turns an innocent mistake into a deliberate breach." },
            { q: 0, t: "Ask the staffing agency to deal with it, they supplied {dev} in the first place",
              r: "The agency's director is 'looking into it'. Friday's payment run goes out as usual.",
              w: "Your payments, your obligation. Work with the agency, but own the response." } ] },

        { id: "nh5", ph: "erad", kc: "install", att: ["T1098.004"],
          obs: "The worker added their own SSH keys to cloud VMs to keep access.",
          title: "What did they leave behind?",
          text: "The investigation finds {dev} added SSH keys to six cloud VMs, created a warehouse service account called 'etl-sync' and pushed two commits to a build script that nobody reviewed.",
          opts: [
            { q: 3, u: ["edr", "logs"], t: "Remove the keys and account, review all their commits, rotate secrets they saw",
              r: "One commit adds an obfuscated call to an external URL in the build script. Caught before it ships.",
              f: "Reviewing 40 repos takes three days. The build script change reached one release candidate before you found it.",
              w: "Insiders leave persistence where only they'd know to look. Review their code like an attacker's, and rotate every secret they could read." },
            { q: 2, t: "Remove the SSH keys and the etl-sync account, then close the investigation",
              r: "Cleaner. The unreviewed build script change ships in Thursday's release.",
              w: "Code contributions are part of an insider's footprint. Review them." },
            { q: 1, t: "Rebuild the six cloud VMs from golden images to remove anything they installed",
              r: "The VMs are clean. The warehouse account and the build script change aren't on them.",
              w: "Rebuilding hosts misses identity and code-level persistence." },
            { q: 0, t: "Leave their code in place, it passed every automated test in the pipeline",
              r: "The tests don't check whether a build script phones home.",
              w: "Passing tests measure function, not intent." } ] },

        { id: "nh6", ph: "recover", kc: "actions",
          title: "Could it happen again?",
          text: "HR asks how {dev} got through hiring. The honest answer: four video interviews, a background check that only confirmed the name existed, and a laptop shipped to an address nobody verified.",
          opts: [
            { q: 3, t: "Verified ID checks for remote hires, validated shipping addresses, alerts on KVMs",
              r: "The next remote hire does a verified ID check at a partner office. Two applicants withdraw when asked.",
              w: "Controls at hiring, device shipping and the endpoint together make this scheme much harder." },
            { q: 2, t: "Require camera-on video interviews with HR present for every single future developer hire",
              r: "The next deepfake is better lit.",
              w: "Real-time face-swaps already beat camera-on interviews. Identity needs verifying, not just seeing." },
            { q: 1, t: "Stop hiring remote contractors altogether and require office attendance",
              r: "Hiring slows to a crawl and two strong candidates go elsewhere.",
              w: "An overcorrection. Verified identity is the control, not location." },
            { q: 0, t: "Rely on the staffing agency's vetting, they've promised to be more careful",
              r: "The agency's vetting turns out to be a checkbox on a web form.",
              w: "Outsourcing vetting doesn't outsource the risk." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1657"],
        obs: "After being cut off, the worker threatened to leak stolen source code unless paid.",
        title: "The former employee",
        text: "An email from a new address: 'I have 40 of your repositories and your customer analytics tables. 300,000 USD in crypto or it all goes public, starting with your API keys.' It's signed {dev}.",
        opts: [
            { q: 3, u: ["retainer", "plan"], t: "Rotate every secret in the stolen code, involve police and legal, don't engage",
              r: "Every key in those repos is dead by evening. When the code leaks, it's worth far less.",
              w: "Extortion power comes from what stolen data can still do. Rotate the secrets, involve law enforcement, and never pay a sanctioned actor." },
            { q: 2, t: "Scan the stolen repos for secrets and rotate the ones rated critical by the scanner",
              r: "Critical keys rotated. A 'low severity' test key turns out to reach production.",
              w: "Rotate everything in stolen code. Scanner severity isn't a risk assessment." },
            { q: 0, t: "Negotiate a smaller payment to make the problem go away quietly",
              r: "A payment to a sanctioned regime, no guarantee, and they're back a month later.",
              w: "Paying a DPRK operative is a sanctions breach and funds the programme." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline fix. What is it?",
        opts: [
            { q: 3, t: "Verified-identity hiring, device controls and least privilege for new joiners",
              w: "It breaks the scheme at hiring, at the laptop and at the level of access a new contractor gets." },
            { q: 2, t: "Use a premium background screening provider for every future hire",
              w: "Useful, but these schemes use real stolen identities that pass name checks." },
            { q: 1, t: "Run an insider threat awareness session for every people manager",
              w: "The manager thought {dev} was brilliant. Awareness alone doesn't beat a skilled operative." },
            { q: 0, t: "Add a clause to contractor agreements that bans using a false identity",
              w: "State-backed operatives are not deterred by contract clauses." } ] }
});

/* ---------- 7. Dependency hell ---------- */
SCEN.push({
    id: "supply", name: "Dependency Hell",
    blurb: "A routine npm install brings a worm. By breakfast it has published a new version of your SDK.",
    tags: ["supply", "dev"], start: [3, 8, 45], orgs: ["Vantage Software", "Fieldline Analytics"],
    actor: "A self-replicating npm worm campaign: trojanised package versions that steal developer and CI secrets, then use stolen publishing tokens to infect more packages. Campaigns like this hit hundreds of npm packages in 2025.",
    sum: "was hit by a self-replicating npm worm that stole developer and CI secrets and used them to publish a trojanised version of its own SDK",
    escSum: "the trojanised SDK spread into a major customer's build systems and the story hit the news.",
    pre: [
        { kc: "recon", att: "T1589", txt: "Harvested npm maintainers' email addresses from public package metadata." },
        { kc: "weapon", att: "T1608.001", txt: "Phished a maintainer and published a trojanised version of a small, widely used utility package with a postinstall script." }
    ],
    intro: "Thursday, 08:45. A developer posts in the engineering channel: their GitHub account has a new public repository called 'migration-dump' that they didn't create, full of base64 JSON. Ten minutes later a security researcher emails: {org}'s npm package @{orgslug}/sdk has just published version 3.8.2. Nobody on the team released it.",
    nodes: [
        { id: "sc1", ph: "ident", kc: "delivery", att: ["T1195.001"],
          obs: "Attackers compromised an open-source dependency so that installing it ran malicious code.",
          title: "Something in node_modules",
          text: "The public repo holds the developer's environment variables and tokens. The source is a dependency, tiny-color-fmt 4.2.1, pulled in by a routine npm install yesterday. Its postinstall script ran on every machine and build agent that installed it. What first?",
          art: "$ npm ls tiny-color-fmt\n@{orgslug}/sdk@3.8.1\n  -- chalk-utils@2.0.4\n      -- tiny-color-fmt@4.2.1   (published 2 days ago)\n\"postinstall\": \"node bundle.js\"   (3.1 MB, minified)",
          disc: "Could you list every machine that ran a given npm package version yesterday? How long would it take?",
          opts: [
            { q: 3, u: ["logs"], t: "Find every machine and CI runner that installed 4.2.1 from lockfiles and build logs",
              r: "Seven developer laptops and every CI runner that built since Tuesday. You know the blast radius.",
              f: "Build logs are kept for 48 hours. You rebuild the list from lockfile commits and by asking developers, which takes all morning.",
              w: "Every machine that ran the install ran the payload. Lockfiles and build logs give you the list." },
            { q: 2, t: "Pin the dependency to the previous version and push the fix to main",
              r: "The fix is merged. Everything the payload already stole is still valid.",
              w: "Stopping new installs matters, but the payload already ran and took secrets. Scope, then rotate." },
            { q: 1, t: "Get the developer to delete the public repository straight away so the secrets aren't exposed",
              r: "Deleted. It had already been forked and scraped by at least two bots.",
              w: "Secrets in a public repo are harvested within minutes. Deleting doesn't un-leak them." },
            { q: 0, set: "waited", t: "Report the package to npm and wait for them to confirm it's malicious",
              r: "npm pulls it that afternoon. Your stolen tokens get used in the meantime.",
              w: "Reporting is good citizenship, not containment." } ] },

        { id: "sc1x", ph: "ident", kc: "delivery", if: "waited", enter: { heat: 1, impact: 6 }, att: ["T1195.001"],
          obs: "More developers installed the compromised dependency, spreading the worm internally.",
          title: "It's spreading",
          text: "While you waited, two more developers ran npm install on projects that pull the same dependency. The worm now has their tokens too, and one of them has admin on the GitHub organisation.",
          opts: [
            { q: 3, t: "Block the version at your registry proxy and warn all developers now",
              r: "No more installs. The two new victims are added to the rotation list.",
              w: "Stop the spread at the choke point, then warn people directly." },
            { q: 1, t: "Post a reminder in the engineering channel to be careful with npm installs",
              r: "Nobody knows what 'careful' means for a routine install.",
              w: "Vague warnings don't stop an automated worm." } ] },

        { id: "sc2", ph: "contain", kc: "exploit", att: ["T1552.001"],
          obs: "The malicious package harvested tokens and secrets from environment variables and config on each machine.",
          title: "Every secret, everywhere",
          text: "The payload collected environment variables, .npmrc files, cloud CLI credentials and GitHub tokens from each machine, then ran a secret scanner over local repos. The CI runners held the npm publish token and production cloud keys.",
          opts: [
            { q: 3, u: ["idp"], t: "Rotate every secret those machines could reach, publish and cloud keys first",
              r: "The npm publish token and cloud keys are rotated by 10:30. The rest follow by lunch.",
              f: "Rotating the cloud key breaks three production integrations that hardcoded it. You spend the afternoon firefighting.",
              w: "Rotate by blast radius: tokens that let the attacker publish code or touch production go first." },
            { q: 2, t: "Rotate the credentials found in the public repo, those are confirmed as stolen",
              r: "Those are done. The payload also sent secrets to a webhook you haven't found yet.",
              w: "The public repo is what you can see, not everything that was taken. Rotate everything reachable." },
            { q: 1, t: "Get every developer to change their password and turn on MFA if it's off",
              r: "Passwords change. Tokens and API keys, which don't care about passwords, keep working.",
              w: "Tokens and keys bypass passwords and MFA. Revoke them directly." },
            { q: 0, esc: true, t: "Keep the CI pipeline running, this week's release schedule can't slip",
              r: "The next build runs the payload again on a fresh runner.",
              w: "A compromised pipeline keeps compromising until it's stopped and cleaned." } ] },

        { id: "sc3", ph: "contain", kc: "actions", att: ["T1195.002"],
          obs: "Attackers used a stolen publishing token to release a trojanised version of the company's own package.",
          title: "It's our package now",
          text: "@{orgslug}/sdk 3.8.2 was published with the stolen token at 06:12. It contains the same worm. The SDK has 40,000 weekly downloads, many of them customers' build systems.",
          opts: [
            { q: 3, t: "Pull 3.8.2, ship a clean 3.8.3 and publish an advisory with indicators",
              r: "The bad version is pulled within the hour and the advisory helps customers check their builds.",
              f: "npm won't let you unpublish a version others depend on. You deprecate it and ask npm support to remove it, which takes until evening.",
              w: "You're now part of the supply chain attack. Remove the bad version, ship a clean one and tell downstream users exactly what to check." },
            { q: 2, t: "Publish a clean 3.8.3 quickly so everyone's builds pick up the fixed version",
              r: "Anyone on a version range gets 3.8.3. Anyone who already installed 3.8.2 is still infected and doesn't know it.",
              w: "A new version protects future installs. People already hit need to be told." },
            { q: 1, t: "Unpublish 3.8.2 quietly so you don't alarm customers or attract the press",
              r: "A researcher's blog names {org} as a source of the worm. Your silence becomes part of the story.",
              w: "Silent fixes erode trust and leave customers exposed. Coordinated disclosure is expected." },
            { q: 0, t: "Leave the package alone until the investigation has finished",
              r: "Downloads of 3.8.2 continue all morning.",
              w: "Every hour the malicious version is live, more customers install it." } ] },

        { id: "sc4", ph: "contain", kc: "actions",
          title: "Downstream",
          text: "Three enterprise customers have emailed: their security teams found 3.8.2 in their builds. One says they'll suspend the contract unless you give them a full timeline by 17:00.",
          disc: "Who talks to customers' security teams during an incident at your organisation? Is it written down?",
          opts: [
            { q: 3, t: "Give each a named contact, a factual timeline and indicators, with set update times",
              r: "Two customers thank you for being open. The third extends its deadline after your first update.",
              w: "Affected customers need facts they can act on, a person to talk to and a steady cadence." },
            { q: 2, t: "Send every customer the public advisory and ask them to follow its steps",
              r: "Helpful, but the three already affected want answers about their specific builds.",
              w: "Advisories are necessary but not enough for customers already hit." },
            { q: 1, t: "Route every customer query through legal first to avoid admitting liability",
              r: "Legal's first reply lands two days later. One customer has already suspended the contract.",
              w: "Legal input matters, but a silent vendor loses customers faster than an honest one." },
            { q: 0, t: "Point out politely that the flaw was in an open-source dependency, not in {org}'s own code",
              r: "Technically true. Also exactly what customers expect a vendor to say.",
              w: "Customers care that your package infected them, not whose code it was." } ] },

        { id: "sc5", ph: "erad", kc: "install", att: ["T1567.001"],
          obs: "The worm added a CI workflow that sends repo secrets to a public project on an attacker's account on every run.",
          title: "The worm's nest",
          text: "Across the GitHub organisation, 14 repos have a new workflow, .github/workflows/sync.yml, added by developer accounts. It dumps every repo secret to a public repo on each run.",
          opts: [
            { q: 3, u: ["logs"], t: "Remove the workflows, audit the whole org's changes, lock down workflow edits",
              r: "All 14 removed, plus two new deploy keys found in the audit log. Workflow changes now need review.",
              w: "Worms persist in CI configuration. Audit the whole organisation, not just the repos you know about." },
            { q: 2, t: "Delete the workflow file from each of the 14 repositories you've found",
              r: "The known ones are gone. The audit log shows a deploy key quietly added to a fifteenth repo.",
              w: "Remove what you've found, then search for what you haven't." },
            { q: 1, t: "Make all of the organisation's repositories private for the time being",
              r: "The dump repos are on attacker-controlled accounts. Nothing changes.",
              w: "Your repos' visibility isn't the problem; the exfiltration workflow is." },
            { q: 0, t: "Reinstall node_modules on every developer machine and call it cleaned up",
              r: "The workflows keep running on every push.",
              w: "The worm lives beyond the laptop now: in CI config, tokens and packages." } ] },

        { id: "sc6", ph: "recover", kc: "actions",
          title: "Shipping again",
          text: "Engineering wants to resume releases. The pipeline has been paused for two days and a customer bug fix is waiting.",
          opts: [
            { q: 3, t: "Rebuilt runners, short-lived tokens, and no dependency versions under a week old",
              r: "Releases resume on Monday. The new setup would have ignored tiny-color-fmt 4.2.1 for its first week.",
              w: "Short-lived tokens limit what a stolen secret can do, and delaying brand-new versions sidesteps most worm waves." },
            { q: 2, t: "Resume on the existing runners, now that all of the secrets have been rotated",
              r: "The runners still have the payload cached in their npm cache.",
              w: "Build infrastructure that ran malware needs rebuilding, not just new secrets." },
            { q: 1, t: "Freeze all dependency updates for six months to avoid a repeat",
              r: "Six months later you're two critical security patches behind.",
              w: "Never updating is its own risk. Delay and verify, don't freeze." },
            { q: 0, t: "Give the release team a long-lived admin publish token so they're never blocked",
              r: "The next worm wave finds a very useful token.",
              w: "Long-lived, powerful tokens are exactly what these worms hunt for." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15, trust: -5 }, att: ["T1195.002"],
        obs: "A trojanised version of the company's own SDK was pulled into a customer's build systems.",
        title: "Patient zero for someone else",
        text: "A large customer's CISO calls: their CI pulled @{orgslug}/sdk 3.8.2 overnight and the worm is now in their GitHub organisation. By lunchtime it's in the news, with {org} in the headline.",
        opts: [
            { q: 3, u: ["plan"], t: "Set up a joint call, share your full indicators and timeline, brief comms",
              r: "Your indicators help them contain it in hours. Their CISO says so publicly, which helps.",
              w: "When you're part of someone else's incident, speed and openness limit the damage to both of you." },
            { q: 2, t: "Send them the public advisory and offer to help if they need anything further from you",
              r: "They needed it an hour ago.",
              w: "Direct, proactive support beats an advisory when a customer is actively compromised." },
            { q: 0, t: "Let legal handle every contact with the customer from now on",
              r: "Their incident drags on for days. Their lawyers call yours.",
              w: "Legal should shape comms, not replace technical cooperation." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline fix. What is it?",
        opts: [
            { q: 3, t: "Short-lived CI tokens, trusted publishing, delayed new versions, a registry proxy",
              w: "It removes the long-lived secrets the worm steals and stops brand-new malicious versions reaching builds." },
            { q: 2, t: "Run a software composition analysis scan on every single build before it's released",
              w: "SCA catches known-bad versions, but a worm's first hours come before anyone knows." },
            { q: 1, t: "Require two developers to approve every single dependency update",
              w: "Humans can't spot a malicious minified postinstall script in a routine version bump." },
            { q: 0, t: "Rewrite the SDK so it has no third-party dependencies at all",
              w: "Admirable, enormous, and it doesn't fix the build pipeline." } ] }
});
