/* ---------- 16. Skimmed (web checkout card skimmer) ---------- */
SCEN.push({
    id: "skimmer", name: "Skimmed",
    blurb: "Customers are reporting fraud on cards they only used on your website. Something is skimming the checkout.",
    tags: ["web", "ecommerce", "pii"], start: [1, 9, 15],
    actor: "A financially motivated e-crime crew who slip card-skimming code into online checkout pages and harvest payment details as customers type. These digital skimmers can sit unnoticed for months, turning ordinary sales into a steady theft of card data.",
    sum: "discovered card-skimming code injected into its online checkout that had been quietly harvesting customers' payment details",
    escSum: "the skimmer kept collecting live card details for another two days before it was found and removed.",
    pre: [
        { kc: "recon", att: "T1593", txt: "Mapped the online shop's platform and its third-party scripts from public sources to find the weakest link." },
        { kc: "weapon", att: "T1608.001", txt: "Staged the skimmer payload on look-alike infrastructure, ready to be pulled into the checkout page." }
    ],
    intro: "Tuesday, 09:15. Your card processor flags a spike in fraud reports from cardholders who all have one thing in common: they recently paid on {org}'s online shop. Nothing else links them. No alarms have fired on your side. You are the lead analyst.",
    nodes: [
        { id: "sk1", ph: "ident", kc: "exploit", att: ["T1190"],
          obs: "A flaw in the shop's internet-exposed content system let an outsider quietly edit the checkout page.",
          title: "Fraud after checkout",
          text: "The pattern is clear: cardholders defrauded days after paying on {org}'s site. Your shop takes card details directly on the page. What do you do first?",
          art: "Processor alert: 210 fraud reports / 6 days, common point of purchase = {orgslug}.example/shop\nCheckout page diff: +<script src='cdn-metrics.example/collect.js'>  added 12 days ago",
          disc: "If a script changed on your checkout page last week, would anything have told you? What watches your front end?",
          opts: [
            { q: 3, u: ["plan"], t: "Preserve the checkout as evidence and bring in the processor and forensics",
              r: "The page and logs are captured intact, and the acquiring bank and a forensics firm are looped in early.",
              f: "You preserve the page, but the shop is on a hosted platform and pulling full logs needs a support ticket that takes hours.",
              w: "Card incidents have card-brand rules attached. Preserve the evidence and engage the acquirer and qualified forensics before you start changing things." },
            { q: 2, t: "Start pulling the shop's logs yourself to confirm it before telling anyone",
              r: "You build a decent picture, but you're one analyst on a card-data case with reporting deadlines already ticking.",
              w: "Confirming is right, but card cases carry acquirer and brand obligations. Bring them in as you scope, not after." },
            { q: 1, set: "yanked", t: "Quietly delete the suspicious script and watch to see if the fraud stops",
              r: "The script vanishes and so does the evidence of when it arrived and where it sent data.",
              w: "Ripping the payload without preserving it destroys the timeline and the proof you'll owe the card brands." },
            { q: 0, t: "Treat it as ordinary card fraud that isn't your problem to solve",
              r: "The reports keep climbing and every one traces back to your checkout.",
              w: "A common point of purchase pointing at your site is your incident, not the bank's." } ] },

        { id: "sk2", ph: "ident", kc: "exploit", att: ["T1056.003"],
          obs: "Injected code on the checkout copied each shopper's card number and security code as they typed and sent it out.",
          title: "What the code does",
          text: "The injected snippet hooks the payment form and streams every field, card number and security code included, to an outside server the moment a shopper submits. You need to know how long this has run and how many cards are affected.",
          art: "collect.js -> reads form fields on submit -> POST https://cdn-metrics.example/c\nfirst seen in page history: 12 days ago",
          disc: "Could you tell today exactly which orders passed through a tampered checkout, and reconstruct the count of exposed cards?",
          opts: [
            { q: 3, u: ["logs"], t: "Date the injection and count the orders that passed through it",
              r: "Page history and order logs bound it to twelve days and a few thousand transactions.",
              f: "Order logs are complete but the CDN access logs rotated after seven days, leaving a gap you flag openly.",
              w: "Scope is the deliverable here: when the tampering started and how many cards ran through it drives every notification that follows." },
            { q: 1, t: "Assume only today's orders are affected and scope to those",
              r: "You under-count badly. The card brands later find the real window from their own fraud data.",
              w: "Skimmers run for as long as they go unnoticed. Establish the window from evidence, not optimism." },
            { q: 0, t: "Ask the platform vendor to estimate the impact for you",
              r: "They point back at you: it's your page, your responsibility to scope.",
              w: "The obligation to scope and report sits with you, not the hosting platform." } ] },

        { id: "sk3", ph: "contain", kc: "actions", att: ["T1567"],
          obs: "Card details were being sent out to an attacker-run server hiding behind a plausible-looking analytics name.",
          title: "Turn off the tap",
          text: "The skimmer streams to cdn-metrics.example, a name chosen to look like harmless analytics. How do you stop the bleeding without wrecking your evidence?",
          disc: "Can you block a single outbound destination at your edge quickly, without taking the whole shop down?",
          opts: [
            { q: 3, u: ["plan"], t: "Remove the injected code, block the collection server, and lock the platform down",
              r: "The tampered script is pulled, the destination is blocked at the edge, and admin access to the platform is tightened.",
              w: "Cut the collection and the injection together, and close the way in, so it can't simply be re-added an hour later." },
            { q: 2, t: "Block the outbound server but leave the script while you investigate",
              r: "Collection stops for now, but the hostile code is one config change away from a new destination.",
              w: "Blocking the endpoint helps, but leaving the injected code in place leaves the attacker a live foothold on your page." },
            { q: 0, t: "Take the entire shop offline until you've finished the full investigation",
              r: "Revenue stops for days over something a targeted block would have handled.",
              w: "A total shutdown is rarely proportionate when you can surgically block the destination and pull the script." } ] },

        { id: "sk4", ph: "erad", kc: "install", att: ["T1505.003"],
          obs: "The intruder had also left a hidden backdoor page in the shop's files so they could re-inject the skimmer at will.",
          title: "Why it keeps coming back",
          text: "You remove the script and within hours it returns. Someone still has a way in. How do you get ahead of it?",
          art: "wwwroot/media/.thumb.php  (unfamiliar, 12 days old)  -> accepts commands, rewrites checkout",
          disc: "After a site compromise, do you clean the files in place, or rebuild from a known-good source? What's the difference in confidence?",
          opts: [
            { q: 3, u: ["edr", "logs"], t: "Hunt for backdoors and rebuild the platform from known-good",
              r: "The hidden backdoor page is found, and the shop is rebuilt from clean sources with credentials rotated.",
              f: "You rebuild successfully, but a second backdoor in an uploads folder surfaces the next morning and is removed.",
              w: "Injection that keeps returning means persistence. Rebuild from known-good and rotate access rather than trusting a cleaned file." },
            { q: 1, t: "Keep deleting the script each time it reappears",
              r: "You lose the race; the backdoor rewrites the page faster than you can clean it.",
              w: "Deleting the symptom while the foothold remains is an endless loop. Remove the way back in." },
            { q: 0, t: "Assume removing the script once was enough and close the incident",
              r: "It's back on the checkout by lunchtime.",
              w: "Never close on a compromise that re-appears. Find and remove the persistence first." } ] },

        { id: "sk5", ph: "recover", kc: "actions", at: 24.0,
          title: "Cards, brands and customers",
          text: "Tuesday, next day. You've stopped the skimmer and closed the way in. Thousands of cards passed through the tampered checkout. This is card data and personal data. How do you handle the fallout?",
          disc: "Who must you tell after a card-data compromise, and on what clock: your acquirer, the card brands, the regulator, the cardholders?",
          opts: [
            { q: 3, t: "Notify the acquirer and card brands and support affected customers",
              r: "The acquirer and brands are notified on time, and affected customers get clear guidance to watch and replace cards.",
              w: "Card-data compromises carry brand and acquirer notification duties and, for personal data, regulatory ones. Notify promptly and help cardholders act." },
            { q: 2, t: "Notify the card brands but hold off telling customers to avoid alarm",
              r: "The brands force reissuance anyway and customers hear it from their banks, wondering why not from you.",
              w: "Silence to customers reads as concealment and they find out regardless. Tell them what to do." },
            { q: 1, t: "Treat it as fixed now the skimmer is gone and move on",
              r: "The unreported exposure surfaces in the brands' fraud analysis and the questions get harder.",
              w: "Removing the skimmer isn't the end. The reporting obligations outlive the technical fix." },
            { q: 0, t: "Keep it quiet to protect the shop's reputation",
              r: "It comes out through the card networks, now with a cover-up attached.",
              w: "Concealing a card-data breach compounds the penalties and the reputational hit." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1567", "T1190"],
        obs: "Left in place, the injected code kept streaming fresh card details out with every sale.",
        title: "Still skimming",
        text: "Because the checkout was never truly cleaned, the skimmer keeps running. Every sale over the last two days has handed another card to the attacker.",
        opts: [
            { q: 3, u: ["plan", "logs"], t: "Freeze checkout, rebuild clean, and widen the exposed-card count",
              r: "Payments pause behind a maintenance page, the checkout is rebuilt clean, and the affected-card list is widened to match.",
              w: "When a skimmer is still live, stopping intake beats protecting uptime. Rebuild clean and re-scope who was hit." },
            { q: 2, t: "Block the current destination and hope that's enough",
              r: "It streams to a fresh destination within the hour.",
              w: "Blocking one endpoint on live, persistent tampering just moves the target." },
            { q: 0, t: "Keep the shop trading while you investigate slowly",
              r: "Every checkout adds another victim to the count.",
              w: "Trading through a live skimmer multiplies the harm by the minute." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one headline change after a skimmer sat on your checkout for twelve days. What do you push?",
        opts: [
            { q: 3, t: "Lock and monitor third-party scripts on the checkout",
              w: "Integrity controls and change alerts on the payment page catch an injected or altered script the day it appears, which is the whole game here." },
            { q: 2, t: "Move to a hosted payment page so cards never touch your site",
              w: "A strong structural fix that shrinks your card-data scope, though it needs the monitoring and platform hardening around it to hold." },
            { q: 1, t: "Run an annual penetration test of the website",
              w: "Useful, but a yearly snapshot would have missed a script injected in month three. Continuous monitoring is what fits." },
            { q: 0, t: "Add a cookie banner and a security badge to the checkout",
              w: "Reassurance theatre. It does nothing to detect or stop code tampering." } ] }
});

/* ---------- 17. Number's Up (SIM swap on finance) ---------- */
SCEN.push({
    id: "simswap", name: "Number's Up",
    blurb: "The FD's phone lost all signal this morning. Then the bank started texting about a login they didn't make.",
    tags: ["fraud", "identity"], start: [3, 8, 5],
    actor: "A fraud crew who take over a target's mobile number at the carrier, intercept the one-time codes protecting their bank and email, and move money before anyone connects the dots. The victim's first clue is usually a phone that has gone silent.",
    sum: "found that its finance director's mobile number had been hijacked at the carrier and used to intercept the codes guarding company banking",
    escSum: "a six-figure transfer cleared before the bank could freeze the account.",
    pre: [
        { kc: "recon", att: "T1589", txt: "Gathered {fd}'s personal details from public profiles and old breach dumps to pass the carrier's identity questions." },
        { kc: "weapon", att: "T1585", txt: "Opened receiving accounts in advance to move the money through once a transfer landed." }
    ],
    intro: "Thursday, 08:05. {fd}, your finance director, calls from a desk phone: their mobile has had no signal since 06:00, and their inbox is filling with bank messages about a password reset they never asked for. You are the lead analyst.",
    nodes: [
        { id: "ss1", ph: "ident", kc: "exploit", att: ["T1451"],
          obs: "The finance director's number was moved onto a handset the attacker controls, cutting the real phone off.",
          title: "No signal",
          text: "{fd}'s phone died at 06:00 and the bank is emailing about activity they don't recognise. What's your first move?",
          art: "06:02  Carrier  number transferred to new handset  line={fd}\n06:40  Bank  password reset requested\n06:44  Bank  sign-in OK from unrecognised device",
          disc: "If an attacker holds an exec's phone number, which of your systems that lean on texted codes fall with it?",
          opts: [
            { q: 3, u: ["idp"], t: "Freeze {fd}'s banking and reset their access from a trusted channel",
              r: "Banking is frozen and access is reset over a verified, in-person channel while the phone is untrusted.",
              f: "You freeze banking quickly, but one finance portal has no out-of-hours contact, so that reset waits until 09:00.",
              w: "A hijacked number means texted codes are the attacker's. Lock money movement first and reset through a channel the phone isn't part of." },
            { q: 2, t: "Start gathering the bank and carrier logs before acting",
              r: "You build a clear timeline, but every minute of gathering is a minute the attacker still holds the codes.",
              w: "Understanding matters, but with an active hijack, containing access comes first and the timeline follows." },
            { q: 1, t: "Tell {fd} to go to a carrier shop and get their number back",
              r: "They head off across town while the attacker still has banking access right now.",
              w: "Reclaiming the number matters, but it's slower than freezing the accounts the number protects." },
            { q: 0, t: "Assume it's a lost phone and ask {fd} to buy a replacement",
              r: "The bank messages weren't about a lost phone. A transfer is being set up.",
              w: "A silent phone plus unexpected bank resets is a takeover pattern, not a lost handset." } ] },

        { id: "ss2", ph: "ident", kc: "exploit", att: ["T1111"],
          obs: "Holding the number, the attacker received the bank's one-time codes and completed the password reset as {fd}.",
          title: "The codes went to them",
          text: "With the number in hand, every one-time code texted to {fd}, for the bank, for email, for the finance portal, landed on the attacker's handset. Which systems are exposed?",
          disc: "List everything {fd} logs into with a texted code. That list is your blast radius.",
          opts: [
            { q: 3, u: ["idp"], t: "List every system {fd} secures with texted codes and lock each",
              r: "Bank, mailbox and two finance tools are found relying on texted codes; each is locked or switched to a stronger check.",
              w: "The exposure is every account that trusts a text to that number. Enumerate them and close each, don't stop at the bank." },
            { q: 1, t: "Assume only the bank is affected and focus there",
              r: "The attacker is already reading {fd}'s redirected mailbox for anything else useful.",
              w: "A hijacked number unlocks more than the bank. Scope every system that texts a code to it." },
            { q: 0, t: "Wait for the carrier to restore the number before checking systems",
              r: "By restore time the attacker has used the codes they needed.",
              w: "Don't wait on the carrier to act on systems you control now." } ] },

        { id: "ss3", ph: "contain", kc: "actions", att: ["T1078"],
          obs: "Using the reset sign-in, the attacker logged in to the banking portal posing as {fd}.",
          title: "In as the FD",
          text: "The attacker is inside the banking portal as {fd}. A new payee has appeared. How do you contain it?",
          disc: "Do you have an after-hours line to your bank's fraud team, and does anyone know the number without looking it up?",
          opts: [
            { q: 3, u: ["idp"], t: "Kill sessions, alert the bank, reclaim the number",
              r: "Live sessions are terminated, the bank's fraud desk is engaged, and the carrier begins returning the number to {fd}.",
              f: "Sessions are killed and the bank engaged fast, but the carrier's port-back takes a couple of hours to complete.",
              w: "Contain on three fronts at once: end the attacker's sessions, get the bank actively watching, and take the number back." },
            { q: 1, t: "Just change {fd}'s banking password and move on",
              r: "The attacker's live session survives the password change and adds the payee anyway.",
              w: "A password change doesn't end an active session or the pending payment it set up." },
            { q: 0, t: "Wait to see whether the new payee is actually used",
              r: "It's used. A transfer is queued to it.",
              w: "A payee you didn't add, created during a takeover, gets removed, not observed." } ] },

        { id: "ss4", ph: "contain", kc: "actions", at: 2.0, att: ["T1657"],
          obs: "A payment to an unfamiliar account had been set up, ready to move the company's money out.",
          title: "The transfer",
          text: "A large transfer to the new payee is queued, and one smaller one has already been released. The recall clock is short. What now?",
          disc: "How fast can your finance team reach the bank to halt and recall a payment, and who is allowed to make that call?",
          opts: [
            { q: 3, t: "Call the bank's fraud line to halt the queued transfer and recall the sent one",
              r: "The queued payment is stopped and the bank freezes the receiving account with most of the sent funds intact.",
              w: "Payment recovery is a race measured in hours. The fraud line with the payment reference gives the best odds." },
            { q: 1, t: "Email the bank relationship manager and wait for a reply",
              r: "They reply after their morning meeting. The money has moved on by then.",
              w: "Email is far too slow for a recall. Phone the fraud line." },
            { q: 0, t: "Wait until the full investigation is done before contacting the bank",
              r: "The recall window closes and the funds are gone.",
              w: "The recall clock won't pause for your investigation." } ] },

        { id: "ss5", ph: "recover", kc: "actions", at: 6.0,
          title: "Never by text again",
          text: "Thursday afternoon. The number is back with {fd}, the transfer was stopped, and the attacker is locked out. Why did a texted code guard the company's money in the first place?",
          disc: "Where in your organisation does a text message still stand between an attacker and something that matters?",
          opts: [
            { q: 3, u: ["idp"], t: "Move finance to app or hardware MFA and set a carrier port lock",
              r: "Finance and admin accounts move to phishing-resistant MFA and {fd}'s line gets a port-out lock and PIN.",
              w: "Texted codes fall with the number. App or hardware factors don't, and a carrier port lock makes the next hijack far harder." },
            { q: 2, t: "Switch {fd} to an authenticator app but leave everyone else on texts",
              r: "{fd} is safer; the rest of finance is still one hijack away from the same morning.",
              w: "Fixing one person leaves the same weakness across the team. Move the group off texted codes." },
            { q: 1, t: "Tell staff to keep their phone numbers private in future",
              r: "The details were already out there from old breaches. Privacy advice won't undo that.",
              w: "You can't claw personal data back. Remove the dependency on the number instead." },
            { q: 0, t: "Consider it a one-off bit of bad luck and change nothing",
              r: "The same technique works on the next exec next quarter.",
              w: "SIM-swap fraud is routine and repeatable. Leaving texted codes in place invites the sequel." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1657"],
        obs: "The queued transfer cleared to the attacker's account before anyone reached the bank.",
        title: "Cleared",
        text: "While access was still open, the large transfer completed. A six-figure sum has left {org}'s account for one the attacker controls.",
        opts: [
            { q: 3, u: ["retainer"], t: "Get the bank recalling, report the fraud, and lock every account down",
              r: "The bank begins a recall on the correspondent chain, the fraud is reported, and all of {fd}'s access is hard-locked.",
              w: "After funds leave: bank recall, formal fraud report, and a full lockdown so no second transfer follows the first." },
            { q: 2, t: "Focus only on chasing the money through the bank",
              r: "You recover some funds, but the still-open access lets a second payee appear.",
              w: "Chase the money and close the door. Recovery without lockdown invites a repeat." },
            { q: 0, t: "Wait for the police report to complete before telling the bank",
              r: "Every hour of delay lets the money move another hop away.",
              w: "The bank needs to move on funds now; the police report runs alongside, not before." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board asks for one change after a texted code let a stranger into the company bank account. What do you push?",
        opts: [
            { q: 3, t: "Phishing-resistant MFA off SMS, plus carrier port protection",
              w: "It removes the two things this attack needed: a texted code to steal and an unprotected number to steal it from." },
            { q: 2, t: "Move all high-value payments to dual authorisation",
              w: "A strong control on the money itself, but it leaves the mailbox and portal takeovers untouched. Pair it with dropping SMS codes." },
            { q: 1, t: "Ask staff to set a PIN with their mobile carrier",
              w: "Helpful and worth doing, but voluntary and partial. The systemic fix is moving off texted codes." },
            { q: 0, t: "Tell executives to keep a spare phone",
              w: "A spare handset does nothing when the number itself is hijacked." } ] }
});

/* ---------- 18. Hostile Takeover (registrar / DNS hijack) ---------- */
SCEN.push({
    id: "registrar", name: "Hostile Takeover",
    blurb: "Customers say your website looks off and replies to your emails are vanishing. Someone's been at the domain settings.",
    tags: ["identity", "pii"], start: [0, 7, 50],
    actor: "An attacker who seized the account controlling {org}'s internet name, then rerouted its email and website to servers they own, so they could read messages, harvest logins and impersonate the company to its own customers.",
    sum: "discovered that the account controlling its internet name had been taken over and used to reroute company email and website traffic",
    escSum: "a week of inbound email was silently copied before the records were put back.",
    pre: [
        { kc: "recon", att: "T1593", txt: "Read public registration and DNS records to learn who hosts {org}'s internet name and how it's managed." },
        { kc: "weapon", att: "T1588.004", txt: "Lined up TLS certs for {org}'s name so the redirected sites would show the reassuring padlock." }
    ],
    intro: "Monday, 07:50. Staff can't send external email and it's bouncing back. Customers are calling to say the website redirects somewhere odd. Your registrar account shows an overnight login from an unfamiliar place and a batch of edited records. You are the lead analyst.",
    nodes: [
        { id: "rg1", ph: "ident", kc: "exploit", att: ["T1078"],
          obs: "Someone logged in to {org}'s registrar account overnight and began rewriting the internet name's records.",
          title: "The records don't match",
          text: "Email is bouncing, the website redirects, and the registrar shows edits you didn't make. Where do you start?",
          art: "02:14 Registrar sign-in  new device  geo=elsewhere\n02:20 Nameservers -> ns1.badhost.example\n02:22 Mail record -> mail.badhost.example",
          disc: "Who in your team can log in to your registrar right now, and is that account protected any better than a normal login?",
          opts: [
            { q: 3, u: ["plan"], t: "Contact the registrar to regain control and freeze the account",
              r: "The registrar verifies you as the real owner, locks the account and starts backing out the hostile changes.",
              f: "Support verifies ownership, but the account recovery takes an hour of proving who you are while records stay wrong.",
              w: "When the registrar account itself is taken, your first lever is the registrar. Regain control and freeze changes before anything else." },
            { q: 2, t: "Start documenting every changed record before contacting anyone",
              r: "You capture a clean before-and-after, but every minute of documenting is a minute of redirected mail.",
              w: "Capturing the changes is useful, but regaining control is the urgent move; the record can be built alongside." },
            { q: 1, t: "Try to edit the records back yourself in the panel",
              r: "You're locked out. The attacker changed the recovery contact too.",
              w: "You rarely win an edit war inside a hijacked account. Escalate to the registrar to reclaim it." },
            { q: 0, t: "Assume it's a DNS propagation glitch and wait it out",
              r: "It's no glitch. Your mail is flowing through someone else's server.",
              w: "Bouncing mail plus edited records plus a strange login is a takeover, not propagation." } ] },

        { id: "rg2", ph: "ident", kc: "actions", att: ["T1584.001"],
          obs: "The company's internet name now pointed its web and mail at servers the attacker runs.",
          title: "Whose servers now",
          text: "The nameservers and mail route were repointed to hosts the attacker controls, and a TLS cert may already have been issued for your name. How do you scope it?",
          disc: "Would you know if someone obtained a certificate for your name? What public record could tell you?",
          opts: [
            { q: 3, u: ["logs"], t: "Check certificate transparency and DNS history",
              r: "Public cert logs reveal a rogue cert issued at 03:00 and the DNS history shows every record they moved.",
              f: "The cert logs are clear, but your own DNS change history was only kept for 24 hours, leaving part of the picture to reconstruct.",
              w: "Certificate transparency and DNS history are your map of the takeover: what was repointed, and what certs now exist for your name." },
            { q: 1, t: "Assume only the website was affected and check that alone",
              r: "The mail route was moved too, and it's quietly copying inbound messages.",
              w: "A registrar takeover usually hits mail as well as web. Scope both routes and any certs." },
            { q: 0, t: "Trust that fixing the nameservers undoes everything",
              r: "The rogue certs and the intercepted mail persist regardless of the nameservers.",
              w: "Repointing records doesn't revoke a cert or recall the mail already read." } ] },

        { id: "rg3", ph: "contain", kc: "actions", att: ["T1114.002"],
          obs: "The redirected route let the attacker read messages sent to {org}, including password resets.",
          title: "Reading the post",
          text: "While the route was hijacked, inbound mail flowed through the attacker, including password-reset links for other systems. How do you contain the damage?",
          disc: "If your inbound mail was readable for hours, which account resets could an attacker have completed with it?",
          opts: [
            { q: 3, u: ["idp"], t: "Restore the records, revoke the rogue certs, and reset anything reset by mail",
              r: "Records are put back, the rogue certs are revoked, and every account whose reset could have been intercepted is force-reset.",
              w: "Undo the redirect, kill the certs that trusted it, and assume any password reset that flowed through it is compromised." },
            { q: 2, t: "Restore the records and revoke the certs, but skip the resets",
              r: "The redirect is gone, but an account reset during the window is used against you a day later.",
              w: "Fixing the plumbing isn't enough if resets flowed through it. Reset what the attacker could have grabbed." },
            { q: 0, t: "Just point the records back and call it contained",
              r: "The rogue cert still lets them impersonate your site convincingly.",
              w: "Records alone leave the certs and any intercepted resets live." } ] },

        { id: "rg4", ph: "erad", kc: "install", att: ["T1656"],
          obs: "With the look-alike site and mail route, the attacker posed as {org} to phish its customers and partners.",
          title: "Pretending to be us",
          text: "Customers report emails and a site that look like {org} but aren't, asking them to log in or pay. How do you handle the outside damage?",
          disc: "When your own name is being used against your customers, who warns them, and how fast can you get fakes taken down?",
          opts: [
            { q: 3, u: ["plan"], t: "Warn customers and partners and get the look-alike sites taken down",
              r: "A clear warning goes out through trusted channels and takedown requests start against the fake sites and certs.",
              f: "The warning lands well, but one reseller had already actioned a fake payment request before it reached them.",
              w: "When your name is the weapon, fast honest warnings to customers plus takedowns limit who gets caught by it." },
            { q: 1, t: "Stay quiet to avoid admitting the website was hijacked",
              r: "Customers keep getting phished in your name and blame you for the silence.",
              w: "Silence while your customers are targeted in your name does more reputational harm than the honest warning." },
            { q: 0, t: "Assume customers will spot the fakes themselves",
              r: "A partner pays a fake invoice sent from your look-alike address.",
              w: "Convincing look-alikes with a valid padlock fool people. Warn them proactively." } ] },

        { id: "rg5", ph: "recover", kc: "actions", at: 12.0,
          title: "Locking the front door",
          text: "Monday evening. Records are restored, certs revoked, customers warned. The takeover happened because the registrar account had a normal password and nothing more. This route also carried personal data in intercepted mail.",
          disc: "What protects your registrar account today, and would a stolen password be enough to repeat all of this?",
          opts: [
            { q: 3, t: "Enable registrar MFA and a registry lock, assess with the DPO",
              r: "The registrar account gets MFA and a registry lock, DNS is monitored, and the DPO assesses the intercepted mail as a possible breach.",
              w: "Harden the account that failed, lock the records at the registry, monitor for changes, and treat readable inbound mail as a data breach to assess." },
            { q: 2, t: "Turn on registrar MFA but skip the registry lock and monitoring",
              r: "Better, but a future support-desk social-engineering could still move the records unnoticed.",
              w: "MFA on the login is a start; a registry lock and change monitoring are what stop the record edits themselves." },
            { q: 1, t: "Just change the registrar password and consider it handled",
              r: "A new password on an unmonitored, unlocked account is the same door with a new key.",
              w: "A password alone is what got taken. Add MFA, a registry lock and monitoring." },
            { q: 0, t: "Assume the registrar will prevent it happening again",
              r: "The registrar offers those protections but leaves it to you to switch them on. You didn't.",
              w: "Domain protections are opt-in. Enabling them is your job, not the registrar's default." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1114.002"],
        obs: "For as long as the mail route stayed hijacked, every inbound message was quietly copied.",
        title: "A week of post",
        text: "Because the records weren't restored quickly, the hijacked mail route kept copying every inbound message for days before you cut it.",
        opts: [
            { q: 3, u: ["plan", "idp"], t: "Restore records, revoke certs, reset broadly, and assess the breach",
              r: "The route is restored, certs revoked, exposed credentials reset, and the copied mail is assessed as a reportable breach.",
              w: "After prolonged interception: cut the route, kill the certs, reset what flowed through, and assess the exposure formally." },
            { q: 2, t: "Restore the records and hope little of value was in the mail",
              r: "Some of it held resets and personal data you now have to account for.",
              w: "Hope isn't scoping. Assume the intercepted mail was read and assess it." },
            { q: 0, t: "Keep the incident quiet to protect the brand",
              r: "The rogue certs are public in transparency logs; the story surfaces anyway.",
              w: "Certificate transparency makes this kind of hijack findable. Get ahead of it honestly." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one change after a stranger repointed the company's own internet name overnight. What do you push?",
        opts: [
            { q: 3, t: "Harden and lock the registrar account",
              w: "It defends the exact thing that failed: a hard-to-take account, records the registry won't move without extra steps, and an alert the moment they change." },
            { q: 2, t: "Adopt DNSSEC across the estate",
              w: "Worthwhile against record tampering, but it wouldn't stop an attacker who owns the registrar login. The account controls come first." },
            { q: 1, t: "Move to a more expensive registrar",
              w: "Price isn't the control. The same account, unprotected, is just as takeable at any registrar." },
            { q: 0, t: "Ask staff to bookmark the real website",
              w: "Bookmarks don't help when it's your genuine name that's been repointed." } ] }
});

/* ---------- 19. Pocket Sized (smishing to mobile compromise) ---------- */
SCEN.push({
    id: "mobile", name: "Pocket Sized",
    blurb: "The CEO tapped a link in a text about a parcel. Now their phone is doing things they didn't ask for.",
    tags: ["mobile", "identity", "pii"], start: [4, 16, 20],
    actor: "An attacker who phishes an executive by text, gets a malicious profile onto their phone, and turns the device itself into a way to read their mail and the login codes that guard everything else.",
    sum: "found that an executive's phone had been compromised through a malicious text, exposing their mailbox and login codes",
    escSum: "the attacker read the chief executive's mailbox for three days using the phone's own access.",
    pre: [
        { kc: "recon", att: "T1591", txt: "Profiled {ceo}'s role and number from public sources to craft a text they'd believe." },
        { kc: "weapon", att: "T1660", txt: "Stood up a fake parcel-tracking page to deliver a rogue configuration profile." }
    ],
    intro: "Friday, 16:20. {ceo} forwards you a text: 'Your parcel is held, pay 0.99 to release it.' They admit they tapped it an hour ago, entered card details, and approved 'something to install' on their phone. The device is now behaving oddly. You are the lead analyst.",
    nodes: [
        { id: "mb1", ph: "ident", kc: "delivery", att: ["T1660"],
          obs: "{ceo} was lured by a text to a fake parcel page and talked into installing a rogue configuration on their phone.",
          title: "Just a parcel text",
          text: "{ceo} tapped a scam parcel link, paid a token fee, and installed a profile onto their handset an hour ago. It's now acting strangely. What first?",
          art: "16:20 SMS -> {ceo}: parcel-hold.example\n17:05 Device: new configuration profile installed\n17:12 Mailbox: forwarding rule added",
          disc: "If an executive's phone is turned against you, what company access lives on that one device?",
          opts: [
            { q: 3, u: ["idp"], t: "Cut the phone off from company access and revoke its sessions",
              r: "The device is blocked from company services and its live sessions are revoked before more is done through it.",
              f: "You block it fast, but {ceo}'s phone is personal and getting it enrolled enough to revoke cleanly takes a few calls.",
              w: "A hostile profile turns the phone into the attacker's tool. Sever its company access and kill its sessions first." },
            { q: 2, t: "Start pulling the mailbox and device logs before acting",
              r: "You learn a lot, but the phone keeps its access the whole time you're reading.",
              w: "Investigation is right, but a live compromised device should lose its access while you scope, not after." },
            { q: 1, t: "Tell {ceo} to delete the text and restart the phone",
              r: "The rogue profile survives a restart and keeps its foothold.",
              w: "Deleting the message doesn't remove an installed profile. It needs proper containment." },
            { q: 0, t: "Assume a scam text is harmless once the small fee is paid",
              r: "The fee was the hook. The profile is the actual attack, and it's live.",
              w: "The payment was bait; the installed profile is the compromise. Treat the device as hostile." } ] },

        { id: "mb2", ph: "ident", kc: "exploit", att: ["T1635"],
          obs: "The rogue profile handed the attacker the phone's saved sign-in for company mail.",
          title: "The keys on the phone",
          text: "The profile lifted the mail app's saved sign-in, so the attacker can reach {ceo}'s mailbox without a password. What else lives on that handset, and how do you cut it off?",
          disc: "An executive phone often holds mail, an authenticator and a VPN profile. Which of those just became the attacker's?",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke the mail sign-in, re-issue the authenticator",
              r: "The stolen mail sign-in is revoked and {ceo}'s authenticator is rebuilt on a fresh, trusted phone.",
              w: "A saved sign-in that's been lifted stays valid until revoked. Kill it and move the authenticator off the compromised handset." },
            { q: 1, t: "Change {ceo}'s password and leave the sign-in in place",
              r: "The lifted sign-in keeps working; a password change doesn't touch it.",
              w: "A stolen saved sign-in survives a password change. It has to be revoked directly." },
            { q: 0, t: "Assume only the mail app is affected and stop there",
              r: "The authenticator on the same phone is compromised too, and it guards everything else.",
              w: "Scope the whole device. On a phone, one profile can reach every credential on it." } ] },

        { id: "mb3", ph: "contain", kc: "actions", att: ["T1517"],
          obs: "The rogue profile could read the codes popping up on the lock screen, including sign-in prompts.",
          title: "Reading over the shoulder",
          text: "The profile can see the codes and prompts that appear on {ceo}'s lock screen, so it watches the very approvals meant to stop it. How do you contain?",
          disc: "If something on the phone can read your login prompts, is any code sent to that phone still a secret?",
          opts: [
            { q: 3, u: ["idp"], t: "Wipe and re-enrol the phone and reset {ceo}'s MFA",
              r: "The handset is wiped and re-enrolled clean, and {ceo}'s login factors are reset onto trusted hardware.",
              f: "The wipe goes fine, but a shared family backup means restoring apps carefully so the profile doesn't return.",
              w: "Once the device can read your prompts, nothing on it is trusted. Wipe, re-enrol, and reset the factors elsewhere." },
            { q: 1, t: "Just remove the profile you can see and leave the phone in use",
              r: "A second component reinstalls it after the next lock-screen prompt.",
              w: "Removing the visible piece rarely clears a phone compromise. A clean wipe is the reliable move." },
            { q: 0, t: "Keep using the phone but tell {ceo} to ignore odd prompts",
              r: "The attacker doesn't need {ceo} to act; it reads the prompts itself.",
              w: "You can't user-train around a device that reads its own screen. Take it out of the loop." } ] },

        { id: "mb4", ph: "erad", kc: "actions", att: ["T1114.002"],
          obs: "Using the phone's mail access, the attacker had been reading and quietly forwarding {ceo}'s messages.",
          title: "What they read",
          text: "With the mailbox open, the attacker set a hidden forwarding rule and has been reading {ceo}'s mail. How do you scope and clean it?",
          disc: "How would you find a forwarding rule an attacker set on an executive mailbox, and know what they'd already read?",
          opts: [
            { q: 3, u: ["logs"], t: "Find and remove hidden rules and scope what was read",
              r: "The forwarding rule is removed and mailbox logs show which threads were opened during the window.",
              w: "Hostile mailbox access means hidden rules and read history. Remove the rules and establish what was actually seen." },
            { q: 1, t: "Delete recent suspicious emails and assume that covers it",
              r: "The forwarding rule stays, still copying new mail out.",
              w: "Deleting messages misses the rule doing the exfiltration. Hunt the rules." },
            { q: 0, t: "Trust that revoking the device access ended the mailbox risk",
              r: "The forwarding rule outlives the device and keeps sending mail onward.",
              w: "Mailbox persistence lives in the mailbox, not the phone. Check it directly." } ] },

        { id: "mb5", ph: "recover", kc: "actions", at: 8.0,
          title: "Locking the pocket",
          text: "Friday evening. The phone is clean, the mailbox rules are gone, and {ceo}'s factors are reset. This happened because a personal phone with company mail could install anything and had no policy over it. The mailbox held personal data too.",
          disc: "What stands between a tapped link and a compromised executive phone in your organisation today?",
          opts: [
            { q: 3, t: "Enforce device compliance and block untrusted profiles through MDM",
              r: "Company access now requires a managed, compliant device, and installing unmanaged profiles is blocked, with the mailbox exposure assessed.",
              w: "The fix is management: only compliant devices reach company data, hostile profiles are blocked, and the mail exposure gets a breach assessment." },
            { q: 2, t: "Ask executives to be more careful with text-message links",
              r: "Care helps, but the next convincing lure lands eventually and nothing technical stops it.",
              w: "Awareness is a layer, not the control. Device management is what stops a hostile profile taking hold." },
            { q: 1, t: "Ban personal phones from company mail entirely",
              r: "Executives quietly route mail to personal accounts to get their work done instead.",
              w: "An outright ban tends to push people to riskier workarounds. Manage the devices rather than forbidding them." },
            { q: 0, t: "Assume a wiped phone means the problem is fully solved",
              r: "The same lure compromises another unmanaged phone the following month.",
              w: "Cleaning one device doesn't change the conditions that let it happen. Fix the policy." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1114.002"],
        obs: "Left with its access, the phone let the attacker read the chief executive's mailbox for days.",
        title: "Three days of mail",
        text: "Because the device kept its access, the attacker quietly read {ceo}'s mailbox for three days, including board and deal correspondence, before it was cut off.",
        opts: [
            { q: 3, u: ["idp", "plan"], t: "Cut the device, reset the factors, and assess the mailbox exposure",
              r: "The phone is fully severed, {ceo}'s factors are reset on clean hardware, and the exposed correspondence is assessed for breach and market impact.",
              w: "After prolonged mailbox access: sever the device, reset every factor it held, and assess sensitive correspondence for its own obligations." },
            { q: 2, t: "Wipe the phone and treat the mailbox as unaffected",
              r: "The mailbox held sensitive deal talk that now has to be accounted for.",
              w: "The phone was the door; the mailbox is the loss. Assess what was read." },
            { q: 0, t: "Keep it quiet given how sensitive the mailbox content is",
              r: "Sensitive content read by an attacker rarely stays contained, and silence worsens it.",
              w: "Sensitive exposure needs careful handling, not concealment. Assess and act on the obligations." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one change after a text message opened the chief executive's phone and mailbox. What do you push?",
        opts: [
            { q: 3, t: "Mobile device management with compliance and phishing-resistant MFA",
              w: "It closes the whole chain: only managed devices reach company data, hostile profiles are blocked, and factors that can't be read off a screen guard the accounts." },
            { q: 2, t: "Run phishing-awareness training aimed at executives",
              w: "A useful layer, but a convincing lure will eventually land. The device controls are what contain it when it does." },
            { q: 1, t: "Issue executives a separate locked-down work phone",
              w: "Helps if it's actually managed and used, but without MDM policy it's just another unmanaged handset." },
            { q: 0, t: "Block all text messages containing links",
              w: "Unworkable and easily evaded, and it does nothing about the profile once installed." } ] }
});

/* ---------- 20. Free Wi-Fi (evil-twin at an event) ---------- */
SCEN.push({
    id: "eviltwin", name: "Free Wi-Fi",
    blurb: "Several staff logged into 'Conference-WiFi' at the expo. Now their accounts are doing things they aren't.",
    tags: ["network", "identity"], start: [2, 10, 30],
    actor: "An attacker who stands up a look-alike Wi-Fi network near your people, sits in the middle of their traffic, and steals the session tokens that let them walk into company accounts with no password and no prompt.",
    sum: "traced a run of account break-ins to a rogue Wi-Fi network that had stolen staff session tokens at an offsite event",
    escSum: "the stolen sessions reached the chief executive's mailbox before they were cut.",
    pre: [
        { kc: "recon", att: "T1591", txt: "Learned that {org} staff would be at the industry expo and which accounts would be worth taking." },
        { kc: "weapon", att: "T1585", txt: "Prepared a look-alike sign-in page to harvest logins from anyone who joined the fake network." }
    ],
    intro: "Wednesday, 10:30. Three of your team are at an industry expo. Since this morning their {saas} accounts show sign-ins from an unknown device, though the passwords are right and no MFA prompt appeared. All three joined a network called 'Conference-WiFi' at the venue. You are the lead analyst.",
    nodes: [
        { id: "et1", ph: "ident", kc: "delivery", att: ["T1557"],
          obs: "A fake hotspot at the expo sat between staff and the internet, quietly watching their traffic.",
          title: "Conference Wi-Fi",
          text: "Three staff at the expo have unexplained sign-ins on their {saas} accounts, no MFA prompt, correct passwords, and one thing in common: the venue Wi-Fi. Where do you start?",
          art: "10:31 {saas} sign-in OK  user=sales01  no MFA prompt  device=unknown\n10:33 same pattern x2\ncommon factor: SSID 'Conference-WiFi'",
          disc: "How would you even learn that three staff joined the same rogue network at a venue you don't control?",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke the affected staff's sessions and force fresh sign-ins",
              r: "The three accounts have their live sessions killed and must sign in again cleanly on trusted devices.",
              f: "You revoke fast, but one of the three is mid-demo on stage and can't re-authenticate for an hour.",
              w: "Sign-ins with no MFA prompt point at stolen sessions. Kill the sessions first; the investigation follows." },
            { q: 2, t: "Gather the sign-in logs for all three before doing anything",
              r: "You get a clear pattern, but the attacker keeps using the live sessions while you read.",
              w: "The pattern matters, but with sessions in play, revoking them comes first and the analysis after." },
            { q: 1, t: "Reset the three passwords and consider it handled",
              r: "The stolen sessions keep working; they never needed the password.",
              w: "A password reset doesn't end a live session that was taken whole. Revoke the sessions." },
            { q: 0, t: "Assume they're just travel sign-ins from a new location",
              r: "Travel doesn't skip the MFA prompt or come from one venue network at once.",
              w: "No prompt plus a shared venue network is a session-theft signature, not travel." } ] },

        { id: "et2", ph: "ident", kc: "exploit", att: ["T1539"],
          obs: "The fake network copied the tokens that keep staff signed in, so the attacker never needed their passwords.",
          title: "No password needed",
          text: "Sitting in the middle of the traffic, the attacker lifted the tokens that hold a login open, which is why MFA never fired. Who else on your team joined that network?",
          disc: "A stolen sign-in token can skip the password and the MFA prompt entirely. How long does yours stay valid?",
          opts: [
            { q: 3, u: ["logs"], t: "Identify everyone who joined that network and check their sign-ins",
              r: "The attendee list and sign-in logs surface two more staff who connected and are quietly flagged.",
              w: "The blast radius is everyone who joined the rogue network. Find them from attendance and sign-in logs, not just the first three." },
            { q: 1, t: "Assume only the three flagged accounts are affected",
              r: "A fourth attendee's account is used that afternoon; you hadn't checked them.",
              w: "The three you saw are the ones that acted first. Scope everyone who connected." },
            { q: 0, t: "Wait for more suspicious sign-ins before widening the net",
              r: "Waiting hands the attacker the initiative on accounts you could have secured now.",
              w: "Don't wait for harm to define scope. Everyone on that network is in scope now." } ] },

        { id: "et3", ph: "contain", kc: "exploit", att: ["T1056.003"],
          obs: "A fake sign-in page behind the hotspot also grabbed some staff passwords as they typed them.",
          title: "Some typed it in",
          text: "Behind the fake Wi-Fi sat a convincing sign-in page. A couple of staff typed their actual passwords into it before reaching the real service. How do you contain?",
          disc: "Some lost only a session; some also handed over the password itself. Do you treat those two groups the same?",
          opts: [
            { q: 3, u: ["idp"], t: "Reset the typed-in passwords and revoke all tokens",
              r: "The staff who entered credentials get full resets, and every token for the whole affected group is revoked.",
              w: "Stolen sessions need revoking; typed-in passwords need resetting too. Handle both groups for the people who were caught by the page." },
            { q: 2, t: "Revoke everyone's sessions but skip the password resets",
              r: "The typed-in passwords still work, and one is reused the next day.",
              w: "Session revocation alone leaves a handed-over password live. Reset those." },
            { q: 0, t: "Assume the tokens were the only thing lost",
              r: "A reused password opens a second account through the front door.",
              w: "Where a fake page harvested passwords, the password itself is compromised, not just the session." } ] },

        { id: "et4", ph: "contain", kc: "actions", att: ["T1550.004"],
          obs: "The attacker replayed the stolen tokens to open staff mailboxes from their own machine.",
          title: "Walking straight in",
          text: "The attacker is replaying the lifted tokens to reach mailboxes and files as your staff, from a device you've never seen. How do you shut it down for good?",
          disc: "If a stolen token lets someone in without a password or a prompt, what control actually stops them using it?",
          opts: [
            { q: 3, u: ["idp"], t: "Invalidate all active sessions and require re-auth on compliant devices",
              r: "Every session is invalidated and sign-in is now gated on a managed, compliant device the attacker doesn't have.",
              w: "A replayed token dies when you invalidate sessions and bind future sign-ins to devices the attacker can't produce." },
            { q: 1, t: "Block the attacker's current IP address and leave it there",
              r: "They reconnect from a new address and keep replaying the tokens.",
              w: "IP blocking is whack-a-mole against a replayed token. Invalidate the sessions and gate on device." },
            { q: 0, t: "Wait to see which mailboxes they open before acting",
              r: "They read what they need while you watch.",
              w: "Active token replay gets cut off, not observed." } ] },

        { id: "et5", ph: "recover", kc: "actions", at: 6.0,
          title: "Never trust the venue",
          text: "Wednesday afternoon. Sessions are invalidated and the caught accounts are reset. This worked because a token stolen on any network was accepted anywhere, from any device. What changes?",
          disc: "Would a token stolen from one of your staff on hotel Wi-Fi tonight still let an attacker in from their own laptop?",
          opts: [
            { q: 3, t: "Bind sessions to managed devices and brief staff",
              r: "Conditional access ties sessions to compliant devices, and staff get clear guidance on venue Wi-Fi and using the VPN.",
              w: "The durable fix makes a stolen token useless off a managed device, backed by staff guidance for hostile networks." },
            { q: 2, t: "Roll out an always-on VPN for travelling staff",
              r: "It helps against interception, but a token stolen another way is still accepted from anywhere.",
              w: "A VPN reduces the interception risk but doesn't bind the token to a device. Pair it with conditional access." },
            { q: 1, t: "Tell staff never to use public Wi-Fi again",
              r: "They use it anyway when the deadline bites, as people always do.",
              w: "Blanket bans on public Wi-Fi don't hold. Make the stolen token worthless instead." },
            { q: 0, t: "Treat it as bad luck at one event and change nothing",
              r: "The same trick works at the next conference on the calendar.",
              w: "Evil-twin networks are a standard event risk. Without a control, the next expo repeats this." } ] }
    ],
    esc: { id: "ESC", ph: "contain", kc: "actions", enter: { impact: 15 }, att: ["T1550.004", "T1114.002"],
        obs: "The stolen sessions were replayed far enough to reach the chief executive's mailbox before being cut.",
        title: "All the way up",
        text: "While the sessions stayed valid, the attacker replayed them from account to account and reached {ceo}'s mailbox before you invalidated everything.",
        opts: [
            { q: 3, u: ["idp", "plan"], t: "Invalidate sessions and reset what was reached",
              r: "All sessions are invalidated, every account the attacker reached is reset, and the mailbox exposure is assessed.",
              w: "After lateral session replay: invalidate globally, reset each account actually reached, and assess what sensitive access exposed." },
            { q: 2, t: "Reset the executive account and leave the rest",
              r: "Another still-valid session lets the attacker back into a second mailbox.",
              w: "One reset doesn't end a spread of replayed sessions. Invalidate them all." },
            { q: 0, t: "Assume reaching one mailbox means little was taken",
              r: "That mailbox is exactly the one worth reading.",
              w: "Reaching the top mailbox is the worst case, not a minor one. Assess it properly." } ] },
    ll: { id: "LL", ph: "lessons", title: "The one fix that matters",
        text: "The board wants one change after a fake Wi-Fi network at an expo let a stranger into staff accounts. What do you push?",
        opts: [
            { q: 3, t: "Conditional access and token protection so a stolen token is useless",
              w: "It removes the payoff entirely: a token lifted on any network won't work from a device that isn't managed and compliant." },
            { q: 2, t: "Deploy an always-on VPN for all remote and travelling staff",
              w: "A solid reduction in interception, but a token taken another way still travels. It needs device-bound access alongside." },
            { q: 1, t: "Provide staff with mobile hotspots to avoid public Wi-Fi",
              w: "Reduces exposure for those who use them, but doesn't make a stolen token worthless the way device binding does." },
            { q: 0, t: "Tell staff to avoid Wi-Fi networks they don't recognise",
              w: "Advice alone won't survive a busy expo. The token has to stop being usable off a managed device." } ] }
});
