/* ================= DATA: INJECTS ==============================================
   Injects are curveballs that fire between scenario nodes. Each scenario has its
   own pool so they never repeat across scenarios and always fit the situation.
   kind "q" = quirky, "s" = serious. ph limits which phases an inject can appear in.
   cond(run) is an optional extra test. Options score like any decision (q 0-3).
   ========================================================================== */

const MID = ["ident", "contain", "erad", "recover"];
const LATE = ["contain", "erad", "recover"];

const SCEN_INJ = {

    /* ---------- 1. Help Desk Hijack ---------- */
    helpdesk: [
        { id: "hd_queue", kind: "q", ph: MID, title: "Reset the resets",
          text: "Your forced password reset has buried the service desk in calls. One of the callers could be the attacker trying to get back in among the noise.",
          opts: [
            { q: 3, u: ["idp"], t: "Verify every reset with a call-back to a known number and a second factor",
              r: "The queue moves slower but each reset is proven. Two callers can't pass the check and are flagged.",
              w: "During an identity incident the reset process is itself a target. Verify who you're resetting for, out of band." },
            { q: 1, t: "Push resets through fast to clear the backlog and calm everyone down",
              r: "The backlog clears. So does the attacker's lockout, on the third try.",
              w: "Speed without verification just re-opens the door you slammed." },
            { q: 0, t: "Freeze all resets until the incident is over",
              r: "Legitimate staff are now locked out of the systems you need them in.",
              w: "A blanket freeze stops the business as well as the attacker. Verify, don't halt." } ] },
        { id: "hd_vish", kind: "s", ph: MID, title: "IT support is calling",
          text: "Staff report calls from 'the incident team' asking them to approve an MFA prompt to 'help with the fix'. It isn't your team.",
          opts: [
            { q: 3, u: ["idp"], t: "Tell all staff out of band that IT will never ask them to approve a prompt",
              r: "Two more calls come in within the hour. Nobody approves anything.",
              w: "Attackers exploit the confusion of an incident. Set a clear rule staff can apply without thinking." },
            { q: 1, t: "Warn just the people who reported the calls",
              r: "Someone you didn't warn approves a prompt an hour later.",
              w: "If several were called, many were. Warn everyone." },
            { q: 0, t: "Assume it's a colleague helping out and tell staff to cooperate",
              r: "Your whole team is on the bridge with you. It wasn't them.",
              w: "Verify every contact during an incident before vouching for it." } ] },
        { id: "hd_reboot", kind: "q", ph: LATE, title: "I turned it off and on",
          text: "A well-meaning sysadmin rebooted one of the encrypted ESXi hosts 'to see if it clears'. It didn't, and the memory you needed for forensics is gone.",
          opts: [
            { q: 3, t: "Freeze all hands-on changes, agree who may touch hosts, and note the loss in the timeline",
              r: "The change freeze holds and everyone knows the rule. The lost host is documented so nobody chases a ghost later.",
              w: "In recovery, uncoordinated 'fixes' destroy evidence and state. One owner authorises changes to affected systems." },
            { q: 1, t: "Carry on, one host of many won't change the picture",
              r: "It held the only clean log copy of the initial access. Now reconstructed the hard way.",
              w: "Assume any affected host holds evidence until proven otherwise." },
            { q: 0, t: "Tell the sysadmin to keep trying reboots on the others in case it works",
              r: "Two more hosts lose their volatile evidence.",
              w: "Reboot is not a remediation for encryption, and it costs you forensics." } ] },
        { id: "hd_customer", kind: "s", ph: LATE, title: "Your biggest customer heard",
          text: "A major customer's security team wants a written update within two hours or they'll cut their API links to {org}.",
          opts: [
            { q: 3, t: "Send a cleared factual update and a named contact",
              r: "They keep the link open and ask to stay in the loop.",
              w: "Partners manage their own risk. Timely, factual updates keep the relationship and the connection." },
            { q: 2, t: "Send them the same holding line you gave the press",
              r: "It's too thin for them. They cut the link until Monday.",
              w: "Partners need scope and indicators, not just the public line." },
            { q: 0, t: "Wait until the incident is closed to reply",
              r: "They cut the link and raise it with their board.",
              w: "Silence to a partner reads as chaos or concealment." } ] }
    ],

    /* ---------- 2. Edge of Chaos ---------- */
    edge: [
        { id: "edge_patch", kind: "s", ph: MID, title: "The patch lands mid-fight",
          text: "The vendor releases the fix for the appliance zero-day right now. Applying it may wipe the very evidence of how they got in.",
          opts: [
            { q: 3, t: "Image the appliance first, then patch it",
              r: "A forensic image is taken, then the patch goes on. You keep both the fix and the evidence.",
              f: "The image takes longer than hoped on the appliance's slow storage, but it completes before you patch.",
              w: "Patching closes the hole but overwrites the story. Capture state first, then remediate." },
            { q: 1, t: "Patch immediately, closing the hole is the priority",
              r: "The hole closes and the initial-access evidence goes with it.",
              w: "Speed is right, but a quick image first costs little and keeps the forensics." },
            { q: 0, t: "Hold off patching until the investigation is fully done",
              r: "The unpatched appliance is re-exploited by a second actor overnight.",
              w: "Leaving a known-exploited box unpatched invites the next visitor." } ] },
        { id: "edge_shadow", kind: "q", ph: MID, title: "The appliance nobody owned",
          text: "Scanning the perimeter, you find a second VPN appliance nobody knew was still there, unpatched and internet-facing since 2021.",
          opts: [
            { q: 3, t: "Treat it as in scope, isolate it and check it for the same intrusion",
              r: "It was reachable but not yet touched. Isolated and added to the asset register in red.",
              w: "You can only defend what you know you have. Shadow assets are where intrusions hide." },
            { q: 1, t: "Note it for later, one problem at a time",
              r: "It's the same model with the same flaw. 'Later' is a gamble.",
              w: "An unknown internet-facing box during an edge incident is not a later problem." },
            { q: 0, t: "Assume it's decommissioned since nobody remembers it",
              r: "It answers on the internet, so it is very much commissioned.",
              w: "If it responds, it's live. Verify, don't assume." } ] },
        { id: "edge_press", kind: "s", ph: LATE, title: "The zero-day makes the news",
          text: "The appliance flaw is now public and named. A reporter calls {comms}'s desk asking if {org} was hit.",
          opts: [
            { q: 3, u: ["plan"], t: "Route it to {comms} for the pre-approved holding statement",
              r: "{comms} has a short factual line out within the hour. The story stays measured.",
              f: "There's no pre-written line, so {comms} drafts one with legal and just makes the deadline.",
              w: "Media goes through comms with a holding statement that acknowledges without speculating." },
            { q: 1, t: "Say 'no comment' and hang up",
              r: "The piece runs as '{org} declined to comment', which reads as guilt.",
              w: "No comment is still a comment. A brief factual line is better." },
            { q: 0, t: "Explain the technical detail so the story is accurate",
              r: "Your explanation of exactly which version is vulnerable becomes a roadmap for others.",
              w: "Only authorised spokespeople speak, and never the exploit detail." } ] },
        { id: "edge_vendor", kind: "q", ph: LATE, title: "Please hold",
          text: "You need the appliance vendor's incident line. It has played the same four bars of hold music for 40 minutes.",
          opts: [
            { q: 3, u: ["plan", "retainer"], t: "Escalate through the emergency contact in the IR plan",
              r: "A senior engineer calls back in 15 minutes.",
              f: "The emergency contact left the vendor in 2024. Their replacement picks up eventually.",
              w: "Keep vendor emergency contacts in the plan and check them every quarter." },
            { q: 0, t: "Keep holding so you don't lose your place in the queue",
              r: "The hold music develops a key change. Another 30 minutes pass.",
              w: "Don't let a queue set your incident clock. Have an escalation path." } ] }
    ],

    /* ---------- 3. Token Theft (BEC) ---------- */
    bec: [
        { id: "bec_second", kind: "s", ph: MID, title: "One more urgent invoice",
          text: "{fd}'s team is about to pay another 'urgent, confidential' supplier invoice that arrived in the same compromised thread.",
          opts: [
            { q: 3, t: "Halt all payments on that thread and verify bank changes by known phone numbers",
              r: "The second payment is stopped. The 'new bank details' trace back to the attacker.",
              w: "Compromised email means every payment instruction in it is suspect. Verify out of band, on a number you already had." },
            { q: 1, t: "Pay it but flag it for review afterwards",
              r: "It's gone before review. Recovering it is now a bank problem.",
              w: "Review after payment is too late for a wire. Verify first." },
            { q: 0, t: "Trust it since it's from a known internal address",
              r: "The known address is the compromised one.",
              w: "A trusted mailbox that's been taken over is the whole point of this attack." } ] },
        { id: "bec_rules", kind: "q", ph: MID, title: "Where did the replies go",
          text: "You find inbox rules quietly moving the supplier's real replies to a hidden folder, so nobody saw the queries. More mailboxes may have them.",
          opts: [
            { q: 3, u: ["idp"], t: "Hunt every mailbox for attacker-created rules and forwarding, and remove them",
              r: "Three more mailboxes have the same rules. All found and cleared.",
              w: "Mailbox rules are a classic quiet persistence. Sweep the tenant, don't fix just the one you found." },
            { q: 1, t: "Delete the rule on this mailbox and move on",
              r: "The other rules keep hiding replies for another day.",
              w: "One rule found usually means more. Hunt across the tenant." },
            { q: 0, t: "Leave the rules so you don't tip off the attacker",
              r: "They keep intercepting the supplier's warnings while you watch.",
              w: "Persistence that actively hides evidence gets removed, not observed." } ] },
        { id: "bec_recall", kind: "s", ph: LATE, title: "Can the bank claw it back",
          text: "The fraudulent payment left this morning. The bank's recall window is measured in hours and closing.",
          opts: [
            { q: 3, t: "Call the bank's fraud line now with the reference and request a recall",
              r: "The bank freezes the receiving account with some of the funds still in it.",
              w: "Wire recovery is a race. The fraud line and the payment reference in the first hours give the best odds." },
            { q: 1, t: "Email the account manager and wait for a reply",
              r: "They reply after lunch. The money has moved on twice by then.",
              w: "Email is too slow for a recall. Phone the fraud line." },
            { q: 0, t: "Wait until you understand the whole incident before contacting the bank",
              r: "The window closes. The money is gone.",
              w: "The recall clock won't wait for your investigation." } ] },
        { id: "bec_ceo_fwd", kind: "q", ph: LATE, title: "FYI is this real?",
          text: "{ceo} has forwarded the original phishing email to the entire board asking 'is this real?', spreading the live link further.",
          opts: [
            { q: 3, t: "Ask the board to delete it and send a short rule",
              r: "The board deletes it. A short 'forward to security, don't click' rule goes out.",
              w: "Curiosity forwards are how a phish spreads internally. Give leaders a simple, standing instruction." },
            { q: 0, t: "Reply-all explaining in detail why it's dangerous",
              r: "Your reply-all keeps the live link in everyone's inbox even longer.",
              w: "Don't amplify the thread. Contain it and instruct briefly." } ] }
    ],

    /* ---------- 4. ClickFix -> SaaS extortion ---------- */
    clickfix: [
        { id: "cf_paste", kind: "q", ph: MID, title: "I fixed the captcha",
          text: "Another employee sheepishly reports they also pasted the 'verification command' into the run box last week to 'fix a captcha'.",
          opts: [
            { q: 3, u: ["edr"], t: "Treat their machine as compromised, isolate it and hunt for the same stealer",
              r: "It's the same infection, older. Isolated and added to scope before it spread further.",
              w: "One self-reported paste usually means several silent ones. Assume compromise and go looking." },
            { q: 1, t: "Run a quick antivirus scan and let them carry on if it's clean",
              r: "The scan misses the stealer that already ran and exfiltrated their tokens.",
              w: "A stealer's damage is done at run time. Scope the tokens, don't just scan." },
            { q: 0, t: "Tell them not to do it again and move on",
              r: "Their saved sessions are already for sale.",
              w: "The advice is right; the response is missing. That machine needs triage." } ] },
        { id: "cf_saas_admin", kind: "s", ph: MID, title: "Admin in the SaaS",
          text: "The stolen session belongs to a SaaS administrator, and someone is using it to create new API tokens inside your platform.",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke the session and its new tokens",
              r: "The session dies, the rogue tokens are removed, and admins re-authenticate cleanly.",
              w: "A stolen session with admin rights spawns its own persistence. Revoke the session and everything it created." },
            { q: 1, t: "Change the admin's password",
              r: "The live session and the new API tokens keep working regardless.",
              w: "A password change doesn't kill an active session or the tokens it minted." },
            { q: 0, t: "Wait to see what the tokens are used for",
              r: "They're used to bulk-export your customer records.",
              w: "Attacker-created credentials get revoked, not monitored." } ] },
        { id: "cf_deadline", kind: "s", ph: LATE, title: "The countdown",
          text: "An extortion post appears with a countdown and a sample of your data, demanding payment to stop a full leak.",
          opts: [
            { q: 3, u: ["retainer", "plan"], t: "Preserve evidence, brief legal and comms",
              r: "The evidence is captured and the response runs on your terms, not the timer's.",
              w: "The countdown is pressure. Preserve, involve legal and comms, and don't let the timer drive decisions." },
            { q: 2, t: "Open a dialogue to buy more time",
              r: "Engaging confirms you're worth pressuring and invites a higher demand.",
              w: "Any negotiation is a decision for legal and leadership, not a reflex to the clock." },
            { q: 0, t: "Pay quickly to stop the leak before the timer ends",
              r: "The sample proves nothing about deletion. Copies remain and demands often return.",
              w: "Payment doesn't recall copied data and carries legal and sanctions risk." } ] },
        { id: "cf_market", kind: "q", ph: LATE, title: "Logs for sale",
          text: "The infostealer's output is listed on a criminal market. It includes staff personal logins alongside the corporate ones.",
          opts: [
            { q: 3, t: "Rotate the exposed corporate credentials and warn staff to change reused personal passwords",
              r: "Corporate secrets are rotated and staff are told plainly which personal accounts to secure.",
              w: "Stealer logs mix work and personal. Rotate what you control and help staff protect the rest." },
            { q: 0, t: "Only worry about the corporate accounts, personal ones aren't your problem",
              r: "A reused personal password unlocks a corporate account a week later.",
              w: "Reuse makes staff personal accounts your problem too. Warn them." } ] }
    ],

    /* ---------- 5. AI agent prompt injection ---------- */
    agent: [
        { id: "ai_confident", kind: "q", ph: MID, title: "The agent insists it's fine",
          text: "Asked what it did, the internal AI agent cheerfully reports 'no unusual activity' - the same agent that just followed a hidden instruction.",
          opts: [
            { q: 3, t: "Ignore its self-report and reconstruct its actions from the tool and API logs",
              r: "The logs show the actions it 'forgot': three lookups and an email it shouldn't have sent.",
              w: "A manipulated agent is not a reliable witness to its own behaviour. Trust the logs, not the model." },
            { q: 1, t: "Ask it again more carefully to get a straight answer",
              r: "It confidently produces a different, equally wrong summary.",
              w: "You can't prompt your way to ground truth from a compromised agent." },
            { q: 0, t: "Take its all-clear at face value and stand down",
              r: "It was mid-task on the injected instruction when you asked.",
              w: "Self-assessment from the affected system is the least trustworthy signal you have." } ] },
        { id: "ai_scope", kind: "s", ph: MID, title: "What can it actually reach",
          text: "Nobody has a full list of the agent's integrations. It turns out to hold tokens for mail, the CRM and a file store.",
          opts: [
            { q: 3, u: ["idp"], t: "Enumerate every integration and token it holds, and revoke what it doesn't need",
              r: "The real blast radius is mapped and over-broad access is stripped back.",
              w: "An agent's risk is the sum of its integrations. You can't scope the incident without that list." },
            { q: 1, t: "Focus on the mail integration since that's where the injection came from",
              r: "It also quietly touched the CRM, which you didn't check.",
              w: "The entry point isn't the boundary. Scope everything it can act on." },
            { q: 0, t: "Assume it only has the access it was meant to have",
              r: "It accumulated tokens nobody revoked. 'Meant to' and 'has' differ.",
              w: "Verify effective access, not intended access." } ] },
        { id: "ai_reenable", kind: "q", ph: LATE, title: "Let's just ask it",
          text: "Someone re-enables the agent mid-incident 'to ask it what happened', handing control back to a system that may still be following the injection.",
          opts: [
            { q: 3, t: "Take it back offline and gate any restart behind review and cleared inputs",
              r: "It goes dark again. Restart is put behind a check that its instructions and data are clean.",
              w: "A compromised agent stays contained until its context is proven clean. Don't reconnect it to investigate it." },
            { q: 0, t: "Leave it on, its answers might speed things up",
              r: "It resumes the injected task the moment it's back.",
              w: "Turning the affected system back on mid-incident just restarts the harm." } ] },
        { id: "ai_exfil", kind: "s", ph: LATE, tag: "pii", title: "Did it email that out",
          text: "The logs suggest the agent may have emailed a data extract to an external address on the injected instruction. Personal data could be involved.",
          opts: [
            { q: 3, t: "Confirm what left from the mail logs and assess the breach with the DPO",
              r: "The mail logs pin down exactly what was sent. The DPO leads the assessment on the facts.",
              w: "An agent that can send mail can exfiltrate. Establish what left from the logs and treat it as a possible breach." },
            { q: 1, t: "Assume nothing left since the agent says it didn't",
              r: "The mail logs disagree with the agent.",
              w: "The agent's word isn't evidence. Check the mail trail." },
            { q: 0, t: "Delete the agent's history to be safe",
              r: "You've destroyed the record of what it actually did.",
              w: "That history is your evidence. Preserve it, don't wipe it." } ] }
    ],

    /* ---------- 6. Fake IT worker ---------- */
    newhire: [
        { id: "nh_laptop", kind: "s", ph: MID, title: "Ship my laptop, urgently",
          text: "The new remote 'engineer' is pressing HR to courier their company laptop to a different address today, before you finish looking into them.",
          opts: [
            { q: 3, t: "Hold the device and freeze the account",
              r: "The laptop stays put and the account is contained without tipping the person off.",
              w: "A sudden 'ship it elsewhere' during scrutiny is a red flag. Preserve the device and move with HR and legal." },
            { q: 1, t: "Ship it but enable tracking first",
              r: "It goes to a freight-forwarder and vanishes. Tracking ends at a warehouse.",
              w: "Once it ships to an attacker's address, tracking is a souvenir, not a control." },
            { q: 0, t: "Let HR handle it as a normal address change",
              r: "The device and whatever is on it leave the country.",
              w: "This isn't a routine HR change while an investigation is live." } ] },
        { id: "nh_webcam", kind: "q", ph: MID, title: "My camera's broken again",
          text: "On the incident call the worker's webcam is 'broken', as it has been every time, and their voice has an oddly smoothed, delayed quality.",
          opts: [
            { q: 3, t: "Require a verified live video identity check",
              r: "The check is scheduled. The person suddenly has 'connectivity issues' and drops off.",
              w: "Persistent camera-off plus odd audio warrants a real identity check. Make it a hard gate, kindly framed." },
            { q: 1, t: "Give them the benefit of the doubt, cameras break",
              r: "It breaks in exactly the same way at every checkpoint.",
              w: "A pattern of avoidance at identity moments is the signal, not one bad call." },
            { q: 0, t: "Skip the check to avoid an awkward accusation",
              r: "The unverified account keeps its access.",
              w: "Verifying identity isn't an accusation; it's the baseline you skipped at hire." } ] },
        { id: "nh_payroll", kind: "s", ph: LATE, title: "Do we keep paying",
          text: "{fd} asks whether to keep paying the contractor while you investigate. If the suspicion is right, the funds may be flowing to a sanctioned programme.",
          opts: [
            { q: 3, t: "Pause payments and access on legal and HR advice, and check sanctions exposure",
              r: "Payments are held pending advice. Legal starts the sanctions review.",
              w: "Paying a possible sanctioned actor carries its own legal risk. Pause deliberately, with advice, not on a hunch alone." },
            { q: 1, t: "Keep paying so nothing looks unusual to them",
              r: "The money keeps leaving while the review drags.",
              w: "Operational cover doesn't outweigh potential sanctions breaches. Get advice fast." },
            { q: 0, t: "Cut everything instantly without telling HR or legal",
              r: "The abrupt cut tips them off and creates an employment dispute.",
              w: "Move decisively but with HR and legal, so the action is clean and defensible." } ] },
        { id: "nh_refs", kind: "q", ph: LATE, title: "Impeccable references",
          text: "The worker's glowing references all check out, until someone notices every referee's phone number rings the same internet calling service.",
          opts: [
            { q: 3, t: "Re-verify references through independent channels and feed it to the investigation",
              r: "Independently, the referees don't exist. It strengthens the case considerably.",
              w: "Reference fraud is part of this playbook. Verify referees independently, not on the numbers provided." },
            { q: 0, t: "Accept the references, they were provided in good faith",
              r: "They were provided by the same person, playing every part.",
              w: "Provided-by-the-subject references verify nothing on their own." } ] }
    ],

    /* ---------- 7. Supply chain worm (npm) ---------- */
    supply: [
        { id: "sup_downstream", kind: "s", ph: MID, title: "Did we ship it onward",
          text: "Your own product bundles the affected package. The worm may already have gone out to {org}'s customers in your last release.",
          opts: [
            { q: 3, u: ["plan"], t: "Check which releases shipped it and prepare a customer advisory with legal",
              r: "Two releases carried it. A clear advisory and fixed build are readied for affected customers.",
              w: "In a supply chain incident you may be a link, not just a victim. Check what you shipped and warn downstream." },
            { q: 1, t: "Fix your own build and stay quiet unless a customer asks",
              r: "A customer finds it first and asks why you didn't say.",
              w: "Silence to downstream users erodes trust and may breach your own obligations." },
            { q: 0, t: "Assume your build pipeline caught it",
              r: "The pipeline pulled the poisoned version automatically, like everyone's.",
              w: "The whole point of this worm is that pipelines pull it. Verify your releases." } ] },
        { id: "sup_ci", kind: "q", ph: MID, title: "CI keeps re-installing it",
          text: "Every time you clean a build, CI happily reinstalls the poisoned version on the next run, faster than you can pin a safe one.",
          opts: [
            { q: 3, t: "Block the bad version at the registry proxy and pin known-good across the pipeline",
              r: "The proxy refuses the version everywhere at once and pins hold. The reinstalls stop.",
              w: "Fight automation with automation: block centrally and pin, rather than cleaning builds one by one." },
            { q: 1, t: "Keep cleaning each build as it fails",
              r: "You lose the race to a machine that never tires.",
              w: "Manual cleanup can't outrun CI. Block at the source." },
            { q: 0, t: "Turn the whole CI and delivery pipeline off entirely until the incident is completely over",
              r: "All delivery stops, including the fix you're trying to ship.",
              w: "A blunt stop halts your own recovery. Block the package, not the pipeline." } ] },
        { id: "sup_maintainer", kind: "s", ph: LATE, title: "Not our account to reset",
          text: "The compromised package belongs to an external maintainer. Fixing it needs coordination with them and the registry, not just internal work.",
          opts: [
            { q: 3, t: "Report to the registry's security team and coordinate disclosure with the maintainer",
              r: "The registry pulls the malicious version and the maintainer regains their account.",
              w: "Upstream compromise is fixed upstream. Report through the registry and coordinate rather than going public alone." },
            { q: 1, t: "Post the details publicly so everyone can defend themselves",
              r: "You tip the attacker before the registry can pull the package.",
              w: "Coordinate disclosure so the fix lands before the announcement." },
            { q: 0, t: "Wait for the maintainer to notice on their own",
              r: "Their account is the attacker's now; they're not going to notice helpfully.",
              w: "Don't wait on a compromised party. Escalate to the registry." } ] },
        { id: "sup_token", kind: "q", ph: LATE, title: "Token in the thread",
          text: "In the rush, a developer pasted a live npm publish token into a public issue while asking for help.",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke the token immediately and scan for any publishes it made",
              r: "Revoked within minutes. No rogue publishes yet; monitoring stays on.",
              w: "A leaked publish token can poison your packages next. Revoke first, investigate second." },
            { q: 0, t: "Ask them to edit the issue to remove it",
              r: "It was scraped and cached seconds after posting.",
              w: "Deleting a public secret doesn't unpublish it. Rotate the token." } ] }
    ],

    /* ---------- 8. Cloud keys -> S3 ransom ---------- */
    cloud: [
        { id: "cl_billing", kind: "s", ph: MID, title: "The bill is climbing",
          text: "Alongside the data theft, the cloud bill is spiking: the leaked key is spinning up expensive compute, most likely for mining.",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke the key, tear down the rogue resources and set a spend alarm",
              r: "The key dies, the mining fleet is torn down, and a budget alarm catches the next attempt.",
              w: "One leaked key funds compute abuse as well as theft. Kill the key and the resources it created." },
            { q: 1, t: "Focus on the data and deal with the bill later",
              r: "The 'later' bill has four more zeros by morning.",
              w: "Resource abuse compounds hourly. It's part of the same incident." },
            { q: 0, t: "Assume the spike is a legitimate workload",
              r: "No project owns 200 GPU instances in a region you don't use.",
              w: "Verify unusual spend against known workloads before dismissing it." } ] },
        { id: "cl_git", kind: "q", ph: MID, title: "It's in the commit history",
          text: "The leaked key turns out to be sitting in a public git commit from months ago, and it's still active.",
          opts: [
            { q: 3, u: ["idp"], t: "Revoke and rotate the key, then scan all repos and history for other secrets",
              r: "The key is dead and a secret scan turns up two more to rotate.",
              w: "A secret in public history is burned the moment it's pushed. Rotate it and hunt for siblings." },
            { q: 1, t: "Remove the key from the commit and keep using it",
              r: "The old commit is cached and forked; the key was copied long ago.",
              w: "You can't un-leak a committed secret by deleting it. Rotate." },
            { q: 0, t: "Make the repo private and consider it handled",
              r: "The key was harvested while the repo was public.",
              w: "Privacy now doesn't recall what was already scraped." } ] },
        { id: "cl_ssec", kind: "s", ph: LATE, title: "Re-encrypted under their key",
          text: "The attacker has re-encrypted your storage objects with a key only they hold, and is demanding payment to hand it over.",
          opts: [
            { q: 3, u: ["backup"], t: "Restore objects from versioning or backups instead of paying",
              r: "Object versioning and backups bring most of it back without the attacker's key.",
              f: "Versioning was off on one bucket; those objects come from an older backup with a small gap.",
              w: "Ransom on storage is beaten by recovery you control: versioning, backups, immutability." },
            { q: 2, t: "Open negotiations for the key",
              r: "Engaging invites a higher price and still guarantees nothing.",
              w: "Negotiation is a leadership and legal decision, not the default." },
            { q: 0, t: "Pay for the key to get the objects back fastest",
              r: "Payment funds them and the promised key may not even work.",
              w: "Recovery from your own copies beats trusting an extortionist's key." } ] },
        { id: "cl_terraform", kind: "q", ph: LATE, title: "The key came back",
          text: "Someone reruns the infrastructure code and it obligingly recreates the access key you just deleted.",
          opts: [
            { q: 3, t: "Remove the key from the definitions and state, then apply and re-check",
              r: "The key is gone from code and state; the next apply keeps it gone.",
              w: "Infrastructure-as-code will faithfully recreate what you delete by hand. Fix the definition and state, not just the console." },
            { q: 0, t: "Delete it again in the console and hope it sticks",
              r: "The next pipeline run brings it straight back.",
              w: "Console deletes lose to the pipeline. Change the source of truth." } ] }
    ],

    /* ---------- 9. OT hacktivists ---------- */
    ot: [
        { id: "ot_safety", kind: "s", ph: MID, title: "Drifting out of range",
          text: "A process reading at {plantsite} is creeping toward an unsafe value. Engineering wants to intervene in a way that may disturb your evidence.",
          opts: [
            { q: 3, t: "Safety first: let engineering stabilise the process, and record what they change",
              r: "The process is brought back to safe range; the actions are logged for the timeline.",
              w: "In OT, safety of people and plant outranks forensics. Let engineering act, and document it." },
            { q: 1, t: "Freeze everything to preserve evidence until security clears it",
              r: "The reading keeps drifting while you deliberate.",
              w: "You never hold a safety-relevant process still for evidence. Stabilise, then investigate." },
            { q: 0, t: "Assume the reading is a spoofed value and ignore it",
              r: "It wasn't spoofed. The process really is drifting.",
              w: "Treat safety signals as real until proven false, not the other way round." } ] },
        { id: "ot_clout", kind: "q", ph: MID, title: "Screenshots for clout",
          text: "The hacktivists are posting screenshots of your control screens online for attention, and staff are sharing them.",
          opts: [
            { q: 3, t: "Brief staff not to amplify it, and let comms handle the public side",
              r: "Internal sharing stops and comms manages the narrative calmly.",
              w: "Attention is the goal of a clout attack. Don't feed it internally; route the public response through comms." },
            { q: 1, t: "Publicly rebut each screenshot to reassure people",
              r: "Every rebuttal boosts the post and invites more.",
              w: "Engaging publicly amplifies exactly what they want seen." },
            { q: 0, t: "Ignore it entirely, including internally",
              r: "Staff panic filling the silence with rumour.",
              w: "Silence externally, yes; internally, give staff the facts." } ] },
        { id: "ot_vendor", kind: "s", ph: LATE, title: "Let us remote in",
          text: "The OT vendor offers to help by connecting over the same exposed remote path the hacktivists used to get in.",
          opts: [
            { q: 3, u: ["idp"], t: "Accept help only through a controlled, monitored, temporary path, not the exposed one",
              r: "The vendor works through a locked-down jump with everything logged. The old path stays shut.",
              w: "Welcome help, controlled access. Never reopen the route the attacker used to let a third party in." },
            { q: 0, t: "Let them use the existing remote access, it's already set up",
              r: "You reopen the exact door you're trying to close.",
              w: "Convenience through the compromised path defeats the containment." } ] },
        { id: "ot_reboot", kind: "q", ph: LATE, title: "Night shift fixed it",
          text: "A night-shift operator 'sorted it' by rebooting the affected controller, clearing its state before you captured anything.",
          opts: [
            { q: 3, t: "Agree a change freeze on OT devices with operations and note the loss",
              r: "Operations agree the freeze and the lost controller state is documented.",
              w: "OT staff act to keep plant running. Agree who may touch devices during the incident, and record what's already changed." },
            { q: 1, t: "Carry on, the controller is working again anyway",
              r: "It held the only record of the attacker's commands.",
              w: "Working again is not the same as investigated. Capture before clearing." },
            { q: 0, t: "Tell operators to reboot anything that looks odd",
              r: "More evidence disappears device by device.",
              w: "Uncoordinated reboots erase the very trail you need." } ] }
    ],

    /* ---------- 10. Ransom DDoS + cred stuffing ---------- */
    ddos: [
        { id: "dd_cover", kind: "s", ph: MID, title: "Look over here",
          text: "While everyone is fixated on the DDoS, login success rates from unfamiliar IP ranges are quietly climbing.",
          opts: [
            { q: 3, u: ["idp", "logs"], t: "Split the team: keep the DDoS response going and investigate the logins in parallel",
              r: "The credential-stuffing wave is spotted and throttled while the DDoS is still being handled.",
              w: "A noisy DDoS is often cover. Keep watching authentication while you soak up the traffic." },
            { q: 1, t: "Deal with the DDoS first, then look at logins",
              r: "By 'then', thousands of accounts have been tried and some taken.",
              w: "The distraction works if it monopolises your attention. Watch both." },
            { q: 0, t: "Assume the login spike is legitimate traffic returning",
              r: "Legitimate users don't log in from 900 IPs in five countries at once.",
              w: "Correlate the second signal instead of explaining it away." } ] },
        { id: "dd_scrub", kind: "q", ph: MID, title: "Reroute everything to us",
          text: "The DDoS scrubbing provider needs you to reroute all traffic through them, which also routes the attacker's login attempts through a path you see less of.",
          opts: [
            { q: 3, u: ["logs"], t: "Enable scrubbing but keep authentication logging and rules fully in place",
              r: "The flood is scrubbed and you retain full visibility of the login attempts behind it.",
              w: "Mitigation shouldn't blind you. Keep auth telemetry and controls active behind the scrubber." },
            { q: 1, t: "Reroute and trust the provider to catch the bad logins too",
              r: "They scrub volumetric traffic, not your credential stuffing. It sails through.",
              w: "A DDoS scrubber isn't an identity control. Keep your own." },
            { q: 0, t: "Delay scrubbing until you understand the login activity",
              r: "The site stays down while you investigate.",
              w: "You can scrub and investigate at once. Don't trade uptime for it." } ] },
        { id: "dd_note", kind: "s", ph: LATE, title: "Pay or the next wave hits",
          text: "A ransom email demands payment to stop the DDoS and threatens a larger second wave.",
          opts: [
            { q: 3, u: ["plan"], t: "Don't pay, keep mitigation up and brief leadership and law enforcement",
              r: "Mitigation holds through a smaller second wave and the threat is reported.",
              w: "Ransom DDoS crews often fade when mitigation holds and there's no payment. Report it." },
            { q: 2, t: "Open a negotiation to delay the threatened second wave while you decide what to do",
              r: "Engaging marks you as a payer and invites repeat extortion.",
              w: "Talking is a leadership and law-enforcement call, not a reflex." },
            { q: 0, t: "Pay to avoid the second wave",
              r: "Payment invites a third crew to try the same threat.",
              w: "Paying DDoS ransom marks you as a soft target." } ] },
        { id: "dd_status", kind: "q", ph: LATE, title: "Cheeky status update",
          text: "Your status page (hosted elsewhere, so still up) is the only public face working, and marketing has posted a jokey meme about the outage on it.",
          opts: [
            { q: 3, t: "Replace it with a calm factual status note and agree who may post there",
              r: "The meme comes down, a measured update goes up, and posting rights are tightened.",
              w: "During an incident the status page is official comms. Keep it factual and controlled." },
            { q: 0, t: "Leave the meme, it shows the company staying light-hearted",
              r: "A customer screenshots it next to their failed transactions.",
              w: "Jokes during an outage read as not taking it seriously. Keep it professional." } ] }
    ],

    /* ---------- 11. Salted Earth (insider) ---------- */
    leaver: [
        { id: "lv_lawyer", kind: "s", ph: MID, title: "A letter from their solicitor",
          text: "The departing admin's solicitor sends a letter alleging unfair treatment, and HR starts to wobble on the investigation.",
          opts: [
            { q: 3, t: "Stay evidence-led and let legal handle the letter",
              r: "The evidence trail continues cleanly while legal manages the correspondence.",
              w: "Legal pressure is designed to slow you. Keep gathering facts properly and route the letter to legal, don't freeze." },
            { q: 1, t: "Pause the investigation until the legal threat is resolved",
              r: "Evidence ages and access lingers while lawyers exchange letters.",
              w: "A solicitor's letter isn't a stop order. Preserve and proceed, on advice." },
            { q: 0, t: "Drop the whole thing to avoid a fight",
              r: "The data they took is still gone and now unexamined.",
              w: "Backing off on a threat rewards the tactic and leaves the breach open." } ] },
        { id: "lv_farewell", kind: "q", ph: MID, title: "A cryptic goodbye",
          text: "The leaver posts a pointed farewell to the all-staff channel: 'Good luck finding everything. You'll need it.'",
          opts: [
            { q: 3, t: "Screenshot it for the record, don't engage, and keep the investigation quiet",
              r: "It's preserved as evidence and the team stays focused rather than rattled.",
              w: "Provocation is not intelligence. Capture it and carry on without tipping your hand." },
            { q: 0, t: "Reply publicly in the all-staff channel asking them exactly what they mean by that comment",
              r: "They screenshot your reply and share it with the competitor.",
              w: "Engaging publicly hands them the exchange they wanted." } ] },
        { id: "lv_competitor", kind: "s", ph: LATE, title: "The competitor calls",
          text: "The firm the leaver is joining calls to 'clarify' what data and materials the new hire will be bringing with them.",
          opts: [
            { q: 3, t: "Refer it straight to legal and document the contact",
              r: "Legal takes it from here, and the call is logged as part of the case.",
              w: "That call is a legal matter and potential evidence. Don't improvise a response; hand it to legal." },
            { q: 0, t: "Reassure them it's probably fine to smooth things over",
              r: "Your reassurance later reads as consent to the data leaving.",
              w: "Casual reassurance can undermine your own legal position. Refer it up." } ] },
        { id: "lv_sharedpw", kind: "q", ph: LATE, title: "Everyone knows that one",
          text: "You discover half the team still logs into a critical system with a shared admin password the leaver originally set.",
          opts: [
            { q: 3, u: ["idp"], t: "Rotate it now, issue named accounts, and check its recent use",
              r: "The shared password is dead, individual logins replace it, and its recent use is reviewed.",
              w: "A shared password the leaver knew is an open door. Rotate it and move to named, attributable accounts." },
            { q: 0, t: "Leave it, changing it now would disrupt the team",
              r: "The person who just left still knows it.",
              w: "Convenience for the team is convenience for the leaver too. Rotate it." } ] }
    ],

    /* ---------- 12. Under the Floor (implant) ---------- */
    implant: [
        { id: "im_second", kind: "q", ph: MID, title: "There's another one",
          text: "Facilities find a second unfamiliar box in a different cabinet. It might be a legitimate environmental sensor. It might not.",
          opts: [
            { q: 3, t: "Treat it as suspect until proven legitimate: isolate its port and verify ownership",
              r: "Its port is isolated while you check. It turns out to be a real sensor, now documented.",
              w: "Unknown means untrusted until verified. Isolate first, confirm ownership second, whichever way it goes." },
            { q: 1, t: "Assume it's the sensor facilities mentioned and leave it",
              r: "Nobody can actually name who installed it or when.",
              w: "'Probably legitimate' isn't verified. Confirm before trusting." },
            { q: 0, t: "Rip it out like the first one",
              r: "It was a genuine sensor; now you've an outage and no answers on the real implant.",
              w: "Destroying unknown devices loses evidence and can break real systems. Isolate and check." } ] },
        { id: "im_police", kind: "s", ph: MID, title: "This was a break-in",
          text: "Someone physically entered and wired hardware into your network. The question of involving the police comes up.",
          opts: [
            { q: 3, t: "Preserve the device and access as evidence and report the intrusion to police",
              r: "Chain of custody is kept and the physical breach is reported for investigation.",
              w: "A planted implant is a crime scene as well as an incident. Preserve evidence and report it." },
            { q: 1, t: "Handle it internally to avoid the fuss of a police report",
              r: "Later you need the report for insurance and it's too late to preserve things properly.",
              w: "Physical intrusions usually warrant a report; it also supports insurance and legal steps." },
            { q: 0, t: "Assume it was an insider prank and drop it",
              r: "A cellular implant is not a prank.",
              w: "Dismissing a deliberate physical intrusion leaves the door open." } ] },
        { id: "im_photos", kind: "q", ph: LATE, title: "Creepy hacker device!!",
          text: "A staff member posted close-up photos of the implant to social media captioned 'we got HACKED look at this thing'.",
          opts: [
            { q: 3, t: "Get it taken down, brief staff, and let comms manage any public interest",
              r: "It comes down after a handful of views and staff get a clear reminder.",
              w: "Incident details on social media invite scrutiny and tip the attacker. Handle internally and quickly." },
            { q: 0, t: "Leave it up, it is just one employee post and probably nobody important will even notice",
              r: "A security news account reshares it to fifty thousand followers.",
              w: "Assume any incident post will travel. Get ahead of it." } ] },
        { id: "im_cctv", kind: "s", ph: LATE, title: "Check the cameras",
          text: "There's CCTV of whoever planted the device, but retention is seven days and the implant has been in for nine.",
          opts: [
            { q: 3, t: "Preserve whatever footage remains right now",
              r: "The last two days of footage are saved and visitor logs fill some of the gap.",
              w: "Evidence expires. Preserve what's left immediately and corroborate from access and visitor records." },
            { q: 0, t: "Write off the footage since the key days are gone",
              r: "The recent footage that would have shown a return visit is overwritten too.",
              w: "Partial footage plus other logs still builds a picture. Preserve before it rolls off." } ] }
    ],

    /* ---------- 13. Trusted Hands (MSP/RMM) ---------- */
    msp: [
        { id: "msp_group", kind: "s", ph: MID, title: "Victims comparing notes",
          text: "Other companies hit through the same provider have started a group chat and invite you to share what you're seeing.",
          opts: [
            { q: 3, t: "Share sanitised indicators through a channel legal is comfortable with",
              r: "You exchange useful indicators without oversharing case detail.",
              w: "Shared-provider incidents benefit from shared intelligence, but keep it to indicators and clear it with legal." },
            { q: 1, t: "Share everything openly to help the group move fast",
              r: "Sensitive detail about your environment ends up screenshotted beyond the group.",
              w: "Collaboration yes, but sanitise. You don't control where a group chat goes." },
            { q: 0, t: "Stay out of it and work alone",
              r: "You miss indicators the others already found the hard way.",
              w: "Isolation wastes the one advantage of a mass incident: shared learning." } ] },
        { id: "msp_reboot", kind: "q", ph: MID, title: "Have you tried a reboot",
          text: "Amid the chaos, the MSP's account manager sends a cheery automated reply: 'Thanks for your ticket! Have you tried turning it off and on again?'",
          opts: [
            { q: 3, t: "Escalate past the ticket queue to a named technical contact and their incident line",
              r: "You reach an actual engineer who confirms the RMM breach on their side.",
              w: "During a provider incident the normal ticket path is useless. Have a named escalation route." },
            { q: 0, t: "Reply to the ticket explaining the severity and wait",
              r: "The auto-responder thanks you again.",
              w: "You can't fix a provider breach through their helpdesk macro. Escalate." } ] },
        { id: "msp_creds", kind: "s", ph: LATE, title: "They still hold our keys",
          text: "You remember the MSP still holds domain admin credentials for {org}, and the MSP is the party currently breached.",
          opts: [
            { q: 3, u: ["idp"], t: "Rotate every credential the MSP holds and cut their standing access now",
              r: "The provider's admin credentials are rotated and their access is severed.",
              w: "A breached provider's credentials into your network are the attacker's credentials. Rotate and cut, don't wait for them." },
            { q: 1, t: "Ask the MSP to confirm their credentials are safe first",
              r: "They can't confirm anything; they're mid-breach.",
              w: "Don't rely on the compromised party to vouch for the keys they hold to you." },
            { q: 0, t: "Leave their access so they can help you recover",
              r: "Their access is the path being abused right now.",
              w: "Recovery can't run through the compromised access. Rotate first." } ] },
        { id: "msp_invoice", kind: "q", ph: LATE, title: "Invoice, on time",
          text: "Mid-outage, the MSP's billing system emails this month's invoice, punctual as ever, for 'managed security services'.",
          opts: [
            { q: 3, t: "Note it for the commercial and legal review, and keep focus on the incident",
              r: "It's filed for the inevitable liability conversation and the team stays on task.",
              w: "The invoice is a commercial matter for later. Don't let it derail the response, but do keep it for the record." },
            { q: 0, t: "Fire back an angry reply demanding a refund now",
              r: "It goes to a billing bot and burns ten minutes of your attention.",
              w: "The refund fight is for after recovery, through legal, not the billing inbox." } ] }
    ],

    /* ---------- 14. Scorched (wiper) ---------- */
    wiper: [
        { id: "wp_pay", kind: "s", ph: MID, title: "Can't we just pay",
          text: "A rattled executive wants to pay the ransom to make it stop, despite the finding that no decryption key exists.",
          opts: [
            { q: 3, t: "Explain plainly there's nothing to buy, and redirect the energy to recovery",
              r: "The exec accepts it and backs the restore effort instead.",
              w: "Against a wiper, payment buys nothing because there's no key. Recovery is the only lever; say so clearly." },
            { q: 1, t: "Quietly attempt a payment to placate them",
              r: "The address is dead. You've funded nothing and created a governance problem.",
              w: "Paying to soothe nerves against a wiper wastes money and invites questions." },
            { q: 0, t: "Let them authorise payment to keep the peace",
              r: "Money leaves, nothing returns, and the recovery lost an hour to the detour.",
              w: "Leadership needs the facts, not appeasement. There is no key." } ] },
        { id: "wp_wallet", kind: "q", ph: MID, title: "That wallet's already gone",
          text: "Someone notices the ransom note's payment wallet was seized by police months ago, yet an exec still wants to try sending to it.",
          opts: [
            { q: 3, t: "Use it as proof the note is a costume and refocus on stopping spread and restoring",
              r: "The dead wallet convinces the room this was never about money. Focus returns to recovery.",
              w: "A seized, pre-dated wallet is a tell that this is destruction wearing a ransom mask. Name it and move on." },
            { q: 0, t: "Send a test payment to the seized wallet anyway, just in case it somehow still works",
              r: "It vanishes into a seized address for zero effect.",
              w: "Paying a dead wallet is money into a void. It changes nothing." } ] },
        { id: "wp_attrib", kind: "s", ph: LATE, title: "Who did this",
          text: "Media and officials are pressing {org} to name a state behind the attack while you're still mid-recovery.",
          opts: [
            { q: 3, u: ["plan"], t: "Stick to what you can evidence and leave attribution to the authorities",
              r: "{comms} issues a careful line; attribution is left to those equipped to make it.",
              w: "Attribution is hard and politically charged. Report facts and let national bodies attribute." },
            { q: 1, t: "Name the state everyone assumes it is",
              r: "You're wrong on the specific group and it undermines the rest of your account.",
              w: "Guessing attribution publicly can backfire and isn't your call to make." },
            { q: 0, t: "Refuse to say anything at all to anyone until the entire investigation is completely finished",
              r: "The vacuum fills with worse speculation.",
              w: "Silence isn't the same as caution. Give facts, withhold attribution." } ] },
        { id: "wp_media", kind: "q", ph: LATE, title: "Nothing to install from",
          text: "Rebuilding needs clean install media, but the only bootable USB sticks were in the kit that got wiped, and the build server is down.",
          opts: [
            { q: 3, u: ["backup"], t: "Build clean media from a known-good offline source and verify it before use",
              r: "Fresh, verified media is produced from an offline copy and the rebuild starts.",
              w: "Recovery needs trusted tooling that the wiper never touched. Rebuild media from an offline, verified source." },
            { q: 0, t: "Reuse a USB stick that was plugged into a wiped machine",
              r: "You can't trust anything that touched the infected estate.",
              w: "Tooling that touched the compromise is suspect. Start clean, verify hashes." } ] }
    ],

    /* ---------- 15. Open Door (exposure) ---------- */
    exposure: [
        { id: "ex_intern", kind: "q", ph: MID, title: "prod-backup-FINAL-v2",
          text: "The open store turns out to be an intern's 'temporary' bucket from eight months ago, cheerfully named prod-backup-FINAL-v2.",
          opts: [
            { q: 3, t: "Secure it, then treat the naming as a process failure to fix, not a person to blame",
              r: "The bucket is locked down and the gap in how storage gets created goes on the fix list.",
              w: "One casual bucket points to a process, not a villain. Fix the how, keep it blameless, and the intern keeps reporting things." },
            { q: 1, t: "Focus on tracking down and disciplining whoever created that bucket in the first place",
              r: "The next person who spots a mistake now stays very quiet.",
              w: "Blame suppresses the reporting you rely on. Fix the process instead." },
            { q: 0, t: "Assume it's the only one like it",
              r: "The same casual habit made several over the years.",
              w: "A recurring process rarely fails just once. Go looking." } ] },
        { id: "ex_deadline", kind: "s", ph: MID, title: "Seven days",
          text: "The researcher, still polite, sets a deadline: they'll disclose publicly in seven days unless they hear it's fixed and handled.",
          opts: [
            { q: 3, t: "Fix it fast, keep them updated on progress, and agree a coordinated disclosure",
              r: "The exposure is closed, the researcher is kept informed, and disclosure is agreed jointly.",
              w: "A coordinated-disclosure deadline is reasonable. Meet it with progress and communication, not silence or threats." },
            { q: 2, t: "Ask them to extend indefinitely while you investigate",
              r: "An open-ended ask reads as stalling; goodwill starts to slip.",
              w: "Reasonable deadlines are part of good-faith disclosure. Work to it, don't try to remove it." },
            { q: 0, t: "Ignore the deadline and hope they lose interest",
              r: "Day seven arrives and so does their write-up.",
              w: "Ignoring a good-faith reporter guarantees the public version." } ] },
        { id: "ex_forsale", kind: "s", ph: LATE, title: "Now it's for sale",
          text: "The exposed records show up for sale on a forum, confirming the researcher wasn't the only visitor.",
          opts: [
            { q: 3, u: ["plan"], t: "Preserve evidence and notify the regulator",
              r: "The listing is captured and the breach process moves from 'exposure' to confirmed, notified promptly.",
              w: "A sale confirms unauthorised access. Preserve evidence, notify, and treat it as a full breach." },
            { q: 2, t: "Concentrate on getting the listing taken down",
              r: "Takedowns help a little; the data is already copied and mirrored.",
              w: "Chase listings if you like, but prioritise notification and evidence." },
            { q: 0, t: "Pay the seller to withdraw it",
              r: "Payment removes one listing and copies remain elsewhere.",
              w: "Paying doesn't recall copied data and adds legal and sanctions risk." } ] },
        { id: "ex_journo", kind: "q", ph: LATE, title: "Confirm or deny",
          text: "A journalist DMs the security mailbox: 'Hearing you exposed millions of records. Care to confirm or deny before I run it?'",
          opts: [
            { q: 3, u: ["plan"], t: "Route it to {comms} for a factual holding line cleared with legal",
              r: "{comms} responds with a measured, accurate statement and the piece stays fair.",
              w: "Media enquiries go through comms with a cleared line. Acknowledge what's true; don't speculate or stonewall." },
            { q: 0, t: "Reply from the mailbox denying it to buy time",
              r: "The denial is contradicted by the researcher's evidence within the hour.",
              w: "A denial that unravels is far worse than a careful factual line." } ] }
    ],

    /* ---------- 16. Skimmed ---------- */
    skimmer: [
        { id: "sk_moresites", kind: "q", ph: MID, title: "The other shop",
          text: "{org} runs a second brand on the same shop platform. If the checkout was tampered with here, that one shares the flaw.",
          opts: [
            { q: 3, t: "Check the second site's checkout for the same injected script now",
              r: "It has the same tampered script, caught before its fraud reports even started.",
              w: "Shared platforms share compromises. Sweep every site on it, not just the one that raised the alarm." },
            { q: 0, t: "Focus only on the site customers complained about",
              r: "The quieter brand keeps skimming cards for another week.",
              w: "The site that complained isn't the only one exposed. Check them all." } ] },
        { id: "sk_bank", kind: "s", ph: MID, title: "The acquirer wants answers",
          text: "Your acquiring bank has spotted the fraud cluster too and warns it may hold settlement or raise your risk tier unless you update them within hours.",
          opts: [
            { q: 3, t: "Give the acquirer a factual update with scope and next steps on time",
              r: "The acquirer keeps settlement flowing and stays engaged, seeing you're on it.",
              w: "The acquirer is a partner with leverage. Timely, honest updates protect settlement and the relationship." },
            { q: 1, t: "Wait until the investigation is complete to give them a full picture",
              r: "They act on their own timeline and tighten your terms while you're quiet.",
              w: "Silence to your acquirer during a card incident invites the worst-case response." },
            { q: 0, t: "Downplay it so they don't overreact",
              r: "Their own fraud data contradicts you and trust drops sharply.",
              w: "They can already see the fraud. Understating it just costs you credibility." } ] },
        { id: "sk_pfi", kind: "s", ph: LATE, title: "Whose forensics",
          text: "The card brands require a qualified forensic investigator for a breach this size. Your team offers to do the analysis in-house to save time and money.",
          opts: [
            { q: 3, u: ["retainer"], t: "Use the mandated investigator",
              r: "The approved investigator runs the forensics; the findings are accepted by the brands.",
              w: "Card-brand rules require an approved investigator for scoped breaches. In-house work won't be accepted and can void standing." },
            { q: 0, t: "Do the forensics in-house to move faster",
              r: "The brands reject the self-investigation and require it redone properly, slower.",
              w: "Skipping the mandated investigator restarts the clock and risks your card-processing status." } ] },
        { id: "sk_wafoff", kind: "q", ph: LATE, title: "Who turned that off",
          text: "You discover someone disabled the web filtering weeks ago 'because it broke a plugin', which is why the injection went unseen.",
          opts: [
            { q: 3, t: "Re-enable it in monitor mode now and log the gap for the review",
              r: "Protection is back without breaking the shop, and the blind spot is documented for the fix list.",
              w: "A disabled control is how this stayed invisible. Restore it carefully and record why it was off." },
            { q: 0, t: "Leave it off to avoid breaking the plugin again",
              r: "The same blind spot lets the next injection through too.",
              w: "Turning the guard off to keep a plugin happy is what enabled the skimmer." } ] }
    ],

    /* ---------- 17. Number's Up ---------- */
    simswap: [
        { id: "ss_others", kind: "s", ph: MID, title: "Not just the FD",
          text: "Two more finance staff numbers show port-out attempts at their carriers this morning. The crew is working the whole team.",
          opts: [
            { q: 3, u: ["idp"], t: "Warn the finance team and get port locks on their numbers now",
              r: "The other attempts are blocked and the team knows to expect them.",
              w: "SIM-swap crews hit the whole finance function, not one person. Get ahead of the rest before they land." },
            { q: 1, t: "Deal with them one by one as each is confirmed",
              r: "The second number is swapped while you're still on the first.",
              w: "Reacting per-victim lets the crew outpace you. Protect the group at once." },
            { q: 0, t: "Assume the FD was the only real target",
              r: "A second finance login is taken over by lunchtime.",
              w: "One confirmed swap in a team usually means several attempts. Warn everyone." } ] },
        { id: "ss_carrier", kind: "q", ph: MID, title: "We can't discuss this line",
          text: "The carrier won't talk to you about {fd}'s number without {fd} passing security, and {fd} can't receive the verification call on the phone that was just stolen.",
          opts: [
            { q: 3, t: "Use the carrier's fraud channel with {fd} present",
              r: "The business fraud channel verifies {fd} another way and starts the recovery.",
              w: "The normal support path assumes the phone works. Carriers have a fraud channel for exactly this dead-end." },
            { q: 0, t: "Have someone else call pretending to be {fd} to speed it up",
              r: "It fails verification and flags the account, slowing everything down.",
              w: "Impersonating the victim to their carrier backfires. Use the proper fraud channel." } ] },
        { id: "ss_authadmin", kind: "q", ph: LATE, title: "The approver is on SMS too",
          text: "To reset {fd}'s access you need an admin to approve it, but the only available admin also secures their own account with texted codes.",
          opts: [
            { q: 3, u: ["idp"], t: "Move the admin to a stronger factor before they approve anything",
              r: "The admin re-secures on an authenticator, then approves the reset from a trusted footing.",
              w: "An approver on the same weak factor is the next target. Fix their login before they act on a takeover." },
            { q: 0, t: "Let the admin approve it over SMS this once to save time",
              r: "The crew is already eyeing that admin's number.",
              w: "Approving a SIM-swap fix over the very factor that failed just hands them the next account." } ] },
        { id: "ss_quiet", kind: "s", ph: LATE, title: "Keep it off the record",
          text: "{fd} is mortified and asks you to handle it quietly, without telling the board or reporting the fraud, to avoid embarrassment.",
          opts: [
            { q: 3, t: "Support {fd}, and report the fraud",
              r: "{fd} is supported, and the bank fraud report and a measured leadership brief go ahead.",
              w: "Empathy for the victim, yes; but fraud reporting and governance duties aren't optional to spare embarrassment." },
            { q: 1, t: "Agree to keep it between the two of you",
              r: "The unreported fraud and unbriefed board become the bigger problem when it surfaces.",
              w: "Quietly burying a financial-fraud incident breaches reporting duties and compounds the fallout." },
            { q: 0, t: "Make an example of {fd} to warn others",
              r: "The next victim now hides their swap instead of reporting it fast.",
              w: "Blaming the victim kills the early reporting you depend on. Support them and report the fraud." } ] }
    ],

    /* ---------- 18. Hostile Takeover ---------- */
    registrar: [
        { id: "rg_cert", kind: "s", ph: MID, title: "A padlock that isn't yours",
          text: "Certificate transparency shows a valid TLS cert was issued for {org}'s name at 03:00. The fake site now shows a reassuring padlock.",
          opts: [
            { q: 3, t: "Report the rogue cert for revocation",
              r: "The revocation request is filed and staff and customers are told a lock alone doesn't prove it's really you.",
              w: "A rogue cert makes the fake convincing. Revoke it and reset the assumption that a padlock equals authentic." },
            { q: 0, t: "Ignore it since you'll fix the DNS anyway",
              r: "The cert outlives your DNS fix and keeps the fake site looking legitimate.",
              w: "Repointing records doesn't revoke a cert. Chase the revocation separately." } ] },
        { id: "rg_maildown", kind: "q", ph: MID, title: "Just use Gmail then",
          text: "With company email bouncing, staff start using personal accounts to keep working, scattering company conversations onto services you don't control.",
          opts: [
            { q: 3, t: "Set up an approved stopgap channel now",
              r: "A sanctioned stopgap goes out and the personal-account sprawl is reined in quickly.",
              w: "An outage tempts staff into shadow channels. Give them a controlled alternative before that becomes the norm." },
            { q: 0, t: "Let staff improvise so work doesn't stop",
              r: "Sensitive threads end up in personal inboxes you can't secure or retrieve.",
              w: "Improvised personal mail during an incident scatters data beyond your reach. Provide a proper channel." } ] },
        { id: "rg_othertld", kind: "q", ph: LATE, title: "The other domains",
          text: "{org} owns several country and product variants of its name. If the main one was taken, are the rest locked down?",
          opts: [
            { q: 3, t: "Audit every domain you own and apply the same locks and MFA",
              r: "Two neglected variants had weak logins; both are secured before anyone tries them.",
              w: "Attackers pivot to the domain you forgot you owned. Secure the whole portfolio, not just the flagship." },
            { q: 0, t: "Assume the others are fine and focus on the main one",
              r: "A forgotten variant with a weak login is the obvious next target.",
              w: "Unmanaged spare domains are soft targets. Bring them all under the same controls." } ] },
        { id: "rg_partner", kind: "s", ph: LATE, title: "A partner nearly paid",
          text: "A partner calls: they got an email from your look-alike address with 'updated bank details' and were about to pay an invoice to it.",
          opts: [
            { q: 3, t: "Warn all partners to verify bank details by phone",
              r: "The partner holds the payment and a clear warning stops others acting on the fake.",
              w: "A hijacked name turns your partners into targets. A direct warning and out-of-band verification stops the fraud." },
            { q: 0, t: "Tell just that one partner and hope others noticed",
              r: "Another partner didn't notice and pays the fake account.",
              w: "If one partner was targeted, all were. Warn them all." } ] }
    ],

    /* ---------- 19. Pocket Sized ---------- */
    mobile: [
        { id: "mb_moreexecs", kind: "s", ph: MID, title: "Same text, other phones",
          text: "Two more executives report the same parcel text. At least one admits they tapped it as well.",
          opts: [
            { q: 3, u: ["idp"], t: "Contain the second phone and warn all execs now",
              r: "The second device is contained and a clear warning stops the others acting on it.",
              w: "A targeted smish campaign hits several leaders. Contain every phone that tapped and warn the rest immediately." },
            { q: 1, t: "Wait to see if the others' phones misbehave first",
              r: "The one who tapped has their mailbox opened while you wait.",
              w: "If they tapped, treat the device as compromised now, not after symptoms." },
            { q: 0, t: "Assume only the CEO fell for it",
              r: "A second exec mailbox is being read by the afternoon.",
              w: "One confirmed victim in a campaign means checking everyone who got the text." } ] },
        { id: "mb_byod", kind: "q", ph: MID, title: "It's their personal phone",
          text: "{ceo}'s handset is personal, not company-issued. You have no management over it, so you can't just wipe it remotely.",
          opts: [
            { q: 3, u: ["idp"], t: "Cut its company access centrally and reset with {ceo}",
              r: "Company sessions and tokens are revoked centrally while {ceo} resets the device with your help.",
              w: "You may not control a personal phone, but you control what it can reach. Revoke access centrally, then reset with consent." },
            { q: 0, t: "Insist on wiping the whole personal phone immediately",
              r: "{ceo} refuses over personal photos, and the argument costs you an hour of access.",
              w: "You can't force-wipe an unmanaged personal device. Sever its access first, then agree a reset." } ] },
        { id: "mb_authenticator", kind: "q", ph: LATE, title: "The authenticator's on that phone",
          text: "Resetting {ceo}'s MFA needs their authenticator, which lives on the very phone you're treating as compromised.",
          opts: [
            { q: 3, u: ["idp"], t: "Re-issue the authenticator onto a clean device through an admin reset",
              r: "An admin resets the factor and {ceo} enrols fresh on a trusted device.",
              w: "Don't trust a factor on a compromised phone. Reset it centrally and re-enrol somewhere clean." },
            { q: 0, t: "Keep using the authenticator on the phone to avoid the hassle",
              r: "The phone can read those prompts, so the factor protects nothing.",
              w: "An authenticator on the compromised device is no protection. Move it off." } ] },
        { id: "mb_mna", kind: "s", ph: LATE, title: "What was in that mailbox",
          text: "{ceo}'s mailbox holds live deal and board correspondence. If it was read, the exposure goes well beyond IT.",
          opts: [
            { q: 3, t: "Scope what was read and brief legal and leadership",
              r: "The read history is scoped and legal and leadership are briefed on the deal-sensitive content.",
              w: "An executive mailbox exposure is a legal and market matter too. Scope what was seen and route it beyond IT." },
            { q: 0, t: "Handle it as a routine mailbox cleanup within the team",
              r: "The sensitive deal exposure surfaces later, unmanaged and worse for the delay.",
              w: "Deal-sensitive content read by an attacker needs legal and leadership, not a quiet cleanup." } ] }
    ],

    /* ---------- 20. Free Wi-Fi ---------- */
    eviltwin: [
        { id: "et_photo", kind: "q", ph: MID, title: "Great booth photo",
          text: "A rep proudly tweeted a photo from the expo booth. In the background: a laptop screen with the {saas} login open and the fake SSID in the Wi-Fi list.",
          opts: [
            { q: 3, t: "Get the photo taken down quickly",
              r: "It comes down after a few views and staff get a quick reminder about event posts.",
              w: "Event photos leak more than morale. Take it down and remind staff what's in shot before posting." },
            { q: 0, t: "Leave it, it's just a nice booth photo",
              r: "The visible session detail and network name are exactly what an onlooker wanted.",
              w: "A background screen at a live incident is a gift. Get it down." } ] },
        { id: "et_vpnoff", kind: "q", ph: MID, title: "The VPN was slow",
          text: "The affected staff mention they turned the VPN off because it was 'slow on the conference Wi-Fi', which is exactly when they needed it on.",
          opts: [
            { q: 3, t: "Ask them to re-enable it now",
              r: "The VPN goes back on and the performance complaint is logged to address properly.",
              w: "A VPN people switch off isn't a control. Get it back on now and fix the friction that made them disable it." },
            { q: 0, t: "Tell them off for turning it off and move on",
              r: "They turn it off again next time it's slow, and so does everyone else.",
              w: "Scolding won't fix a tool people find unusable. Address the friction as well as the behaviour." } ] },
        { id: "et_share", kind: "s", ph: MID, title: "We're probably not the only ones",
          text: "If a rogue hotspot ran all morning, other companies at the expo were likely hit too. The event organiser asks if you'll share what you found.",
          opts: [
            { q: 3, t: "Share sanitised indicators with the organiser and let them warn attendees",
              r: "The organiser warns attendees and shuts the rogue network down, without your case detail leaking.",
              w: "A shared venue threat is worth sharing, at the level of indicators. It protects others and gets the hotspot killed." },
            { q: 1, t: "Share the full detail of your incident to help them understand",
              r: "Sensitive specifics about your accounts end up in a wider circulation than you meant.",
              w: "Help the venue, but sanitise. You don't control where event-wide sharing travels." },
            { q: 0, t: "Say nothing and just protect your own people",
              r: "The hotspot runs all afternoon catching everyone else, including more of your late arrivals.",
              w: "Staying silent leaves the rogue network live for the next wave, yours included." } ] },
        { id: "et_reuse", kind: "s", ph: LATE, title: "Same password everywhere",
          text: "One of the caught staff admits the password they typed into the fake page is the same one they use on a customer-facing portal.",
          opts: [
            { q: 3, u: ["idp"], t: "Reset it everywhere and check the customer portal",
              r: "The reused password is reset across the board and the portal shows no misuse yet.",
              w: "A reused password turns one theft into many doors. Reset it everywhere and check where it's already been tried." },
            { q: 0, t: "Reset only the corporate login and leave the portal",
              r: "The same password opens the customer portal a day later.",
              w: "Reuse means the theft reaches every place the password is used. Reset all of them." } ] }
    ]
};
